/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   any_pattern.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_ANY_PATTERN_H
#define UHDM_ANY_PATTERN_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class AnyPattern final : public Any {
  UHDM_IMPLEMENT_RTTI(AnyPattern, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::AnyPattern;

  explicit AnyPattern(Serializer *serializer) : basetype_t(serializer) {}
  AnyPattern(Serializer *serializer, const AnyPattern& rhs);
  ~AnyPattern() override = default;
  AnyPattern(const AnyPattern& rhs) = delete;
  AnyPattern& operator=(const AnyPattern& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  uint32_t getVpiType() const override { return vpiAnyPattern; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::AnyPattern; }


protected:
  SymbolId m_name = BadSymbolId;
};
}  // namespace uhdm

#endif
