/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   array_typespec.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_ARRAY_TYPESPEC_H
#define UHDM_ARRAY_TYPESPEC_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/typespec.h>

namespace uhdm {
class ArrayTypespec final : public Typespec {
  UHDM_IMPLEMENT_RTTI(ArrayTypespec, Typespec)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ArrayTypespec;

  explicit ArrayTypespec(Serializer *serializer) : basetype_t(serializer) {}
  ArrayTypespec(Serializer *serializer, const ArrayTypespec& rhs);
  ~ArrayTypespec() override = default;
  ArrayTypespec(const ArrayTypespec& rhs) = delete;
  ArrayTypespec& operator=(const ArrayTypespec& rhs) = delete;

  int32_t getArrayType() const { return m_arrayType; }
  bool setArrayType(int32_t data) {
    m_arrayType = data;
    return true;
  }

  bool getPacked() const { return m_packed; }
  bool setPacked(bool data) {
    m_packed = data;
    return true;
  }

  Range* getRange() { return m_range; }
  const Range* getRange() const { return m_range; }
  template <typename T> T* getRange() { return any_cast<T>(m_range); }
  template <typename T> const T* getRange() const { return any_cast<T>(m_range); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setRange(T, bool = false) = delete;
  bool setRange(Range* data, bool force = false) {
    if ((m_range == nullptr) || (data == nullptr) || force) {
      m_range = data;
      return true;
    }
    return false;
  }

  RefTypespec* getIndexTypespec() { return m_indexTypespec; }
  const RefTypespec* getIndexTypespec() const { return m_indexTypespec; }
  template <typename T> T* getIndexTypespec() { return any_cast<T>(m_indexTypespec); }
  template <typename T> const T* getIndexTypespec() const { return any_cast<T>(m_indexTypespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setIndexTypespec(T, bool = false) = delete;
  bool setIndexTypespec(RefTypespec* data, bool force = false) {
    if ((m_indexTypespec == nullptr) || (data == nullptr) || force) {
      m_indexTypespec = data;
      return true;
    }
    return false;
  }

  RefTypespec* getElemTypespec() { return m_elemTypespec; }
  const RefTypespec* getElemTypespec() const { return m_elemTypespec; }
  template <typename T> T* getElemTypespec() { return any_cast<T>(m_elemTypespec); }
  template <typename T> const T* getElemTypespec() const { return any_cast<T>(m_elemTypespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setElemTypespec(T, bool = false) = delete;
  bool setElemTypespec(RefTypespec* data, bool force = false) {
    if ((m_elemTypespec == nullptr) || (data == nullptr) || force) {
      m_elemTypespec = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiArrayTypespec; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ArrayTypespec; }


protected:
  int32_t m_arrayType = 0;
  bool m_packed = false;
  Range* m_range = nullptr;
  RefTypespec* m_indexTypespec = nullptr;
  RefTypespec* m_elemTypespec = nullptr;
};
}  // namespace uhdm

#endif
