/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   bind_directive.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_BIND_DIRECTIVE_H
#define UHDM_BIND_DIRECTIVE_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class BindDirective final : public Any {
  UHDM_IMPLEMENT_RTTI(BindDirective, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::BindDirective;

  explicit BindDirective(Serializer *serializer) : basetype_t(serializer) {}
  BindDirective(Serializer *serializer, const BindDirective& rhs);
  ~BindDirective() override = default;
  BindDirective(const BindDirective& rhs) = delete;
  BindDirective& operator=(const BindDirective& rhs) = delete;

  RefTypespec* getBindTargetScope() { return m_bindTargetScope; }
  const RefTypespec* getBindTargetScope() const { return m_bindTargetScope; }
  template <typename T> T* getBindTargetScope() { return any_cast<T>(m_bindTargetScope); }
  template <typename T> const T* getBindTargetScope() const { return any_cast<T>(m_bindTargetScope); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setBindTargetScope(T, bool = false) = delete;
  bool setBindTargetScope(RefTypespec* data, bool force = false) {
    if ((m_bindTargetScope == nullptr) || (data == nullptr) || force) {
      m_bindTargetScope = data;
      return true;
    }
    return false;
  }

  AnyCollection* getBindTargetInstances() const { return m_bindTargetInstances; }
  template<typename T> AnyCollection* getBindTargetInstances(T) = delete;
  AnyCollection* getBindTargetInstances(bool createIfNull);
  bool setBindTargetInstances(AnyCollection* data, bool force = false) {
    if ((m_bindTargetInstances == nullptr) || (data == nullptr) || force) {
      m_bindTargetInstances = data;
      return true;
    }
    return false;
  }

  Any* getBindSourceInstance() { return m_bindSourceInstance; }
  const Any* getBindSourceInstance() const { return m_bindSourceInstance; }
  template <typename T> T* getBindSourceInstance() { return any_cast<T>(m_bindSourceInstance); }
  template <typename T> const T* getBindSourceInstance() const { return any_cast<T>(m_bindSourceInstance); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setBindSourceInstance(T, bool = false) = delete;
  bool setBindSourceInstance(Any* data, bool force = false) {
    if ((m_bindSourceInstance == nullptr) || (data == nullptr) || force) {
      m_bindSourceInstance = data;
      return true;
    }
    return false;
  }

  AttributeCollection* getAttributes() const { return m_attributes; }
  template<typename T> AttributeCollection* getAttributes(T) = delete;
  AttributeCollection* getAttributes(bool createIfNull);
  bool setAttributes(AttributeCollection* data, bool force = false) {
    if ((m_attributes == nullptr) || (data == nullptr) || force) {
      m_attributes = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiBindDirective; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::BindDirective; }


protected:
  RefTypespec* m_bindTargetScope = nullptr;
  AnyCollection* m_bindTargetInstances = nullptr;
  Any* m_bindSourceInstance = nullptr;
  AttributeCollection* m_attributes = nullptr;
};
}  // namespace uhdm

#endif
