/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   bit_typespec.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_BIT_TYPESPEC_H
#define UHDM_BIT_TYPESPEC_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/typespec.h>

namespace uhdm {
class BitTypespec final : public Typespec {
  UHDM_IMPLEMENT_RTTI(BitTypespec, Typespec)

public:
  static constexpr UhdmType kUhdmType = UhdmType::BitTypespec;

  explicit BitTypespec(Serializer *serializer) : basetype_t(serializer) {}
  BitTypespec(Serializer *serializer, const BitTypespec& rhs);
  ~BitTypespec() override = default;
  BitTypespec(const BitTypespec& rhs) = delete;
  BitTypespec& operator=(const BitTypespec& rhs) = delete;

  RangeCollection* getRanges() const { return m_ranges; }
  template<typename T> RangeCollection* getRanges(T) = delete;
  RangeCollection* getRanges(bool createIfNull);
  bool setRanges(RangeCollection* data, bool force = false) {
    if ((m_ranges == nullptr) || (data == nullptr) || force) {
      m_ranges = data;
      return true;
    }
    return false;
  }

  RefTypespec* getIndexTypespec() { return m_indexTypespec; }
  const RefTypespec* getIndexTypespec() const { return m_indexTypespec; }
  template <typename T> T* getIndexTypespec() { return any_cast<T>(m_indexTypespec); }
  template <typename T> const T* getIndexTypespec() const { return any_cast<T>(m_indexTypespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setIndexTypespec(T, bool = false) = delete;
  bool setIndexTypespec(RefTypespec* data, bool force = false) {
    if ((m_indexTypespec == nullptr) || (data == nullptr) || force) {
      m_indexTypespec = data;
      return true;
    }
    return false;
  }

  bool getSigned() const { return m_signed; }
  bool setSigned(bool data) {
    m_signed = data;
    return true;
  }

  bool getScalar() const { return m_scalar; }
  bool setScalar(bool data) {
    m_scalar = data;
    return true;
  }

  bool getVector() const { return m_vector; }
  bool setVector(bool data) {
    m_vector = data;
    return true;
  }

  uint32_t getVpiType() const override { return vpiBitTypespec; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::BitTypespec; }


protected:
  RangeCollection* m_ranges = nullptr;
  RefTypespec* m_indexTypespec = nullptr;
  bool m_signed = false;
  bool m_scalar = false;
  bool m_vector = false;
};
}  // namespace uhdm

#endif
