/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   case_property_item.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CASE_PROPERTY_ITEM_H
#define UHDM_CASE_PROPERTY_ITEM_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class CasePropertyItem final : public Any {
  UHDM_IMPLEMENT_RTTI(CasePropertyItem, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::CasePropertyItem;

  explicit CasePropertyItem(Serializer *serializer) : basetype_t(serializer) {}
  CasePropertyItem(Serializer *serializer, const CasePropertyItem& rhs);
  ~CasePropertyItem() override = default;
  CasePropertyItem(const CasePropertyItem& rhs) = delete;
  CasePropertyItem& operator=(const CasePropertyItem& rhs) = delete;

  ExprCollection* getExprs() const { return m_exprs; }
  template<typename T> ExprCollection* getExprs(T) = delete;
  ExprCollection* getExprs(bool createIfNull);
  bool setExprs(ExprCollection* data, bool force = false) {
    if ((m_exprs == nullptr) || (data == nullptr) || force) {
      m_exprs = data;
      return true;
    }
    return false;
  }

  Any* getPropertyExpr() { return m_propertyExpr; }
  const Any* getPropertyExpr() const { return m_propertyExpr; }
  template <typename T> T* getPropertyExpr() { return any_cast<T>(m_propertyExpr); }
  template <typename T> const T* getPropertyExpr() const { return any_cast<T>(m_propertyExpr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setPropertyExpr(T, bool = false) = delete;
  bool setPropertyExpr(Any* data, bool force = false) {
    if ((m_propertyExpr == nullptr) || (data == nullptr) || force) {
      m_propertyExpr = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiCasePropertyItem; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::CasePropertyItem; }


protected:
  ExprCollection* m_exprs = nullptr;
  Any* m_propertyExpr = nullptr;
};
}  // namespace uhdm

#endif
