/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   checker_decl.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CHECKER_DECL_H
#define UHDM_CHECKER_DECL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/instance.h>

namespace uhdm {
class CheckerDecl final : public Instance {
  UHDM_IMPLEMENT_RTTI(CheckerDecl, Instance)

public:
  static constexpr UhdmType kUhdmType = UhdmType::CheckerDecl;

  explicit CheckerDecl(Serializer *serializer) : basetype_t(serializer) {}
  CheckerDecl(Serializer *serializer, const CheckerDecl& rhs);
  ~CheckerDecl() override = default;
  CheckerDecl(const CheckerDecl& rhs) = delete;
  CheckerDecl& operator=(const CheckerDecl& rhs) = delete;

  ClockingBlock* getGlobalClocking() { return m_globalClocking; }
  const ClockingBlock* getGlobalClocking() const { return m_globalClocking; }
  template <typename T> T* getGlobalClocking() { return any_cast<T>(m_globalClocking); }
  template <typename T> const T* getGlobalClocking() const { return any_cast<T>(m_globalClocking); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setGlobalClocking(T, bool = false) = delete;
  bool setGlobalClocking(ClockingBlock* data, bool force = false) {
    if ((m_globalClocking == nullptr) || (data == nullptr) || force) {
      m_globalClocking = data;
      return true;
    }
    return false;
  }

  ClockingBlock* getDefaultClocking() { return m_defaultClocking; }
  const ClockingBlock* getDefaultClocking() const { return m_defaultClocking; }
  template <typename T> T* getDefaultClocking() { return any_cast<T>(m_defaultClocking); }
  template <typename T> const T* getDefaultClocking() const { return any_cast<T>(m_defaultClocking); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setDefaultClocking(T, bool = false) = delete;
  bool setDefaultClocking(ClockingBlock* data, bool force = false) {
    if ((m_defaultClocking == nullptr) || (data == nullptr) || force) {
      m_defaultClocking = data;
      return true;
    }
    return false;
  }

  ClockingBlockCollection* getClockingBlocks() const { return m_clockingBlocks; }
  template<typename T> ClockingBlockCollection* getClockingBlocks(T) = delete;
  ClockingBlockCollection* getClockingBlocks(bool createIfNull);
  bool setClockingBlocks(ClockingBlockCollection* data, bool force = false) {
    if ((m_clockingBlocks == nullptr) || (data == nullptr) || force) {
      m_clockingBlocks = data;
      return true;
    }
    return false;
  }

  ProcessCollection* getProcesses() const { return m_processes; }
  template<typename T> ProcessCollection* getProcesses(T) = delete;
  ProcessCollection* getProcesses(bool createIfNull);
  bool setProcesses(ProcessCollection* data, bool force = false) {
    if ((m_processes == nullptr) || (data == nullptr) || force) {
      m_processes = data;
      return true;
    }
    return false;
  }

  ContAssignCollection* getContAssigns() const { return m_contAssigns; }
  template<typename T> ContAssignCollection* getContAssigns(T) = delete;
  ContAssignCollection* getContAssigns(bool createIfNull);
  bool setContAssigns(ContAssignCollection* data, bool force = false) {
    if ((m_contAssigns == nullptr) || (data == nullptr) || force) {
      m_contAssigns = data;
      return true;
    }
    return false;
  }

  CheckerPortCollection* getPorts() const { return m_ports; }
  template<typename T> CheckerPortCollection* getPorts(T) = delete;
  CheckerPortCollection* getPorts(bool createIfNull);
  bool setPorts(CheckerPortCollection* data, bool force = false) {
    if ((m_ports == nullptr) || (data == nullptr) || force) {
      m_ports = data;
      return true;
    }
    return false;
  }

  Any* getDefaultDisableIff() { return m_defaultDisableIff; }
  const Any* getDefaultDisableIff() const { return m_defaultDisableIff; }
  template <typename T> T* getDefaultDisableIff() { return any_cast<T>(m_defaultDisableIff); }
  template <typename T> const T* getDefaultDisableIff() const { return any_cast<T>(m_defaultDisableIff); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setDefaultDisableIff(T, bool = false) = delete;
  bool setDefaultDisableIff(Any* data, bool force = false) {
    if ((m_defaultDisableIff == nullptr) || (data == nullptr) || force) {
      m_defaultDisableIff = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiCheckerDecl; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::CheckerDecl; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  ClockingBlock* m_globalClocking = nullptr;
  ClockingBlock* m_defaultClocking = nullptr;
  ClockingBlockCollection* m_clockingBlocks = nullptr;
  ProcessCollection* m_processes = nullptr;
  ContAssignCollection* m_contAssigns = nullptr;
  CheckerPortCollection* m_ports = nullptr;
  Any* m_defaultDisableIff = nullptr;
};
}  // namespace uhdm

#endif
