/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   class_obj.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CLASS_OBJ_H
#define UHDM_CLASS_OBJ_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/scope.h>

namespace uhdm {
class ClassObj final : public Scope {
  UHDM_IMPLEMENT_RTTI(ClassObj, Scope)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ClassObj;

  explicit ClassObj(Serializer *serializer) : basetype_t(serializer) {}
  ClassObj(Serializer *serializer, const ClassObj& rhs);
  ~ClassObj() override = default;
  ClassObj(const ClassObj& rhs) = delete;
  ClassObj& operator=(const ClassObj& rhs) = delete;

  int32_t getObjId() const { return m_objId; }
  bool setObjId(int32_t data) {
    m_objId = data;
    return true;
  }

  RefTypespec* getClassTypespec() { return m_classTypespec; }
  const RefTypespec* getClassTypespec() const { return m_classTypespec; }
  template <typename T> T* getClassTypespec() { return any_cast<T>(m_classTypespec); }
  template <typename T> const T* getClassTypespec() const { return any_cast<T>(m_classTypespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setClassTypespec(T, bool = false) = delete;
  bool setClassTypespec(RefTypespec* data, bool force = false) {
    if ((m_classTypespec == nullptr) || (data == nullptr) || force) {
      m_classTypespec = data;
      return true;
    }
    return false;
  }

  ThreadCollection* getThreads() const { return m_threads; }
  template<typename T> ThreadCollection* getThreads(T) = delete;
  ThreadCollection* getThreads(bool createIfNull);
  bool setThreads(ThreadCollection* data, bool force = false) {
    if ((m_threads == nullptr) || (data == nullptr) || force) {
      m_threads = data;
      return true;
    }
    return false;
  }

  ExprCollection* getMessages() const { return m_messages; }
  template<typename T> ExprCollection* getMessages(T) = delete;
  ExprCollection* getMessages(bool createIfNull);
  bool setMessages(ExprCollection* data, bool force = false) {
    if ((m_messages == nullptr) || (data == nullptr) || force) {
      m_messages = data;
      return true;
    }
    return false;
  }

  TaskFuncCollection* getTaskFuncs() const { return m_taskFuncs; }
  template<typename T> TaskFuncCollection* getTaskFuncs(T) = delete;
  TaskFuncCollection* getTaskFuncs(bool createIfNull);
  bool setTaskFuncs(TaskFuncCollection* data, bool force = false) {
    if ((m_taskFuncs == nullptr) || (data == nullptr) || force) {
      m_taskFuncs = data;
      return true;
    }
    return false;
  }

  ConstraintCollection* getConstraints() const { return m_constraints; }
  template<typename T> ConstraintCollection* getConstraints(T) = delete;
  ConstraintCollection* getConstraints(bool createIfNull);
  bool setConstraints(ConstraintCollection* data, bool force = false) {
    if ((m_constraints == nullptr) || (data == nullptr) || force) {
      m_constraints = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiClassObj; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ClassObj; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  int32_t m_objId = 0;
  RefTypespec* m_classTypespec = nullptr;
  ThreadCollection* m_threads = nullptr;
  ExprCollection* m_messages = nullptr;
  TaskFuncCollection* m_taskFuncs = nullptr;
  ConstraintCollection* m_constraints = nullptr;
};
}  // namespace uhdm

#endif
