/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   class_typespec.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CLASS_TYPESPEC_H
#define UHDM_CLASS_TYPESPEC_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/typespec.h>

namespace uhdm {
class ClassTypespec final : public Typespec {
  UHDM_IMPLEMENT_RTTI(ClassTypespec, Typespec)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ClassTypespec;

  explicit ClassTypespec(Serializer *serializer) : basetype_t(serializer) {}
  ClassTypespec(Serializer *serializer, const ClassTypespec& rhs);
  ~ClassTypespec() override = default;
  ClassTypespec(const ClassTypespec& rhs) = delete;
  ClassTypespec& operator=(const ClassTypespec& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  AnyCollection* getParameters() const { return m_parameters; }
  template<typename T> AnyCollection* getParameters(T) = delete;
  AnyCollection* getParameters(bool createIfNull);
  bool setParameters(AnyCollection* data, bool force = false) {
    if ((m_parameters == nullptr) || (data == nullptr) || force) {
      m_parameters = data;
      return true;
    }
    return false;
  }

  ParamAssignCollection* getParamAssigns() const { return m_paramAssigns; }
  template<typename T> ParamAssignCollection* getParamAssigns(T) = delete;
  ParamAssignCollection* getParamAssigns(bool createIfNull);
  bool setParamAssigns(ParamAssignCollection* data, bool force = false) {
    if ((m_paramAssigns == nullptr) || (data == nullptr) || force) {
      m_paramAssigns = data;
      return true;
    }
    return false;
  }

  ClassDefn* getClassDefn() { return m_classDefn; }
  const ClassDefn* getClassDefn() const { return m_classDefn; }
  template <typename T> T* getClassDefn() { return any_cast<T>(m_classDefn); }
  template <typename T> const T* getClassDefn() const { return any_cast<T>(m_classDefn); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setClassDefn(T, bool = false) = delete;
  bool setClassDefn(ClassDefn* data, bool force = false) {
    if ((m_classDefn == nullptr) || (data == nullptr) || force) {
      m_classDefn = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiClassTypespec; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ClassTypespec; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  SymbolId m_name = BadSymbolId;
  AnyCollection* m_parameters = nullptr;
  ParamAssignCollection* m_paramAssigns = nullptr;
  ClassDefn* m_classDefn = nullptr;
};
}  // namespace uhdm

#endif
