/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   clocking_block.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CLOCKING_BLOCK_H
#define UHDM_CLOCKING_BLOCK_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/scope.h>

namespace uhdm {
class ClockingBlock final : public Scope {
  UHDM_IMPLEMENT_RTTI(ClockingBlock, Scope)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ClockingBlock;

  explicit ClockingBlock(Serializer *serializer) : basetype_t(serializer) {}
  ClockingBlock(Serializer *serializer, const ClockingBlock& rhs);
  ~ClockingBlock() override = default;
  ClockingBlock(const ClockingBlock& rhs) = delete;
  ClockingBlock& operator=(const ClockingBlock& rhs) = delete;

  int32_t getInputEdge() const { return m_inputEdge; }
  bool setInputEdge(int32_t data) {
    m_inputEdge = data;
    return true;
  }

  int32_t getOutputEdge() const { return m_outputEdge; }
  bool setOutputEdge(int32_t data) {
    m_outputEdge = data;
    return true;
  }

  DelayControl* getInputSkew() { return m_inputSkew; }
  const DelayControl* getInputSkew() const { return m_inputSkew; }
  template <typename T> T* getInputSkew() { return any_cast<T>(m_inputSkew); }
  template <typename T> const T* getInputSkew() const { return any_cast<T>(m_inputSkew); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInputSkew(T, bool = false) = delete;
  bool setInputSkew(DelayControl* data, bool force = false) {
    if ((m_inputSkew == nullptr) || (data == nullptr) || force) {
      m_inputSkew = data;
      return true;
    }
    return false;
  }

  DelayControl* getOutputSkew() { return m_outputSkew; }
  const DelayControl* getOutputSkew() const { return m_outputSkew; }
  template <typename T> T* getOutputSkew() { return any_cast<T>(m_outputSkew); }
  template <typename T> const T* getOutputSkew() const { return any_cast<T>(m_outputSkew); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setOutputSkew(T, bool = false) = delete;
  bool setOutputSkew(DelayControl* data, bool force = false) {
    if ((m_outputSkew == nullptr) || (data == nullptr) || force) {
      m_outputSkew = data;
      return true;
    }
    return false;
  }

  EventControl* getClockingEvent() { return m_clockingEvent; }
  const EventControl* getClockingEvent() const { return m_clockingEvent; }
  template <typename T> T* getClockingEvent() { return any_cast<T>(m_clockingEvent); }
  template <typename T> const T* getClockingEvent() const { return any_cast<T>(m_clockingEvent); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setClockingEvent(T, bool = false) = delete;
  bool setClockingEvent(EventControl* data, bool force = false) {
    if ((m_clockingEvent == nullptr) || (data == nullptr) || force) {
      m_clockingEvent = data;
      return true;
    }
    return false;
  }

  Instance* getInstance() { return m_instance; }
  const Instance* getInstance() const { return m_instance; }
  template <typename T> T* getInstance() { return any_cast<T>(m_instance); }
  template <typename T> const T* getInstance() const { return any_cast<T>(m_instance); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInstance(T, bool = false) = delete;
  bool setInstance(Instance* data, bool force = false) {
    if ((m_instance == nullptr) || (data == nullptr) || force) {
      m_instance = data;
      return true;
    }
    return false;
  }

  ClockingIODeclCollection* getClockingIODecls() const { return m_clockingIODecls; }
  template<typename T> ClockingIODeclCollection* getClockingIODecls(T) = delete;
  ClockingIODeclCollection* getClockingIODecls(bool createIfNull);
  bool setClockingIODecls(ClockingIODeclCollection* data, bool force = false) {
    if ((m_clockingIODecls == nullptr) || (data == nullptr) || force) {
      m_clockingIODecls = data;
      return true;
    }
    return false;
  }

  Variable* getPrefix() { return m_prefix; }
  const Variable* getPrefix() const { return m_prefix; }
  template <typename T> T* getPrefix() { return any_cast<T>(m_prefix); }
  template <typename T> const T* getPrefix() const { return any_cast<T>(m_prefix); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setPrefix(T, bool = false) = delete;
  bool setPrefix(Variable* data, bool force = false) {
    if ((m_prefix == nullptr) || (data == nullptr) || force) {
      m_prefix = data;
      return true;
    }
    return false;
  }

  ClockingBlock* getActual() { return m_actual; }
  const ClockingBlock* getActual() const { return m_actual; }
  template <typename T> T* getActual() { return any_cast<T>(m_actual); }
  template <typename T> const T* getActual() const { return any_cast<T>(m_actual); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setActual(T, bool = false) = delete;
  bool setActual(ClockingBlock* data, bool force = false) {
    if ((m_actual == nullptr) || (data == nullptr) || force) {
      m_actual = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiClockingBlock; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ClockingBlock; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  int32_t m_inputEdge = 0;
  int32_t m_outputEdge = 0;
  DelayControl* m_inputSkew = nullptr;
  DelayControl* m_outputSkew = nullptr;
  EventControl* m_clockingEvent = nullptr;
  Instance* m_instance = nullptr;
  ClockingIODeclCollection* m_clockingIODecls = nullptr;
  Variable* m_prefix = nullptr;
  ClockingBlock* m_actual = nullptr;
};
}  // namespace uhdm

#endif
