/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   clocked_property.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CLOCKED_PROPERTY_H
#define UHDM_CLOCKED_PROPERTY_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class ClockedProperty final : public Any {
  UHDM_IMPLEMENT_RTTI(ClockedProperty, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ClockedProperty;

  explicit ClockedProperty(Serializer *serializer) : basetype_t(serializer) {}
  ClockedProperty(Serializer *serializer, const ClockedProperty& rhs);
  ~ClockedProperty() override = default;
  ClockedProperty(const ClockedProperty& rhs) = delete;
  ClockedProperty& operator=(const ClockedProperty& rhs) = delete;

  Expr* getClockingEvent() { return m_clockingEvent; }
  const Expr* getClockingEvent() const { return m_clockingEvent; }
  template <typename T> T* getClockingEvent() { return any_cast<T>(m_clockingEvent); }
  template <typename T> const T* getClockingEvent() const { return any_cast<T>(m_clockingEvent); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setClockingEvent(T, bool = false) = delete;
  bool setClockingEvent(Expr* data, bool force = false) {
    if ((m_clockingEvent == nullptr) || (data == nullptr) || force) {
      m_clockingEvent = data;
      return true;
    }
    return false;
  }

  Any* getPropertyExpr() { return m_propertyExpr; }
  const Any* getPropertyExpr() const { return m_propertyExpr; }
  template <typename T> T* getPropertyExpr() { return any_cast<T>(m_propertyExpr); }
  template <typename T> const T* getPropertyExpr() const { return any_cast<T>(m_propertyExpr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setPropertyExpr(T, bool = false) = delete;
  bool setPropertyExpr(Any* data, bool force = false) {
    if ((m_propertyExpr == nullptr) || (data == nullptr) || force) {
      m_propertyExpr = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiClockedProp; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ClockedProperty; }


protected:
  Expr* m_clockingEvent = nullptr;
  Any* m_propertyExpr = nullptr;
};
}  // namespace uhdm

#endif
