// -*- c++ -*-

/*
 Do not modify, auto-generated by cloner.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Cloner.h
 * Author: hs
 *
 * Created on July 14, 2023, 00:00 AM
 */
#ifndef UHDM_CLONER_H
#define UHDM_CLONER_H

#include <uhdm/RTTI.h>
#include <uhdm/Serializer.h>
#include <uhdm/containers.h>

#include <map>

namespace uhdm {
// Three different variants of Cloning
//
// Cloner:
//   * Default implementation where every node in the graph gets duplicated.
//   * Nodes are cloned based on the number of times they are referenced.
//   * Number of nodes in cloned graph are likely to be greater then
//     the input graph.
// PassThroughCloner:
//   * This is opposite of the default cloner where none of the nodes
//     are duplicated.
//   * As such, this implementation is of no practical use but can be used
//     as a base where only certain nodes need to be duplicated.
// MirrorCloner:
//   * This generates an exact clone of the input graph.

class Cloner : public RTTI {
  UHDM_IMPLEMENT_RTTI(Cloner, RTTI)

 protected:
  using callstack_t = std::vector<const Any *>;

 public:
  explicit Cloner(Serializer *serializer) : m_serializer(serializer) {}
  virtual ~Cloner() = default;
  Cloner(const Cloner &rhs) = delete;
  Cloner &operator=(const Cloner &rhs) = delete;

  Serializer *getSerializer() { return m_serializer; }

  template <typename T>
  T *clone(const T *source, Any *parent) {
    return static_cast<T *>(cloneAny(static_cast<const Any *>(source), parent));
  }

 private:
  template <typename T>
  T *cloneT(const T *source, Any *parent);

 protected:
  template <typename T>
  std::vector<T *> *cloneT(const std::vector<T *> *source);

  template <typename T>
  std::vector<T *> *cloneT(const std::vector<T *> *source, Any *parent);

  virtual Any *cloneAny(const Any *source, Any *parent);

  // clang-format off
  virtual void copy(const Any* source, Any* target);
  virtual void copy(const Alias* source, Alias* target);
  virtual void copy(const Always* source, Always* target);
  virtual void copy(const AnyPattern* source, AnyPattern* target);
  virtual void copy(const ArrayExpr* source, ArrayExpr* target);
  virtual void copy(const ArrayTypespec* source, ArrayTypespec* target);
  virtual void copy(const Assert* source, Assert* target);
  virtual void copy(const AssignStmt* source, AssignStmt* target);
  virtual void copy(const Assignment* source, Assignment* target);
  virtual void copy(const Assume* source, Assume* target);
  virtual void copy(const AtomicStmt* source, AtomicStmt* target);
  virtual void copy(const Attribute* source, Attribute* target);
  virtual void copy(const Begin* source, Begin* target);
  virtual void copy(const BindDirective* source, BindDirective* target);
  virtual void copy(const BitSelect* source, BitSelect* target);
  virtual void copy(const BitTypespec* source, BitTypespec* target);
  virtual void copy(const BreakStmt* source, BreakStmt* target);
  virtual void copy(const ByteTypespec* source, ByteTypespec* target);
  virtual void copy(const CaseItem* source, CaseItem* target);
  virtual void copy(const CaseProperty* source, CaseProperty* target);
  virtual void copy(const CasePropertyItem* source, CasePropertyItem* target);
  virtual void copy(const CaseStmt* source, CaseStmt* target);
  virtual void copy(const ChandleTypespec* source, ChandleTypespec* target);
  virtual void copy(const CheckerDecl* source, CheckerDecl* target);
  virtual void copy(const CheckerInst* source, CheckerInst* target);
  virtual void copy(const CheckerInstPort* source, CheckerInstPort* target);
  virtual void copy(const CheckerPort* source, CheckerPort* target);
  virtual void copy(const ClassDefn* source, ClassDefn* target);
  virtual void copy(const ClassObj* source, ClassObj* target);
  virtual void copy(const ClassTypespec* source, ClassTypespec* target);
  virtual void copy(const Clause* source, Clause* target);
  virtual void copy(const ClockedProperty* source, ClockedProperty* target);
  virtual void copy(const ClockedSeq* source, ClockedSeq* target);
  virtual void copy(const ClockingBlock* source, ClockingBlock* target);
  virtual void copy(const ClockingIODecl* source, ClockingIODecl* target);
  virtual void copy(const Comment* source, Comment* target);
  virtual void copy(const ConcurrentAssertions* source, ConcurrentAssertions* target);
  virtual void copy(const ConfigDecl* source, ConfigDecl* target);
  virtual void copy(const ConfigRule* source, ConfigRule* target);
  virtual void copy(const Constant* source, Constant* target);
  virtual void copy(const ConstrForeach* source, ConstrForeach* target);
  virtual void copy(const ConstrIf* source, ConstrIf* target);
  virtual void copy(const ConstrIfElse* source, ConstrIfElse* target);
  virtual void copy(const Constraint* source, Constraint* target);
  virtual void copy(const ConstraintExpr* source, ConstraintExpr* target);
  virtual void copy(const ConstraintOrdering* source, ConstraintOrdering* target);
  virtual void copy(const ContAssign* source, ContAssign* target);
  virtual void copy(const ContAssignBit* source, ContAssignBit* target);
  virtual void copy(const ContinueStmt* source, ContinueStmt* target);
  virtual void copy(const Cover* source, Cover* target);
  virtual void copy(const CoverBin* source, CoverBin* target);
  virtual void copy(const CoverCross* source, CoverCross* target);
  virtual void copy(const CoverGroup* source, CoverGroup* target);
  virtual void copy(const CoverPoint* source, CoverPoint* target);
  virtual void copy(const CoverageOption* source, CoverageOption* target);
  virtual void copy(const Deassign* source, Deassign* target);
  virtual void copy(const DefParam* source, DefParam* target);
  virtual void copy(const DelayControl* source, DelayControl* target);
  virtual void copy(const DelayTerm* source, DelayTerm* target);
  virtual void copy(const Design* source, Design* target);
  virtual void copy(const Disable* source, Disable* target);
  virtual void copy(const DisableFork* source, DisableFork* target);
  virtual void copy(const Disables* source, Disables* target);
  virtual void copy(const DistItem* source, DistItem* target);
  virtual void copy(const Distribution* source, Distribution* target);
  virtual void copy(const DoWhile* source, DoWhile* target);
  virtual void copy(const EnumConst* source, EnumConst* target);
  virtual void copy(const EnumTypespec* source, EnumTypespec* target);
  virtual void copy(const EventControl* source, EventControl* target);
  virtual void copy(const EventStmt* source, EventStmt* target);
  virtual void copy(const EventTypespec* source, EventTypespec* target);
  virtual void copy(const ExpectStmt* source, ExpectStmt* target);
  virtual void copy(const Expr* source, Expr* target);
  virtual void copy(const Extends* source, Extends* target);
  virtual void copy(const FinalStmt* source, FinalStmt* target);
  virtual void copy(const ForStmt* source, ForStmt* target);
  virtual void copy(const Force* source, Force* target);
  virtual void copy(const ForeachStmt* source, ForeachStmt* target);
  virtual void copy(const ForeverStmt* source, ForeverStmt* target);
  virtual void copy(const ForkStmt* source, ForkStmt* target);
  virtual void copy(const FuncCall* source, FuncCall* target);
  virtual void copy(const Function* source, Function* target);
  virtual void copy(const FunctionDecl* source, FunctionDecl* target);
  virtual void copy(const Gate* source, Gate* target);
  virtual void copy(const GateArray* source, GateArray* target);
  virtual void copy(const GenCase* source, GenCase* target);
  virtual void copy(const GenFor* source, GenFor* target);
  virtual void copy(const GenIf* source, GenIf* target);
  virtual void copy(const GenIfElse* source, GenIfElse* target);
  virtual void copy(const GenRegion* source, GenRegion* target);
  virtual void copy(const GenScope* source, GenScope* target);
  virtual void copy(const GenScopeArray* source, GenScopeArray* target);
  virtual void copy(const GenStmt* source, GenStmt* target);
  virtual void copy(const HierPath* source, HierPath* target);
  virtual void copy(const IODecl* source, IODecl* target);
  virtual void copy(const Identifier* source, Identifier* target);
  virtual void copy(const IfElse* source, IfElse* target);
  virtual void copy(const IfStmt* source, IfStmt* target);
  virtual void copy(const ImmediateAssert* source, ImmediateAssert* target);
  virtual void copy(const ImmediateAssume* source, ImmediateAssume* target);
  virtual void copy(const ImmediateCover* source, ImmediateCover* target);
  virtual void copy(const Implements* source, Implements* target);
  virtual void copy(const Implication* source, Implication* target);
  virtual void copy(const ImportTypespec* source, ImportTypespec* target);
  virtual void copy(const IncludeStmt* source, IncludeStmt* target);
  virtual void copy(const IndexedPartSelect* source, IndexedPartSelect* target);
  virtual void copy(const Initial* source, Initial* target);
  virtual void copy(const Instance* source, Instance* target);
  virtual void copy(const InstanceArray* source, InstanceArray* target);
  virtual void copy(const IntTypespec* source, IntTypespec* target);
  virtual void copy(const IntegerTypespec* source, IntegerTypespec* target);
  virtual void copy(const Interface* source, Interface* target);
  virtual void copy(const InterfaceArray* source, InterfaceArray* target);
  virtual void copy(const InterfaceTFDecl* source, InterfaceTFDecl* target);
  virtual void copy(const InterfaceTypespec* source, InterfaceTypespec* target);
  virtual void copy(const LetDecl* source, LetDecl* target);
  virtual void copy(const LetExpr* source, LetExpr* target);
  virtual void copy(const Library* source, Library* target);
  virtual void copy(const LogicTypespec* source, LogicTypespec* target);
  virtual void copy(const LongIntTypespec* source, LongIntTypespec* target);
  virtual void copy(const MethodFuncCall* source, MethodFuncCall* target);
  virtual void copy(const MethodTaskCall* source, MethodTaskCall* target);
  virtual void copy(const ModPath* source, ModPath* target);
  virtual void copy(const Modport* source, Modport* target);
  virtual void copy(const Module* source, Module* target);
  virtual void copy(const ModuleArray* source, ModuleArray* target);
  virtual void copy(const ModuleTypespec* source, ModuleTypespec* target);
  virtual void copy(const MulticlockSequenceExpr* source, MulticlockSequenceExpr* target);
  virtual void copy(const NamedEvent* source, NamedEvent* target);
  virtual void copy(const NamedEventArray* source, NamedEventArray* target);
  virtual void copy(const Net* source, Net* target);
  virtual void copy(const NullStmt* source, NullStmt* target);
  virtual void copy(const Operation* source, Operation* target);
  virtual void copy(const OrderedWait* source, OrderedWait* target);
  virtual void copy(const Package* source, Package* target);
  virtual void copy(const PackageTypespec* source, PackageTypespec* target);
  virtual void copy(const ParamAssign* source, ParamAssign* target);
  virtual void copy(const Parameter* source, Parameter* target);
  virtual void copy(const PartSelect* source, PartSelect* target);
  virtual void copy(const PathTerm* source, PathTerm* target);
  virtual void copy(const Port* source, Port* target);
  virtual void copy(const PortBit* source, PortBit* target);
  virtual void copy(const Ports* source, Ports* target);
  virtual void copy(const PreprocMacroDefinition* source, PreprocMacroDefinition* target);
  virtual void copy(const PreprocMacroInstance* source, PreprocMacroInstance* target);
  virtual void copy(const PrimTerm* source, PrimTerm* target);
  virtual void copy(const Primitive* source, Primitive* target);
  virtual void copy(const PrimitiveArray* source, PrimitiveArray* target);
  virtual void copy(const Process* source, Process* target);
  virtual void copy(const Program* source, Program* target);
  virtual void copy(const ProgramArray* source, ProgramArray* target);
  virtual void copy(const ProgramTypespec* source, ProgramTypespec* target);
  virtual void copy(const PropFormalDecl* source, PropFormalDecl* target);
  virtual void copy(const PropertyDecl* source, PropertyDecl* target);
  virtual void copy(const PropertyInst* source, PropertyInst* target);
  virtual void copy(const PropertySpec* source, PropertySpec* target);
  virtual void copy(const PropertyTypespec* source, PropertyTypespec* target);
  virtual void copy(const Range* source, Range* target);
  virtual void copy(const RealTypespec* source, RealTypespec* target);
  virtual void copy(const RefInstance* source, RefInstance* target);
  virtual void copy(const RefObj* source, RefObj* target);
  virtual void copy(const RefTypespec* source, RefTypespec* target);
  virtual void copy(const Reg* source, Reg* target);
  virtual void copy(const RegArray* source, RegArray* target);
  virtual void copy(const Release* source, Release* target);
  virtual void copy(const Repeat* source, Repeat* target);
  virtual void copy(const RepeatControl* source, RepeatControl* target);
  virtual void copy(const Restrict* source, Restrict* target);
  virtual void copy(const ReturnStmt* source, ReturnStmt* target);
  virtual void copy(const Scope* source, Scope* target);
  virtual void copy(const Select* source, Select* target);
  virtual void copy(const SeqFormalDecl* source, SeqFormalDecl* target);
  virtual void copy(const SequenceDecl* source, SequenceDecl* target);
  virtual void copy(const SequenceInst* source, SequenceInst* target);
  virtual void copy(const SequenceTypespec* source, SequenceTypespec* target);
  virtual void copy(const ShortIntTypespec* source, ShortIntTypespec* target);
  virtual void copy(const ShortRealTypespec* source, ShortRealTypespec* target);
  virtual void copy(const SimpleExpr* source, SimpleExpr* target);
  virtual void copy(const SoftDisable* source, SoftDisable* target);
  virtual void copy(const SourceFile* source, SourceFile* target);
  virtual void copy(const SpecParam* source, SpecParam* target);
  virtual void copy(const StringTypespec* source, StringTypespec* target);
  virtual void copy(const StructPattern* source, StructPattern* target);
  virtual void copy(const StructTypespec* source, StructTypespec* target);
  virtual void copy(const SwitchArray* source, SwitchArray* target);
  virtual void copy(const SwitchTran* source, SwitchTran* target);
  virtual void copy(const SysFuncCall* source, SysFuncCall* target);
  virtual void copy(const SysTaskCall* source, SysTaskCall* target);
  virtual void copy(const TFCall* source, TFCall* target);
  virtual void copy(const TableEntry* source, TableEntry* target);
  virtual void copy(const TaggedPattern* source, TaggedPattern* target);
  virtual void copy(const Task* source, Task* target);
  virtual void copy(const TaskCall* source, TaskCall* target);
  virtual void copy(const TaskDecl* source, TaskDecl* target);
  virtual void copy(const TaskFunc* source, TaskFunc* target);
  virtual void copy(const TaskFuncDecl* source, TaskFuncDecl* target);
  virtual void copy(const Tchk* source, Tchk* target);
  virtual void copy(const TchkTerm* source, TchkTerm* target);
  virtual void copy(const Thread* source, Thread* target);
  virtual void copy(const TimeTypespec* source, TimeTypespec* target);
  virtual void copy(const TypeParameter* source, TypeParameter* target);
  virtual void copy(const TypedefTypespec* source, TypedefTypespec* target);
  virtual void copy(const Typespec* source, Typespec* target);
  virtual void copy(const TypespecMember* source, TypespecMember* target);
  virtual void copy(const Udp* source, Udp* target);
  virtual void copy(const UdpArray* source, UdpArray* target);
  virtual void copy(const UdpDefn* source, UdpDefn* target);
  virtual void copy(const UdpDefnTypespec* source, UdpDefnTypespec* target);
  virtual void copy(const UnionTypespec* source, UnionTypespec* target);
  virtual void copy(const Uniqueness* source, Uniqueness* target);
  virtual void copy(const UnsupportedExpr* source, UnsupportedExpr* target);
  virtual void copy(const UnsupportedStmt* source, UnsupportedStmt* target);
  virtual void copy(const UnsupportedTypespec* source, UnsupportedTypespec* target);
  virtual void copy(const UserSystf* source, UserSystf* target);
  virtual void copy(const VarSelect* source, VarSelect* target);
  virtual void copy(const Variable* source, Variable* target);
  virtual void copy(const VoidTypespec* source, VoidTypespec* target);
  virtual void copy(const WaitFork* source, WaitFork* target);
  virtual void copy(const WaitStmt* source, WaitStmt* target);
  virtual void copy(const Waits* source, Waits* target);
  virtual void copy(const WhileStmt* source, WhileStmt* target);
  // clang-format on

  // clang-format off
  virtual Any* clone(const Any* source, Any* parent);
  virtual Alias* clone(const Alias* source, Any* parent);
  virtual Always* clone(const Always* source, Any* parent);
  virtual AnyPattern* clone(const AnyPattern* source, Any* parent);
  virtual ArrayExpr* clone(const ArrayExpr* source, Any* parent);
  virtual Assert* clone(const Assert* source, Any* parent);
  virtual AssignStmt* clone(const AssignStmt* source, Any* parent);
  virtual Assignment* clone(const Assignment* source, Any* parent);
  virtual Assume* clone(const Assume* source, Any* parent);
  virtual Attribute* clone(const Attribute* source, Any* parent);
  virtual Begin* clone(const Begin* source, Any* parent);
  virtual BindDirective* clone(const BindDirective* source, Any* parent);
  virtual BitSelect* clone(const BitSelect* source, Any* parent);
  virtual BreakStmt* clone(const BreakStmt* source, Any* parent);
  virtual CaseItem* clone(const CaseItem* source, Any* parent);
  virtual CaseProperty* clone(const CaseProperty* source, Any* parent);
  virtual CasePropertyItem* clone(const CasePropertyItem* source, Any* parent);
  virtual CaseStmt* clone(const CaseStmt* source, Any* parent);
  virtual CheckerDecl* clone(const CheckerDecl* source, Any* parent);
  virtual CheckerInst* clone(const CheckerInst* source, Any* parent);
  virtual CheckerInstPort* clone(const CheckerInstPort* source, Any* parent);
  virtual CheckerPort* clone(const CheckerPort* source, Any* parent);
  virtual ClassDefn* clone(const ClassDefn* source, Any* parent);
  virtual ClassObj* clone(const ClassObj* source, Any* parent);
  virtual Clause* clone(const Clause* source, Any* parent);
  virtual ClockedProperty* clone(const ClockedProperty* source, Any* parent);
  virtual ClockedSeq* clone(const ClockedSeq* source, Any* parent);
  virtual ClockingBlock* clone(const ClockingBlock* source, Any* parent);
  virtual ClockingIODecl* clone(const ClockingIODecl* source, Any* parent);
  virtual Comment* clone(const Comment* source, Any* parent);
  virtual ConfigDecl* clone(const ConfigDecl* source, Any* parent);
  virtual ConfigRule* clone(const ConfigRule* source, Any* parent);
  virtual Constant* clone(const Constant* source, Any* parent);
  virtual ConstrForeach* clone(const ConstrForeach* source, Any* parent);
  virtual ConstrIf* clone(const ConstrIf* source, Any* parent);
  virtual ConstrIfElse* clone(const ConstrIfElse* source, Any* parent);
  virtual Constraint* clone(const Constraint* source, Any* parent);
  virtual ConstraintOrdering* clone(const ConstraintOrdering* source, Any* parent);
  virtual ContAssign* clone(const ContAssign* source, Any* parent);
  virtual ContAssignBit* clone(const ContAssignBit* source, Any* parent);
  virtual ContinueStmt* clone(const ContinueStmt* source, Any* parent);
  virtual Cover* clone(const Cover* source, Any* parent);
  virtual CoverBin* clone(const CoverBin* source, Any* parent);
  virtual CoverCross* clone(const CoverCross* source, Any* parent);
  virtual CoverGroup* clone(const CoverGroup* source, Any* parent);
  virtual CoverPoint* clone(const CoverPoint* source, Any* parent);
  virtual CoverageOption* clone(const CoverageOption* source, Any* parent);
  virtual Deassign* clone(const Deassign* source, Any* parent);
  virtual DefParam* clone(const DefParam* source, Any* parent);
  virtual DelayControl* clone(const DelayControl* source, Any* parent);
  virtual DelayTerm* clone(const DelayTerm* source, Any* parent);
  virtual Design* clone(const Design* source, Any* parent);
  virtual Disable* clone(const Disable* source, Any* parent);
  virtual DisableFork* clone(const DisableFork* source, Any* parent);
  virtual DistItem* clone(const DistItem* source, Any* parent);
  virtual Distribution* clone(const Distribution* source, Any* parent);
  virtual DoWhile* clone(const DoWhile* source, Any* parent);
  virtual EnumConst* clone(const EnumConst* source, Any* parent);
  virtual EventControl* clone(const EventControl* source, Any* parent);
  virtual EventStmt* clone(const EventStmt* source, Any* parent);
  virtual ExpectStmt* clone(const ExpectStmt* source, Any* parent);
  virtual Extends* clone(const Extends* source, Any* parent);
  virtual FinalStmt* clone(const FinalStmt* source, Any* parent);
  virtual ForStmt* clone(const ForStmt* source, Any* parent);
  virtual Force* clone(const Force* source, Any* parent);
  virtual ForeachStmt* clone(const ForeachStmt* source, Any* parent);
  virtual ForeverStmt* clone(const ForeverStmt* source, Any* parent);
  virtual ForkStmt* clone(const ForkStmt* source, Any* parent);
  virtual Function* clone(const Function* source, Any* parent);
  virtual FunctionDecl* clone(const FunctionDecl* source, Any* parent);
  virtual Gate* clone(const Gate* source, Any* parent);
  virtual GateArray* clone(const GateArray* source, Any* parent);
  virtual GenCase* clone(const GenCase* source, Any* parent);
  virtual GenFor* clone(const GenFor* source, Any* parent);
  virtual GenIf* clone(const GenIf* source, Any* parent);
  virtual GenIfElse* clone(const GenIfElse* source, Any* parent);
  virtual GenRegion* clone(const GenRegion* source, Any* parent);
  virtual GenScopeArray* clone(const GenScopeArray* source, Any* parent);
  virtual HierPath* clone(const HierPath* source, Any* parent);
  virtual IODecl* clone(const IODecl* source, Any* parent);
  virtual Identifier* clone(const Identifier* source, Any* parent);
  virtual IfElse* clone(const IfElse* source, Any* parent);
  virtual IfStmt* clone(const IfStmt* source, Any* parent);
  virtual ImmediateAssert* clone(const ImmediateAssert* source, Any* parent);
  virtual ImmediateAssume* clone(const ImmediateAssume* source, Any* parent);
  virtual ImmediateCover* clone(const ImmediateCover* source, Any* parent);
  virtual Implements* clone(const Implements* source, Any* parent);
  virtual Implication* clone(const Implication* source, Any* parent);
  virtual IncludeStmt* clone(const IncludeStmt* source, Any* parent);
  virtual IndexedPartSelect* clone(const IndexedPartSelect* source, Any* parent);
  virtual Initial* clone(const Initial* source, Any* parent);
  virtual Interface* clone(const Interface* source, Any* parent);
  virtual InterfaceArray* clone(const InterfaceArray* source, Any* parent);
  virtual InterfaceTFDecl* clone(const InterfaceTFDecl* source, Any* parent);
  virtual LetDecl* clone(const LetDecl* source, Any* parent);
  virtual LetExpr* clone(const LetExpr* source, Any* parent);
  virtual Library* clone(const Library* source, Any* parent);
  virtual ModPath* clone(const ModPath* source, Any* parent);
  virtual Modport* clone(const Modport* source, Any* parent);
  virtual Module* clone(const Module* source, Any* parent);
  virtual ModuleArray* clone(const ModuleArray* source, Any* parent);
  virtual MulticlockSequenceExpr* clone(const MulticlockSequenceExpr* source, Any* parent);
  virtual NamedEvent* clone(const NamedEvent* source, Any* parent);
  virtual NamedEventArray* clone(const NamedEventArray* source, Any* parent);
  virtual Net* clone(const Net* source, Any* parent);
  virtual NullStmt* clone(const NullStmt* source, Any* parent);
  virtual Operation* clone(const Operation* source, Any* parent);
  virtual OrderedWait* clone(const OrderedWait* source, Any* parent);
  virtual Package* clone(const Package* source, Any* parent);
  virtual ParamAssign* clone(const ParamAssign* source, Any* parent);
  virtual Parameter* clone(const Parameter* source, Any* parent);
  virtual PartSelect* clone(const PartSelect* source, Any* parent);
  virtual PathTerm* clone(const PathTerm* source, Any* parent);
  virtual Port* clone(const Port* source, Any* parent);
  virtual PortBit* clone(const PortBit* source, Any* parent);
  virtual PreprocMacroDefinition* clone(const PreprocMacroDefinition* source, Any* parent);
  virtual PreprocMacroInstance* clone(const PreprocMacroInstance* source, Any* parent);
  virtual PrimTerm* clone(const PrimTerm* source, Any* parent);
  virtual Program* clone(const Program* source, Any* parent);
  virtual ProgramArray* clone(const ProgramArray* source, Any* parent);
  virtual PropFormalDecl* clone(const PropFormalDecl* source, Any* parent);
  virtual PropertyDecl* clone(const PropertyDecl* source, Any* parent);
  virtual PropertyInst* clone(const PropertyInst* source, Any* parent);
  virtual PropertySpec* clone(const PropertySpec* source, Any* parent);
  virtual Range* clone(const Range* source, Any* parent);
  virtual RefInstance* clone(const RefInstance* source, Any* parent);
  virtual RefObj* clone(const RefObj* source, Any* parent);
  virtual RefTypespec* clone(const RefTypespec* source, Any* parent);
  virtual Reg* clone(const Reg* source, Any* parent);
  virtual RegArray* clone(const RegArray* source, Any* parent);
  virtual Release* clone(const Release* source, Any* parent);
  virtual Repeat* clone(const Repeat* source, Any* parent);
  virtual RepeatControl* clone(const RepeatControl* source, Any* parent);
  virtual Restrict* clone(const Restrict* source, Any* parent);
  virtual ReturnStmt* clone(const ReturnStmt* source, Any* parent);
  virtual SeqFormalDecl* clone(const SeqFormalDecl* source, Any* parent);
  virtual SequenceDecl* clone(const SequenceDecl* source, Any* parent);
  virtual SequenceInst* clone(const SequenceInst* source, Any* parent);
  virtual SoftDisable* clone(const SoftDisable* source, Any* parent);
  virtual SourceFile* clone(const SourceFile* source, Any* parent);
  virtual SpecParam* clone(const SpecParam* source, Any* parent);
  virtual StructPattern* clone(const StructPattern* source, Any* parent);
  virtual SwitchArray* clone(const SwitchArray* source, Any* parent);
  virtual SwitchTran* clone(const SwitchTran* source, Any* parent);
  virtual SysFuncCall* clone(const SysFuncCall* source, Any* parent);
  virtual SysTaskCall* clone(const SysTaskCall* source, Any* parent);
  virtual TFCall* clone(const FuncCall* source, Any* parent);
  virtual TFCall* clone(const MethodFuncCall* source, Any* parent);
  virtual TFCall* clone(const MethodTaskCall* source, Any* parent);
  virtual TFCall* clone(const TaskCall* source, Any* parent);
  virtual TableEntry* clone(const TableEntry* source, Any* parent);
  virtual TaggedPattern* clone(const TaggedPattern* source, Any* parent);
  virtual Task* clone(const Task* source, Any* parent);
  virtual TaskDecl* clone(const TaskDecl* source, Any* parent);
  virtual Tchk* clone(const Tchk* source, Any* parent);
  virtual TchkTerm* clone(const TchkTerm* source, Any* parent);
  virtual Thread* clone(const Thread* source, Any* parent);
  virtual Typespec* clone(const ArrayTypespec* source, Any* parent);
  virtual Typespec* clone(const BitTypespec* source, Any* parent);
  virtual Typespec* clone(const ByteTypespec* source, Any* parent);
  virtual Typespec* clone(const ChandleTypespec* source, Any* parent);
  virtual Typespec* clone(const ClassTypespec* source, Any* parent);
  virtual Typespec* clone(const EnumTypespec* source, Any* parent);
  virtual Typespec* clone(const EventTypespec* source, Any* parent);
  virtual Typespec* clone(const ImportTypespec* source, Any* parent);
  virtual Typespec* clone(const IntTypespec* source, Any* parent);
  virtual Typespec* clone(const IntegerTypespec* source, Any* parent);
  virtual Typespec* clone(const InterfaceTypespec* source, Any* parent);
  virtual Typespec* clone(const LogicTypespec* source, Any* parent);
  virtual Typespec* clone(const LongIntTypespec* source, Any* parent);
  virtual Typespec* clone(const ModuleTypespec* source, Any* parent);
  virtual Typespec* clone(const PackageTypespec* source, Any* parent);
  virtual Typespec* clone(const ProgramTypespec* source, Any* parent);
  virtual Typespec* clone(const PropertyTypespec* source, Any* parent);
  virtual Typespec* clone(const RealTypespec* source, Any* parent);
  virtual Typespec* clone(const SequenceTypespec* source, Any* parent);
  virtual Typespec* clone(const ShortIntTypespec* source, Any* parent);
  virtual Typespec* clone(const ShortRealTypespec* source, Any* parent);
  virtual Typespec* clone(const StringTypespec* source, Any* parent);
  virtual Typespec* clone(const StructTypespec* source, Any* parent);
  virtual Typespec* clone(const TimeTypespec* source, Any* parent);
  virtual Typespec* clone(const TypeParameter* source, Any* parent);
  virtual Typespec* clone(const TypedefTypespec* source, Any* parent);
  virtual Typespec* clone(const UdpDefnTypespec* source, Any* parent);
  virtual Typespec* clone(const UnionTypespec* source, Any* parent);
  virtual Typespec* clone(const UnsupportedTypespec* source, Any* parent);
  virtual Typespec* clone(const VoidTypespec* source, Any* parent);
  virtual TypespecMember* clone(const TypespecMember* source, Any* parent);
  virtual Udp* clone(const Udp* source, Any* parent);
  virtual UdpArray* clone(const UdpArray* source, Any* parent);
  virtual UdpDefn* clone(const UdpDefn* source, Any* parent);
  virtual Uniqueness* clone(const Uniqueness* source, Any* parent);
  virtual UnsupportedExpr* clone(const UnsupportedExpr* source, Any* parent);
  virtual UnsupportedStmt* clone(const UnsupportedStmt* source, Any* parent);
  virtual UserSystf* clone(const UserSystf* source, Any* parent);
  virtual VarSelect* clone(const VarSelect* source, Any* parent);
  virtual Variable* clone(const Variable* source, Any* parent);
  virtual WaitFork* clone(const WaitFork* source, Any* parent);
  virtual WaitStmt* clone(const WaitStmt* source, Any* parent);
  virtual WhileStmt* clone(const WhileStmt* source, Any* parent);
  // clang-format on

  // clang-format off
  virtual AnyCollection* clone(const AnyCollection* source, Any* parent);
  virtual AliasCollection* clone(const AliasCollection* source, Any* parent);
  virtual AlwaysCollection* clone(const AlwaysCollection* source, Any* parent);
  virtual AnyPatternCollection* clone(const AnyPatternCollection* source, Any* parent);
  virtual ArrayExprCollection* clone(const ArrayExprCollection* source, Any* parent);
  virtual ArrayTypespecCollection* clone(const ArrayTypespecCollection* source, Any* parent);
  virtual AssertCollection* clone(const AssertCollection* source, Any* parent);
  virtual AssignStmtCollection* clone(const AssignStmtCollection* source, Any* parent);
  virtual AssignmentCollection* clone(const AssignmentCollection* source, Any* parent);
  virtual AssumeCollection* clone(const AssumeCollection* source, Any* parent);
  virtual AtomicStmtCollection* clone(const AtomicStmtCollection* source, Any* parent);
  virtual AttributeCollection* clone(const AttributeCollection* source, Any* parent);
  virtual BeginCollection* clone(const BeginCollection* source, Any* parent);
  virtual BindDirectiveCollection* clone(const BindDirectiveCollection* source, Any* parent);
  virtual BitSelectCollection* clone(const BitSelectCollection* source, Any* parent);
  virtual BitTypespecCollection* clone(const BitTypespecCollection* source, Any* parent);
  virtual BreakStmtCollection* clone(const BreakStmtCollection* source, Any* parent);
  virtual ByteTypespecCollection* clone(const ByteTypespecCollection* source, Any* parent);
  virtual CaseItemCollection* clone(const CaseItemCollection* source, Any* parent);
  virtual CasePropertyCollection* clone(const CasePropertyCollection* source, Any* parent);
  virtual CasePropertyItemCollection* clone(const CasePropertyItemCollection* source, Any* parent);
  virtual CaseStmtCollection* clone(const CaseStmtCollection* source, Any* parent);
  virtual ChandleTypespecCollection* clone(const ChandleTypespecCollection* source, Any* parent);
  virtual CheckerDeclCollection* clone(const CheckerDeclCollection* source, Any* parent);
  virtual CheckerInstCollection* clone(const CheckerInstCollection* source, Any* parent);
  virtual CheckerInstPortCollection* clone(const CheckerInstPortCollection* source, Any* parent);
  virtual CheckerPortCollection* clone(const CheckerPortCollection* source, Any* parent);
  virtual ClassDefnCollection* clone(const ClassDefnCollection* source, Any* parent);
  virtual ClassObjCollection* clone(const ClassObjCollection* source, Any* parent);
  virtual ClassTypespecCollection* clone(const ClassTypespecCollection* source, Any* parent);
  virtual ClauseCollection* clone(const ClauseCollection* source, Any* parent);
  virtual ClockedPropertyCollection* clone(const ClockedPropertyCollection* source, Any* parent);
  virtual ClockedSeqCollection* clone(const ClockedSeqCollection* source, Any* parent);
  virtual ClockingBlockCollection* clone(const ClockingBlockCollection* source, Any* parent);
  virtual ClockingIODeclCollection* clone(const ClockingIODeclCollection* source, Any* parent);
  virtual CommentCollection* clone(const CommentCollection* source, Any* parent);
  virtual ConcurrentAssertionsCollection* clone(const ConcurrentAssertionsCollection* source, Any* parent);
  virtual ConfigDeclCollection* clone(const ConfigDeclCollection* source, Any* parent);
  virtual ConfigRuleCollection* clone(const ConfigRuleCollection* source, Any* parent);
  virtual ConstantCollection* clone(const ConstantCollection* source, Any* parent);
  virtual ConstrForeachCollection* clone(const ConstrForeachCollection* source, Any* parent);
  virtual ConstrIfCollection* clone(const ConstrIfCollection* source, Any* parent);
  virtual ConstrIfElseCollection* clone(const ConstrIfElseCollection* source, Any* parent);
  virtual ConstraintCollection* clone(const ConstraintCollection* source, Any* parent);
  virtual ConstraintExprCollection* clone(const ConstraintExprCollection* source, Any* parent);
  virtual ConstraintOrderingCollection* clone(const ConstraintOrderingCollection* source, Any* parent);
  virtual ContAssignBitCollection* clone(const ContAssignBitCollection* source, Any* parent);
  virtual ContAssignCollection* clone(const ContAssignCollection* source, Any* parent);
  virtual ContinueStmtCollection* clone(const ContinueStmtCollection* source, Any* parent);
  virtual CoverBinCollection* clone(const CoverBinCollection* source, Any* parent);
  virtual CoverCollection* clone(const CoverCollection* source, Any* parent);
  virtual CoverCrossCollection* clone(const CoverCrossCollection* source, Any* parent);
  virtual CoverGroupCollection* clone(const CoverGroupCollection* source, Any* parent);
  virtual CoverPointCollection* clone(const CoverPointCollection* source, Any* parent);
  virtual CoverageOptionCollection* clone(const CoverageOptionCollection* source, Any* parent);
  virtual DeassignCollection* clone(const DeassignCollection* source, Any* parent);
  virtual DefParamCollection* clone(const DefParamCollection* source, Any* parent);
  virtual DelayControlCollection* clone(const DelayControlCollection* source, Any* parent);
  virtual DelayTermCollection* clone(const DelayTermCollection* source, Any* parent);
  virtual DesignCollection* clone(const DesignCollection* source, Any* parent);
  virtual DisableCollection* clone(const DisableCollection* source, Any* parent);
  virtual DisableForkCollection* clone(const DisableForkCollection* source, Any* parent);
  virtual DisablesCollection* clone(const DisablesCollection* source, Any* parent);
  virtual DistItemCollection* clone(const DistItemCollection* source, Any* parent);
  virtual DistributionCollection* clone(const DistributionCollection* source, Any* parent);
  virtual DoWhileCollection* clone(const DoWhileCollection* source, Any* parent);
  virtual EnumConstCollection* clone(const EnumConstCollection* source, Any* parent);
  virtual EnumTypespecCollection* clone(const EnumTypespecCollection* source, Any* parent);
  virtual EventControlCollection* clone(const EventControlCollection* source, Any* parent);
  virtual EventStmtCollection* clone(const EventStmtCollection* source, Any* parent);
  virtual EventTypespecCollection* clone(const EventTypespecCollection* source, Any* parent);
  virtual ExpectStmtCollection* clone(const ExpectStmtCollection* source, Any* parent);
  virtual ExprCollection* clone(const ExprCollection* source, Any* parent);
  virtual ExtendsCollection* clone(const ExtendsCollection* source, Any* parent);
  virtual FinalStmtCollection* clone(const FinalStmtCollection* source, Any* parent);
  virtual ForStmtCollection* clone(const ForStmtCollection* source, Any* parent);
  virtual ForceCollection* clone(const ForceCollection* source, Any* parent);
  virtual ForeachStmtCollection* clone(const ForeachStmtCollection* source, Any* parent);
  virtual ForeverStmtCollection* clone(const ForeverStmtCollection* source, Any* parent);
  virtual ForkStmtCollection* clone(const ForkStmtCollection* source, Any* parent);
  virtual FuncCallCollection* clone(const FuncCallCollection* source, Any* parent);
  virtual FunctionCollection* clone(const FunctionCollection* source, Any* parent);
  virtual FunctionDeclCollection* clone(const FunctionDeclCollection* source, Any* parent);
  virtual GateArrayCollection* clone(const GateArrayCollection* source, Any* parent);
  virtual GateCollection* clone(const GateCollection* source, Any* parent);
  virtual GenCaseCollection* clone(const GenCaseCollection* source, Any* parent);
  virtual GenForCollection* clone(const GenForCollection* source, Any* parent);
  virtual GenIfCollection* clone(const GenIfCollection* source, Any* parent);
  virtual GenIfElseCollection* clone(const GenIfElseCollection* source, Any* parent);
  virtual GenRegionCollection* clone(const GenRegionCollection* source, Any* parent);
  virtual GenScopeArrayCollection* clone(const GenScopeArrayCollection* source, Any* parent);
  virtual GenScopeCollection* clone(const GenScopeCollection* source, Any* parent);
  virtual GenStmtCollection* clone(const GenStmtCollection* source, Any* parent);
  virtual HierPathCollection* clone(const HierPathCollection* source, Any* parent);
  virtual IODeclCollection* clone(const IODeclCollection* source, Any* parent);
  virtual IdentifierCollection* clone(const IdentifierCollection* source, Any* parent);
  virtual IfElseCollection* clone(const IfElseCollection* source, Any* parent);
  virtual IfStmtCollection* clone(const IfStmtCollection* source, Any* parent);
  virtual ImmediateAssertCollection* clone(const ImmediateAssertCollection* source, Any* parent);
  virtual ImmediateAssumeCollection* clone(const ImmediateAssumeCollection* source, Any* parent);
  virtual ImmediateCoverCollection* clone(const ImmediateCoverCollection* source, Any* parent);
  virtual ImplementsCollection* clone(const ImplementsCollection* source, Any* parent);
  virtual ImplicationCollection* clone(const ImplicationCollection* source, Any* parent);
  virtual ImportTypespecCollection* clone(const ImportTypespecCollection* source, Any* parent);
  virtual IncludeStmtCollection* clone(const IncludeStmtCollection* source, Any* parent);
  virtual IndexedPartSelectCollection* clone(const IndexedPartSelectCollection* source, Any* parent);
  virtual InitialCollection* clone(const InitialCollection* source, Any* parent);
  virtual InstanceArrayCollection* clone(const InstanceArrayCollection* source, Any* parent);
  virtual InstanceCollection* clone(const InstanceCollection* source, Any* parent);
  virtual IntTypespecCollection* clone(const IntTypespecCollection* source, Any* parent);
  virtual IntegerTypespecCollection* clone(const IntegerTypespecCollection* source, Any* parent);
  virtual InterfaceArrayCollection* clone(const InterfaceArrayCollection* source, Any* parent);
  virtual InterfaceCollection* clone(const InterfaceCollection* source, Any* parent);
  virtual InterfaceTFDeclCollection* clone(const InterfaceTFDeclCollection* source, Any* parent);
  virtual InterfaceTypespecCollection* clone(const InterfaceTypespecCollection* source, Any* parent);
  virtual LetDeclCollection* clone(const LetDeclCollection* source, Any* parent);
  virtual LetExprCollection* clone(const LetExprCollection* source, Any* parent);
  virtual LibraryCollection* clone(const LibraryCollection* source, Any* parent);
  virtual LogicTypespecCollection* clone(const LogicTypespecCollection* source, Any* parent);
  virtual LongIntTypespecCollection* clone(const LongIntTypespecCollection* source, Any* parent);
  virtual MethodFuncCallCollection* clone(const MethodFuncCallCollection* source, Any* parent);
  virtual MethodTaskCallCollection* clone(const MethodTaskCallCollection* source, Any* parent);
  virtual ModPathCollection* clone(const ModPathCollection* source, Any* parent);
  virtual ModportCollection* clone(const ModportCollection* source, Any* parent);
  virtual ModuleArrayCollection* clone(const ModuleArrayCollection* source, Any* parent);
  virtual ModuleCollection* clone(const ModuleCollection* source, Any* parent);
  virtual ModuleTypespecCollection* clone(const ModuleTypespecCollection* source, Any* parent);
  virtual MulticlockSequenceExprCollection* clone(const MulticlockSequenceExprCollection* source, Any* parent);
  virtual NamedEventArrayCollection* clone(const NamedEventArrayCollection* source, Any* parent);
  virtual NamedEventCollection* clone(const NamedEventCollection* source, Any* parent);
  virtual NetCollection* clone(const NetCollection* source, Any* parent);
  virtual NullStmtCollection* clone(const NullStmtCollection* source, Any* parent);
  virtual OperationCollection* clone(const OperationCollection* source, Any* parent);
  virtual OrderedWaitCollection* clone(const OrderedWaitCollection* source, Any* parent);
  virtual PackageCollection* clone(const PackageCollection* source, Any* parent);
  virtual PackageTypespecCollection* clone(const PackageTypespecCollection* source, Any* parent);
  virtual ParamAssignCollection* clone(const ParamAssignCollection* source, Any* parent);
  virtual ParameterCollection* clone(const ParameterCollection* source, Any* parent);
  virtual PartSelectCollection* clone(const PartSelectCollection* source, Any* parent);
  virtual PathTermCollection* clone(const PathTermCollection* source, Any* parent);
  virtual PortBitCollection* clone(const PortBitCollection* source, Any* parent);
  virtual PortCollection* clone(const PortCollection* source, Any* parent);
  virtual PortsCollection* clone(const PortsCollection* source, Any* parent);
  virtual PreprocMacroDefinitionCollection* clone(const PreprocMacroDefinitionCollection* source, Any* parent);
  virtual PreprocMacroInstanceCollection* clone(const PreprocMacroInstanceCollection* source, Any* parent);
  virtual PrimTermCollection* clone(const PrimTermCollection* source, Any* parent);
  virtual PrimitiveArrayCollection* clone(const PrimitiveArrayCollection* source, Any* parent);
  virtual PrimitiveCollection* clone(const PrimitiveCollection* source, Any* parent);
  virtual ProcessCollection* clone(const ProcessCollection* source, Any* parent);
  virtual ProgramArrayCollection* clone(const ProgramArrayCollection* source, Any* parent);
  virtual ProgramCollection* clone(const ProgramCollection* source, Any* parent);
  virtual ProgramTypespecCollection* clone(const ProgramTypespecCollection* source, Any* parent);
  virtual PropFormalDeclCollection* clone(const PropFormalDeclCollection* source, Any* parent);
  virtual PropertyDeclCollection* clone(const PropertyDeclCollection* source, Any* parent);
  virtual PropertyInstCollection* clone(const PropertyInstCollection* source, Any* parent);
  virtual PropertySpecCollection* clone(const PropertySpecCollection* source, Any* parent);
  virtual PropertyTypespecCollection* clone(const PropertyTypespecCollection* source, Any* parent);
  virtual RangeCollection* clone(const RangeCollection* source, Any* parent);
  virtual RealTypespecCollection* clone(const RealTypespecCollection* source, Any* parent);
  virtual RefInstanceCollection* clone(const RefInstanceCollection* source, Any* parent);
  virtual RefObjCollection* clone(const RefObjCollection* source, Any* parent);
  virtual RefTypespecCollection* clone(const RefTypespecCollection* source, Any* parent);
  virtual RegArrayCollection* clone(const RegArrayCollection* source, Any* parent);
  virtual RegCollection* clone(const RegCollection* source, Any* parent);
  virtual ReleaseCollection* clone(const ReleaseCollection* source, Any* parent);
  virtual RepeatCollection* clone(const RepeatCollection* source, Any* parent);
  virtual RepeatControlCollection* clone(const RepeatControlCollection* source, Any* parent);
  virtual RestrictCollection* clone(const RestrictCollection* source, Any* parent);
  virtual ReturnStmtCollection* clone(const ReturnStmtCollection* source, Any* parent);
  virtual ScopeCollection* clone(const ScopeCollection* source, Any* parent);
  virtual SelectCollection* clone(const SelectCollection* source, Any* parent);
  virtual SeqFormalDeclCollection* clone(const SeqFormalDeclCollection* source, Any* parent);
  virtual SequenceDeclCollection* clone(const SequenceDeclCollection* source, Any* parent);
  virtual SequenceInstCollection* clone(const SequenceInstCollection* source, Any* parent);
  virtual SequenceTypespecCollection* clone(const SequenceTypespecCollection* source, Any* parent);
  virtual ShortIntTypespecCollection* clone(const ShortIntTypespecCollection* source, Any* parent);
  virtual ShortRealTypespecCollection* clone(const ShortRealTypespecCollection* source, Any* parent);
  virtual SimpleExprCollection* clone(const SimpleExprCollection* source, Any* parent);
  virtual SoftDisableCollection* clone(const SoftDisableCollection* source, Any* parent);
  virtual SourceFileCollection* clone(const SourceFileCollection* source, Any* parent);
  virtual SpecParamCollection* clone(const SpecParamCollection* source, Any* parent);
  virtual StringTypespecCollection* clone(const StringTypespecCollection* source, Any* parent);
  virtual StructPatternCollection* clone(const StructPatternCollection* source, Any* parent);
  virtual StructTypespecCollection* clone(const StructTypespecCollection* source, Any* parent);
  virtual SwitchArrayCollection* clone(const SwitchArrayCollection* source, Any* parent);
  virtual SwitchTranCollection* clone(const SwitchTranCollection* source, Any* parent);
  virtual SysFuncCallCollection* clone(const SysFuncCallCollection* source, Any* parent);
  virtual SysTaskCallCollection* clone(const SysTaskCallCollection* source, Any* parent);
  virtual TFCallCollection* clone(const TFCallCollection* source, Any* parent);
  virtual TableEntryCollection* clone(const TableEntryCollection* source, Any* parent);
  virtual TaggedPatternCollection* clone(const TaggedPatternCollection* source, Any* parent);
  virtual TaskCallCollection* clone(const TaskCallCollection* source, Any* parent);
  virtual TaskCollection* clone(const TaskCollection* source, Any* parent);
  virtual TaskDeclCollection* clone(const TaskDeclCollection* source, Any* parent);
  virtual TaskFuncCollection* clone(const TaskFuncCollection* source, Any* parent);
  virtual TaskFuncDeclCollection* clone(const TaskFuncDeclCollection* source, Any* parent);
  virtual TchkCollection* clone(const TchkCollection* source, Any* parent);
  virtual TchkTermCollection* clone(const TchkTermCollection* source, Any* parent);
  virtual ThreadCollection* clone(const ThreadCollection* source, Any* parent);
  virtual TimeTypespecCollection* clone(const TimeTypespecCollection* source, Any* parent);
  virtual TypeParameterCollection* clone(const TypeParameterCollection* source, Any* parent);
  virtual TypedefTypespecCollection* clone(const TypedefTypespecCollection* source, Any* parent);
  virtual TypespecCollection* clone(const TypespecCollection* source, Any* parent);
  virtual TypespecMemberCollection* clone(const TypespecMemberCollection* source, Any* parent);
  virtual UdpArrayCollection* clone(const UdpArrayCollection* source, Any* parent);
  virtual UdpCollection* clone(const UdpCollection* source, Any* parent);
  virtual UdpDefnCollection* clone(const UdpDefnCollection* source, Any* parent);
  virtual UdpDefnTypespecCollection* clone(const UdpDefnTypespecCollection* source, Any* parent);
  virtual UnionTypespecCollection* clone(const UnionTypespecCollection* source, Any* parent);
  virtual UniquenessCollection* clone(const UniquenessCollection* source, Any* parent);
  virtual UnsupportedExprCollection* clone(const UnsupportedExprCollection* source, Any* parent);
  virtual UnsupportedStmtCollection* clone(const UnsupportedStmtCollection* source, Any* parent);
  virtual UnsupportedTypespecCollection* clone(const UnsupportedTypespecCollection* source, Any* parent);
  virtual UserSystfCollection* clone(const UserSystfCollection* source, Any* parent);
  virtual VarSelectCollection* clone(const VarSelectCollection* source, Any* parent);
  virtual VariableCollection* clone(const VariableCollection* source, Any* parent);
  virtual VoidTypespecCollection* clone(const VoidTypespecCollection* source, Any* parent);
  virtual WaitForkCollection* clone(const WaitForkCollection* source, Any* parent);
  virtual WaitStmtCollection* clone(const WaitStmtCollection* source, Any* parent);
  virtual WaitsCollection* clone(const WaitsCollection* source, Any* parent);
  virtual WhileStmtCollection* clone(const WhileStmtCollection* source, Any* parent);
  // clang-format on

 protected:
  Serializer *const m_serializer = nullptr;
  callstack_t m_callstack;
};

template <typename T>
inline std::vector<T *> *Cloner::cloneT(const std::vector<T *> *source) {
  if ((source == nullptr) || source->empty()) return nullptr;
  std::vector<T *> *const target = m_serializer->template makeCollection<T>();
  target->insert(target->cend(), source->cbegin(), source->cend());
  return target;
}

template <typename T>
inline std::vector<T *> *Cloner::cloneT(const std::vector<T *> *source,
                                        Any *parent) {
  if ((source == nullptr) || source->empty()) return nullptr;
  std::vector<T *> *const target = m_serializer->template makeCollection<T>();
  target->reserve(source->size());
  const std::vector<T *> collection(*source);
  for (T *obj : collection) {
    target->emplace_back(
        static_cast<T *>(cloneAny(static_cast<const Any *>(obj), parent)));
  }
  return target;
}

class PassThroughCloner : public Cloner {
  UHDM_IMPLEMENT_RTTI(PassThroughCloner, Cloner)

 public:
  explicit PassThroughCloner(Serializer *serializer) : Cloner(serializer) {}
  ~PassThroughCloner() override = default;
  PassThroughCloner(const PassThroughCloner &rhs) = delete;
  PassThroughCloner &operator=(const PassThroughCloner &rhs) = delete;

  using Cloner::clone;

 protected:
  Any *cloneAny(const Any *source, Any *parent) override;

  // clang-format off
  AnyCollection* clone(const AnyCollection* source, Any* parent) override { return const_cast<AnyCollection *>(source); }
  AliasCollection* clone(const AliasCollection* source, Any* parent) override;
  AlwaysCollection* clone(const AlwaysCollection* source, Any* parent) override;
  AnyPatternCollection* clone(const AnyPatternCollection* source, Any* parent) override;
  ArrayExprCollection* clone(const ArrayExprCollection* source, Any* parent) override;
  ArrayTypespecCollection* clone(const ArrayTypespecCollection* source, Any* parent) override;
  AssertCollection* clone(const AssertCollection* source, Any* parent) override;
  AssignStmtCollection* clone(const AssignStmtCollection* source, Any* parent) override;
  AssignmentCollection* clone(const AssignmentCollection* source, Any* parent) override;
  AssumeCollection* clone(const AssumeCollection* source, Any* parent) override;
  AtomicStmtCollection* clone(const AtomicStmtCollection* source, Any* parent) override;
  AttributeCollection* clone(const AttributeCollection* source, Any* parent) override;
  BeginCollection* clone(const BeginCollection* source, Any* parent) override;
  BindDirectiveCollection* clone(const BindDirectiveCollection* source, Any* parent) override;
  BitSelectCollection* clone(const BitSelectCollection* source, Any* parent) override;
  BitTypespecCollection* clone(const BitTypespecCollection* source, Any* parent) override;
  BreakStmtCollection* clone(const BreakStmtCollection* source, Any* parent) override;
  ByteTypespecCollection* clone(const ByteTypespecCollection* source, Any* parent) override;
  CaseItemCollection* clone(const CaseItemCollection* source, Any* parent) override;
  CasePropertyCollection* clone(const CasePropertyCollection* source, Any* parent) override;
  CasePropertyItemCollection* clone(const CasePropertyItemCollection* source, Any* parent) override;
  CaseStmtCollection* clone(const CaseStmtCollection* source, Any* parent) override;
  ChandleTypespecCollection* clone(const ChandleTypespecCollection* source, Any* parent) override;
  CheckerDeclCollection* clone(const CheckerDeclCollection* source, Any* parent) override;
  CheckerInstCollection* clone(const CheckerInstCollection* source, Any* parent) override;
  CheckerInstPortCollection* clone(const CheckerInstPortCollection* source, Any* parent) override;
  CheckerPortCollection* clone(const CheckerPortCollection* source, Any* parent) override;
  ClassDefnCollection* clone(const ClassDefnCollection* source, Any* parent) override;
  ClassObjCollection* clone(const ClassObjCollection* source, Any* parent) override;
  ClassTypespecCollection* clone(const ClassTypespecCollection* source, Any* parent) override;
  ClauseCollection* clone(const ClauseCollection* source, Any* parent) override;
  ClockedPropertyCollection* clone(const ClockedPropertyCollection* source, Any* parent) override;
  ClockedSeqCollection* clone(const ClockedSeqCollection* source, Any* parent) override;
  ClockingBlockCollection* clone(const ClockingBlockCollection* source, Any* parent) override;
  ClockingIODeclCollection* clone(const ClockingIODeclCollection* source, Any* parent) override;
  CommentCollection* clone(const CommentCollection* source, Any* parent) override;
  ConcurrentAssertionsCollection* clone(const ConcurrentAssertionsCollection* source, Any* parent) override;
  ConfigDeclCollection* clone(const ConfigDeclCollection* source, Any* parent) override;
  ConfigRuleCollection* clone(const ConfigRuleCollection* source, Any* parent) override;
  ConstantCollection* clone(const ConstantCollection* source, Any* parent) override;
  ConstrForeachCollection* clone(const ConstrForeachCollection* source, Any* parent) override;
  ConstrIfCollection* clone(const ConstrIfCollection* source, Any* parent) override;
  ConstrIfElseCollection* clone(const ConstrIfElseCollection* source, Any* parent) override;
  ConstraintCollection* clone(const ConstraintCollection* source, Any* parent) override;
  ConstraintExprCollection* clone(const ConstraintExprCollection* source, Any* parent) override;
  ConstraintOrderingCollection* clone(const ConstraintOrderingCollection* source, Any* parent) override;
  ContAssignBitCollection* clone(const ContAssignBitCollection* source, Any* parent) override;
  ContAssignCollection* clone(const ContAssignCollection* source, Any* parent) override;
  ContinueStmtCollection* clone(const ContinueStmtCollection* source, Any* parent) override;
  CoverBinCollection* clone(const CoverBinCollection* source, Any* parent) override;
  CoverCollection* clone(const CoverCollection* source, Any* parent) override;
  CoverCrossCollection* clone(const CoverCrossCollection* source, Any* parent) override;
  CoverGroupCollection* clone(const CoverGroupCollection* source, Any* parent) override;
  CoverPointCollection* clone(const CoverPointCollection* source, Any* parent) override;
  CoverageOptionCollection* clone(const CoverageOptionCollection* source, Any* parent) override;
  DeassignCollection* clone(const DeassignCollection* source, Any* parent) override;
  DefParamCollection* clone(const DefParamCollection* source, Any* parent) override;
  DelayControlCollection* clone(const DelayControlCollection* source, Any* parent) override;
  DelayTermCollection* clone(const DelayTermCollection* source, Any* parent) override;
  DesignCollection* clone(const DesignCollection* source, Any* parent) override;
  DisableCollection* clone(const DisableCollection* source, Any* parent) override;
  DisableForkCollection* clone(const DisableForkCollection* source, Any* parent) override;
  DisablesCollection* clone(const DisablesCollection* source, Any* parent) override;
  DistItemCollection* clone(const DistItemCollection* source, Any* parent) override;
  DistributionCollection* clone(const DistributionCollection* source, Any* parent) override;
  DoWhileCollection* clone(const DoWhileCollection* source, Any* parent) override;
  EnumConstCollection* clone(const EnumConstCollection* source, Any* parent) override;
  EnumTypespecCollection* clone(const EnumTypespecCollection* source, Any* parent) override;
  EventControlCollection* clone(const EventControlCollection* source, Any* parent) override;
  EventStmtCollection* clone(const EventStmtCollection* source, Any* parent) override;
  EventTypespecCollection* clone(const EventTypespecCollection* source, Any* parent) override;
  ExpectStmtCollection* clone(const ExpectStmtCollection* source, Any* parent) override;
  ExprCollection* clone(const ExprCollection* source, Any* parent) override;
  ExtendsCollection* clone(const ExtendsCollection* source, Any* parent) override;
  FinalStmtCollection* clone(const FinalStmtCollection* source, Any* parent) override;
  ForStmtCollection* clone(const ForStmtCollection* source, Any* parent) override;
  ForceCollection* clone(const ForceCollection* source, Any* parent) override;
  ForeachStmtCollection* clone(const ForeachStmtCollection* source, Any* parent) override;
  ForeverStmtCollection* clone(const ForeverStmtCollection* source, Any* parent) override;
  ForkStmtCollection* clone(const ForkStmtCollection* source, Any* parent) override;
  FuncCallCollection* clone(const FuncCallCollection* source, Any* parent) override;
  FunctionCollection* clone(const FunctionCollection* source, Any* parent) override;
  FunctionDeclCollection* clone(const FunctionDeclCollection* source, Any* parent) override;
  GateArrayCollection* clone(const GateArrayCollection* source, Any* parent) override;
  GateCollection* clone(const GateCollection* source, Any* parent) override;
  GenCaseCollection* clone(const GenCaseCollection* source, Any* parent) override;
  GenForCollection* clone(const GenForCollection* source, Any* parent) override;
  GenIfCollection* clone(const GenIfCollection* source, Any* parent) override;
  GenIfElseCollection* clone(const GenIfElseCollection* source, Any* parent) override;
  GenRegionCollection* clone(const GenRegionCollection* source, Any* parent) override;
  GenScopeArrayCollection* clone(const GenScopeArrayCollection* source, Any* parent) override;
  GenScopeCollection* clone(const GenScopeCollection* source, Any* parent) override;
  GenStmtCollection* clone(const GenStmtCollection* source, Any* parent) override;
  HierPathCollection* clone(const HierPathCollection* source, Any* parent) override;
  IODeclCollection* clone(const IODeclCollection* source, Any* parent) override;
  IdentifierCollection* clone(const IdentifierCollection* source, Any* parent) override;
  IfElseCollection* clone(const IfElseCollection* source, Any* parent) override;
  IfStmtCollection* clone(const IfStmtCollection* source, Any* parent) override;
  ImmediateAssertCollection* clone(const ImmediateAssertCollection* source, Any* parent) override;
  ImmediateAssumeCollection* clone(const ImmediateAssumeCollection* source, Any* parent) override;
  ImmediateCoverCollection* clone(const ImmediateCoverCollection* source, Any* parent) override;
  ImplementsCollection* clone(const ImplementsCollection* source, Any* parent) override;
  ImplicationCollection* clone(const ImplicationCollection* source, Any* parent) override;
  ImportTypespecCollection* clone(const ImportTypespecCollection* source, Any* parent) override;
  IncludeStmtCollection* clone(const IncludeStmtCollection* source, Any* parent) override;
  IndexedPartSelectCollection* clone(const IndexedPartSelectCollection* source, Any* parent) override;
  InitialCollection* clone(const InitialCollection* source, Any* parent) override;
  InstanceArrayCollection* clone(const InstanceArrayCollection* source, Any* parent) override;
  InstanceCollection* clone(const InstanceCollection* source, Any* parent) override;
  IntTypespecCollection* clone(const IntTypespecCollection* source, Any* parent) override;
  IntegerTypespecCollection* clone(const IntegerTypespecCollection* source, Any* parent) override;
  InterfaceArrayCollection* clone(const InterfaceArrayCollection* source, Any* parent) override;
  InterfaceCollection* clone(const InterfaceCollection* source, Any* parent) override;
  InterfaceTFDeclCollection* clone(const InterfaceTFDeclCollection* source, Any* parent) override;
  InterfaceTypespecCollection* clone(const InterfaceTypespecCollection* source, Any* parent) override;
  LetDeclCollection* clone(const LetDeclCollection* source, Any* parent) override;
  LetExprCollection* clone(const LetExprCollection* source, Any* parent) override;
  LibraryCollection* clone(const LibraryCollection* source, Any* parent) override;
  LogicTypespecCollection* clone(const LogicTypespecCollection* source, Any* parent) override;
  LongIntTypespecCollection* clone(const LongIntTypespecCollection* source, Any* parent) override;
  MethodFuncCallCollection* clone(const MethodFuncCallCollection* source, Any* parent) override;
  MethodTaskCallCollection* clone(const MethodTaskCallCollection* source, Any* parent) override;
  ModPathCollection* clone(const ModPathCollection* source, Any* parent) override;
  ModportCollection* clone(const ModportCollection* source, Any* parent) override;
  ModuleArrayCollection* clone(const ModuleArrayCollection* source, Any* parent) override;
  ModuleCollection* clone(const ModuleCollection* source, Any* parent) override;
  ModuleTypespecCollection* clone(const ModuleTypespecCollection* source, Any* parent) override;
  MulticlockSequenceExprCollection* clone(const MulticlockSequenceExprCollection* source, Any* parent) override;
  NamedEventArrayCollection* clone(const NamedEventArrayCollection* source, Any* parent) override;
  NamedEventCollection* clone(const NamedEventCollection* source, Any* parent) override;
  NetCollection* clone(const NetCollection* source, Any* parent) override;
  NullStmtCollection* clone(const NullStmtCollection* source, Any* parent) override;
  OperationCollection* clone(const OperationCollection* source, Any* parent) override;
  OrderedWaitCollection* clone(const OrderedWaitCollection* source, Any* parent) override;
  PackageCollection* clone(const PackageCollection* source, Any* parent) override;
  PackageTypespecCollection* clone(const PackageTypespecCollection* source, Any* parent) override;
  ParamAssignCollection* clone(const ParamAssignCollection* source, Any* parent) override;
  ParameterCollection* clone(const ParameterCollection* source, Any* parent) override;
  PartSelectCollection* clone(const PartSelectCollection* source, Any* parent) override;
  PathTermCollection* clone(const PathTermCollection* source, Any* parent) override;
  PortBitCollection* clone(const PortBitCollection* source, Any* parent) override;
  PortCollection* clone(const PortCollection* source, Any* parent) override;
  PortsCollection* clone(const PortsCollection* source, Any* parent) override;
  PreprocMacroDefinitionCollection* clone(const PreprocMacroDefinitionCollection* source, Any* parent) override;
  PreprocMacroInstanceCollection* clone(const PreprocMacroInstanceCollection* source, Any* parent) override;
  PrimTermCollection* clone(const PrimTermCollection* source, Any* parent) override;
  PrimitiveArrayCollection* clone(const PrimitiveArrayCollection* source, Any* parent) override;
  PrimitiveCollection* clone(const PrimitiveCollection* source, Any* parent) override;
  ProcessCollection* clone(const ProcessCollection* source, Any* parent) override;
  ProgramArrayCollection* clone(const ProgramArrayCollection* source, Any* parent) override;
  ProgramCollection* clone(const ProgramCollection* source, Any* parent) override;
  ProgramTypespecCollection* clone(const ProgramTypespecCollection* source, Any* parent) override;
  PropFormalDeclCollection* clone(const PropFormalDeclCollection* source, Any* parent) override;
  PropertyDeclCollection* clone(const PropertyDeclCollection* source, Any* parent) override;
  PropertyInstCollection* clone(const PropertyInstCollection* source, Any* parent) override;
  PropertySpecCollection* clone(const PropertySpecCollection* source, Any* parent) override;
  PropertyTypespecCollection* clone(const PropertyTypespecCollection* source, Any* parent) override;
  RangeCollection* clone(const RangeCollection* source, Any* parent) override;
  RealTypespecCollection* clone(const RealTypespecCollection* source, Any* parent) override;
  RefInstanceCollection* clone(const RefInstanceCollection* source, Any* parent) override;
  RefObjCollection* clone(const RefObjCollection* source, Any* parent) override;
  RefTypespecCollection* clone(const RefTypespecCollection* source, Any* parent) override;
  RegArrayCollection* clone(const RegArrayCollection* source, Any* parent) override;
  RegCollection* clone(const RegCollection* source, Any* parent) override;
  ReleaseCollection* clone(const ReleaseCollection* source, Any* parent) override;
  RepeatCollection* clone(const RepeatCollection* source, Any* parent) override;
  RepeatControlCollection* clone(const RepeatControlCollection* source, Any* parent) override;
  RestrictCollection* clone(const RestrictCollection* source, Any* parent) override;
  ReturnStmtCollection* clone(const ReturnStmtCollection* source, Any* parent) override;
  ScopeCollection* clone(const ScopeCollection* source, Any* parent) override;
  SelectCollection* clone(const SelectCollection* source, Any* parent) override;
  SeqFormalDeclCollection* clone(const SeqFormalDeclCollection* source, Any* parent) override;
  SequenceDeclCollection* clone(const SequenceDeclCollection* source, Any* parent) override;
  SequenceInstCollection* clone(const SequenceInstCollection* source, Any* parent) override;
  SequenceTypespecCollection* clone(const SequenceTypespecCollection* source, Any* parent) override;
  ShortIntTypespecCollection* clone(const ShortIntTypespecCollection* source, Any* parent) override;
  ShortRealTypespecCollection* clone(const ShortRealTypespecCollection* source, Any* parent) override;
  SimpleExprCollection* clone(const SimpleExprCollection* source, Any* parent) override;
  SoftDisableCollection* clone(const SoftDisableCollection* source, Any* parent) override;
  SourceFileCollection* clone(const SourceFileCollection* source, Any* parent) override;
  SpecParamCollection* clone(const SpecParamCollection* source, Any* parent) override;
  StringTypespecCollection* clone(const StringTypespecCollection* source, Any* parent) override;
  StructPatternCollection* clone(const StructPatternCollection* source, Any* parent) override;
  StructTypespecCollection* clone(const StructTypespecCollection* source, Any* parent) override;
  SwitchArrayCollection* clone(const SwitchArrayCollection* source, Any* parent) override;
  SwitchTranCollection* clone(const SwitchTranCollection* source, Any* parent) override;
  SysFuncCallCollection* clone(const SysFuncCallCollection* source, Any* parent) override;
  SysTaskCallCollection* clone(const SysTaskCallCollection* source, Any* parent) override;
  TFCallCollection* clone(const TFCallCollection* source, Any* parent) override;
  TableEntryCollection* clone(const TableEntryCollection* source, Any* parent) override;
  TaggedPatternCollection* clone(const TaggedPatternCollection* source, Any* parent) override;
  TaskCallCollection* clone(const TaskCallCollection* source, Any* parent) override;
  TaskCollection* clone(const TaskCollection* source, Any* parent) override;
  TaskDeclCollection* clone(const TaskDeclCollection* source, Any* parent) override;
  TaskFuncCollection* clone(const TaskFuncCollection* source, Any* parent) override;
  TaskFuncDeclCollection* clone(const TaskFuncDeclCollection* source, Any* parent) override;
  TchkCollection* clone(const TchkCollection* source, Any* parent) override;
  TchkTermCollection* clone(const TchkTermCollection* source, Any* parent) override;
  ThreadCollection* clone(const ThreadCollection* source, Any* parent) override;
  TimeTypespecCollection* clone(const TimeTypespecCollection* source, Any* parent) override;
  TypeParameterCollection* clone(const TypeParameterCollection* source, Any* parent) override;
  TypedefTypespecCollection* clone(const TypedefTypespecCollection* source, Any* parent) override;
  TypespecCollection* clone(const TypespecCollection* source, Any* parent) override;
  TypespecMemberCollection* clone(const TypespecMemberCollection* source, Any* parent) override;
  UdpArrayCollection* clone(const UdpArrayCollection* source, Any* parent) override;
  UdpCollection* clone(const UdpCollection* source, Any* parent) override;
  UdpDefnCollection* clone(const UdpDefnCollection* source, Any* parent) override;
  UdpDefnTypespecCollection* clone(const UdpDefnTypespecCollection* source, Any* parent) override;
  UnionTypespecCollection* clone(const UnionTypespecCollection* source, Any* parent) override;
  UniquenessCollection* clone(const UniquenessCollection* source, Any* parent) override;
  UnsupportedExprCollection* clone(const UnsupportedExprCollection* source, Any* parent) override;
  UnsupportedStmtCollection* clone(const UnsupportedStmtCollection* source, Any* parent) override;
  UnsupportedTypespecCollection* clone(const UnsupportedTypespecCollection* source, Any* parent) override;
  UserSystfCollection* clone(const UserSystfCollection* source, Any* parent) override;
  VarSelectCollection* clone(const VarSelectCollection* source, Any* parent) override;
  VariableCollection* clone(const VariableCollection* source, Any* parent) override;
  VoidTypespecCollection* clone(const VoidTypespecCollection* source, Any* parent) override;
  WaitForkCollection* clone(const WaitForkCollection* source, Any* parent) override;
  WaitStmtCollection* clone(const WaitStmtCollection* source, Any* parent) override;
  WaitsCollection* clone(const WaitsCollection* source, Any* parent) override;
  WhileStmtCollection* clone(const WhileStmtCollection* source, Any* parent) override;
  // clang-format on
};

class MirrorCloner : public Cloner {
  UHDM_IMPLEMENT_RTTI(MirrorCloner, Cloner)

 public:
  explicit MirrorCloner(Serializer *serializer) : Cloner(serializer) {}
  ~MirrorCloner() override = default;
  MirrorCloner(const MirrorCloner &rhs) = delete;
  MirrorCloner &operator=(const MirrorCloner &rhs) = delete;

  using Cloner::clone;

 protected:
  Any *cloneAny(const Any *source, Any *parent) override;

 protected:
  using cloned_t = std::map<const Any *, Any *>;
  cloned_t m_cloned;
};
}  // namespace uhdm

UHDM_IMPLEMENT_RTTI_CAST_FUNCTIONS(cloner_cast, uhdm::Cloner)
#endif  // UHDM_CLONER_H
