/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   concurrent_assertions.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CONCURRENT_ASSERTIONS_H
#define UHDM_CONCURRENT_ASSERTIONS_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class ConcurrentAssertions : public Any {
  UHDM_IMPLEMENT_RTTI(ConcurrentAssertions, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ConcurrentAssertions;

  explicit ConcurrentAssertions(Serializer *serializer) : basetype_t(serializer) {}
  ConcurrentAssertions(Serializer *serializer, const ConcurrentAssertions& rhs);
  ~ConcurrentAssertions() override = default;
  ConcurrentAssertions(const ConcurrentAssertions& rhs) = delete;
  ConcurrentAssertions& operator=(const ConcurrentAssertions& rhs) = delete;

  std::string_view getLabel() const;
  bool setLabel(std::string_view name);
  Identifier* getLabelObj() { return m_label; }
  const Identifier* getLabelObj() const { return m_label; }
  template <typename T> T* getLabelObj() { return any_cast<T>(m_label); }
  template <typename T> const T* getLabelObj() const { return any_cast<T>(m_label); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setLabelObj(T, bool = false) = delete;
  bool setLabelObj(Identifier* data, bool force = false) {
    if ((m_label == nullptr) || (data == nullptr) || force) {
      m_label = data;
      return true;
    }
    return false;
  }

  bool getIsClockInferred() const { return m_isClockInferred; }
  bool setIsClockInferred(bool data) {
    m_isClockInferred = data;
    return true;
  }

  Expr* getClockingEvent() { return m_clockingEvent; }
  const Expr* getClockingEvent() const { return m_clockingEvent; }
  template <typename T> T* getClockingEvent() { return any_cast<T>(m_clockingEvent); }
  template <typename T> const T* getClockingEvent() const { return any_cast<T>(m_clockingEvent); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setClockingEvent(T, bool = false) = delete;
  bool setClockingEvent(Expr* data, bool force = false) {
    if ((m_clockingEvent == nullptr) || (data == nullptr) || force) {
      m_clockingEvent = data;
      return true;
    }
    return false;
  }

  Any* getStmt() { return m_stmt; }
  const Any* getStmt() const { return m_stmt; }
  template <typename T> T* getStmt() { return any_cast<T>(m_stmt); }
  template <typename T> const T* getStmt() const { return any_cast<T>(m_stmt); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setStmt(T, bool = false) = delete;
  bool setStmt(Any* data, bool force = false) {
    if ((m_stmt == nullptr) || (data == nullptr) || force) {
      m_stmt = data;
      return true;
    }
    return false;
  }

  Any* getProperty() { return m_property; }
  const Any* getProperty() const { return m_property; }
  template <typename T> T* getProperty() { return any_cast<T>(m_property); }
  template <typename T> const T* getProperty() const { return any_cast<T>(m_property); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setProperty(T, bool = false) = delete;
  bool setProperty(Any* data, bool force = false) {
    if ((m_property == nullptr) || (data == nullptr) || force) {
      m_property = data;
      return true;
    }
    return false;
  }

  AttributeCollection* getAttributes() const { return m_attributes; }
  template<typename T> AttributeCollection* getAttributes(T) = delete;
  AttributeCollection* getAttributes(bool createIfNull);
  bool setAttributes(AttributeCollection* data, bool force = false) {
    if ((m_attributes == nullptr) || (data == nullptr) || force) {
      m_attributes = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiConcurrentAssertions; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ConcurrentAssertions; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  Identifier* m_label = nullptr;
  bool m_isClockInferred = false;
  Expr* m_clockingEvent = nullptr;
  Any* m_stmt = nullptr;
  Any* m_property = nullptr;
  AttributeCollection* m_attributes = nullptr;
};
}  // namespace uhdm

#endif
