/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   config_rule.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CONFIG_RULE_H
#define UHDM_CONFIG_RULE_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class ConfigRule final : public Any {
  UHDM_IMPLEMENT_RTTI(ConfigRule, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ConfigRule;

  explicit ConfigRule(Serializer *serializer) : basetype_t(serializer) {}
  ConfigRule(Serializer *serializer, const ConfigRule& rhs);
  ~ConfigRule() override = default;
  ConfigRule(const ConfigRule& rhs) = delete;
  ConfigRule& operator=(const ConfigRule& rhs) = delete;

  Clause* getSelector() { return m_selector; }
  const Clause* getSelector() const { return m_selector; }
  template <typename T> T* getSelector() { return any_cast<T>(m_selector); }
  template <typename T> const T* getSelector() const { return any_cast<T>(m_selector); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setSelector(T, bool = false) = delete;
  bool setSelector(Clause* data, bool force = false) {
    if ((m_selector == nullptr) || (data == nullptr) || force) {
      m_selector = data;
      return true;
    }
    return false;
  }

  Clause* getTargetClause() { return m_targetClause; }
  const Clause* getTargetClause() const { return m_targetClause; }
  template <typename T> T* getTargetClause() { return any_cast<T>(m_targetClause); }
  template <typename T> const T* getTargetClause() const { return any_cast<T>(m_targetClause); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTargetClause(T, bool = false) = delete;
  bool setTargetClause(Clause* data, bool force = false) {
    if ((m_targetClause == nullptr) || (data == nullptr) || force) {
      m_targetClause = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiConfigRule; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ConfigRule; }


protected:
  Clause* m_selector = nullptr;
  Clause* m_targetClause = nullptr;
};
}  // namespace uhdm

#endif
