/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   constraint.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CONSTRAINT_H
#define UHDM_CONSTRAINT_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class Constraint final : public Any {
  UHDM_IMPLEMENT_RTTI(Constraint, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Constraint;

  explicit Constraint(Serializer *serializer) : basetype_t(serializer) {}
  Constraint(Serializer *serializer, const Constraint& rhs);
  ~Constraint() override = default;
  Constraint(const Constraint& rhs) = delete;
  Constraint& operator=(const Constraint& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  std::string_view getFullName() const;
  bool setFullName(std::string_view data);

  bool getVirtual() const { return m_virtual; }
  bool setVirtual(bool data) {
    m_virtual = data;
    return true;
  }

  bool getAutomatic() const { return m_automatic; }
  bool setAutomatic(bool data) {
    m_automatic = data;
    return true;
  }

  int32_t getAllocScheme() const { return m_allocScheme; }
  bool setAllocScheme(int32_t data) {
    m_allocScheme = data;
    return true;
  }

  int32_t getAccessType() const { return m_accessType; }
  bool setAccessType(int32_t data) {
    m_accessType = data;
    return true;
  }

  AttributeCollection* getAttributes() const { return m_attributes; }
  template<typename T> AttributeCollection* getAttributes(T) = delete;
  AttributeCollection* getAttributes(bool createIfNull);
  bool setAttributes(AttributeCollection* data, bool force = false) {
    if ((m_attributes == nullptr) || (data == nullptr) || force) {
      m_attributes = data;
      return true;
    }
    return false;
  }

  bool getIsConstraintEnabled() const { return m_isConstraintEnabled; }
  bool setIsConstraintEnabled(bool data) {
    m_isConstraintEnabled = data;
    return true;
  }

  AnyCollection* getConstraintItems() const { return m_constraintItems; }
  template<typename T> AnyCollection* getConstraintItems(T) = delete;
  AnyCollection* getConstraintItems(bool createIfNull);
  bool setConstraintItems(AnyCollection* data, bool force = false) {
    if ((m_constraintItems == nullptr) || (data == nullptr) || force) {
      m_constraintItems = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiConstraint; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Constraint; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  SymbolId m_name = BadSymbolId;
  SymbolId m_fullName = BadSymbolId;
  bool m_virtual = false;
  bool m_automatic = false;
  int32_t m_allocScheme = 0;
  int32_t m_accessType = 0;
  AttributeCollection* m_attributes = nullptr;
  bool m_isConstraintEnabled = false;
  AnyCollection* m_constraintItems = nullptr;
};
}  // namespace uhdm

#endif
