/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   constr_foreach.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_CONSTR_FOREACH_H
#define UHDM_CONSTR_FOREACH_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/constraint_expr.h>

namespace uhdm {
class ConstrForeach final : public ConstraintExpr {
  UHDM_IMPLEMENT_RTTI(ConstrForeach, ConstraintExpr)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ConstrForeach;

  explicit ConstrForeach(Serializer *serializer) : basetype_t(serializer) {}
  ConstrForeach(Serializer *serializer, const ConstrForeach& rhs);
  ~ConstrForeach() override = default;
  ConstrForeach(const ConstrForeach& rhs) = delete;
  ConstrForeach& operator=(const ConstrForeach& rhs) = delete;

  Any* getVariable() { return m_variable; }
  const Any* getVariable() const { return m_variable; }
  template <typename T> T* getVariable() { return any_cast<T>(m_variable); }
  template <typename T> const T* getVariable() const { return any_cast<T>(m_variable); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setVariable(T, bool = false) = delete;
  bool setVariable(Any* data, bool force = false) {
    if ((m_variable == nullptr) || (data == nullptr) || force) {
      m_variable = data;
      return true;
    }
    return false;
  }

  AnyCollection* getLoopVars() const { return m_loopVars; }
  template<typename T> AnyCollection* getLoopVars(T) = delete;
  AnyCollection* getLoopVars(bool createIfNull);
  bool setLoopVars(AnyCollection* data, bool force = false) {
    if ((m_loopVars == nullptr) || (data == nullptr) || force) {
      m_loopVars = data;
      return true;
    }
    return false;
  }

  ConstraintExprCollection* getConstraintExprs() const { return m_constraintExprs; }
  template<typename T> ConstraintExprCollection* getConstraintExprs(T) = delete;
  ConstraintExprCollection* getConstraintExprs(bool createIfNull);
  bool setConstraintExprs(ConstraintExprCollection* data, bool force = false) {
    if ((m_constraintExprs == nullptr) || (data == nullptr) || force) {
      m_constraintExprs = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiConstrForEach; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ConstrForeach; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  Any* m_variable = nullptr;
  AnyCollection* m_loopVars = nullptr;
  ConstraintExprCollection* m_constraintExprs = nullptr;
};
}  // namespace uhdm

#endif
