/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   cover.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_COVER_H
#define UHDM_COVER_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/concurrent_assertions.h>

namespace uhdm {
class Cover final : public ConcurrentAssertions {
  UHDM_IMPLEMENT_RTTI(Cover, ConcurrentAssertions)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Cover;

  explicit Cover(Serializer *serializer) : basetype_t(serializer) {}
  Cover(Serializer *serializer, const Cover& rhs);
  ~Cover() override = default;
  Cover(const Cover& rhs) = delete;
  Cover& operator=(const Cover& rhs) = delete;

  bool getIsCoverSequence() const { return m_isCoverSequence; }
  bool setIsCoverSequence(bool data) {
    m_isCoverSequence = data;
    return true;
  }

  ClockingBlock* getClockingBlock() { return m_clockingBlock; }
  const ClockingBlock* getClockingBlock() const { return m_clockingBlock; }
  template <typename T> T* getClockingBlock() { return any_cast<T>(m_clockingBlock); }
  template <typename T> const T* getClockingBlock() const { return any_cast<T>(m_clockingBlock); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setClockingBlock(T, bool = false) = delete;
  bool setClockingBlock(ClockingBlock* data, bool force = false) {
    if ((m_clockingBlock == nullptr) || (data == nullptr) || force) {
      m_clockingBlock = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiCover; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Cover; }


protected:
  bool m_isCoverSequence = false;
  ClockingBlock* m_clockingBlock = nullptr;
};
}  // namespace uhdm

#endif
