/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   design.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_DESIGN_H
#define UHDM_DESIGN_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class Design final : public Any {
  UHDM_IMPLEMENT_RTTI(Design, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Design;

  explicit Design(Serializer *serializer) : basetype_t(serializer) {}
  Design(Serializer *serializer, const Design& rhs);
  ~Design() override = default;
  Design(const Design& rhs) = delete;
  Design& operator=(const Design& rhs) = delete;

  bool getElaborated() const { return m_elaborated; }
  bool setElaborated(bool data) {
    m_elaborated = data;
    return true;
  }

  std::string_view getName() const override;
  bool setName(std::string_view data);

  SourceFileCollection* getSourceFiles() const { return m_sourceFiles; }
  template<typename T> SourceFileCollection* getSourceFiles(T) = delete;
  SourceFileCollection* getSourceFiles(bool createIfNull);
  bool setSourceFiles(SourceFileCollection* data, bool force = false) {
    if ((m_sourceFiles == nullptr) || (data == nullptr) || force) {
      m_sourceFiles = data;
      return true;
    }
    return false;
  }

  PackageCollection* getAllPackages() const { return m_allPackages; }
  template<typename T> PackageCollection* getAllPackages(T) = delete;
  PackageCollection* getAllPackages(bool createIfNull);
  bool setAllPackages(PackageCollection* data, bool force = false) {
    if ((m_allPackages == nullptr) || (data == nullptr) || force) {
      m_allPackages = data;
      return true;
    }
    return false;
  }

  PackageCollection* getTopPackages() const { return m_topPackages; }
  template<typename T> PackageCollection* getTopPackages(T) = delete;
  PackageCollection* getTopPackages(bool createIfNull);
  bool setTopPackages(PackageCollection* data, bool force = false) {
    if ((m_topPackages == nullptr) || (data == nullptr) || force) {
      m_topPackages = data;
      return true;
    }
    return false;
  }

  ClassDefnCollection* getAllClasses() const { return m_allClasses; }
  template<typename T> ClassDefnCollection* getAllClasses(T) = delete;
  ClassDefnCollection* getAllClasses(bool createIfNull);
  bool setAllClasses(ClassDefnCollection* data, bool force = false) {
    if ((m_allClasses == nullptr) || (data == nullptr) || force) {
      m_allClasses = data;
      return true;
    }
    return false;
  }

  InterfaceCollection* getAllInterfaces() const { return m_allInterfaces; }
  template<typename T> InterfaceCollection* getAllInterfaces(T) = delete;
  InterfaceCollection* getAllInterfaces(bool createIfNull);
  bool setAllInterfaces(InterfaceCollection* data, bool force = false) {
    if ((m_allInterfaces == nullptr) || (data == nullptr) || force) {
      m_allInterfaces = data;
      return true;
    }
    return false;
  }

  UdpDefnCollection* getAllUdps() const { return m_allUdps; }
  template<typename T> UdpDefnCollection* getAllUdps(T) = delete;
  UdpDefnCollection* getAllUdps(bool createIfNull);
  bool setAllUdps(UdpDefnCollection* data, bool force = false) {
    if ((m_allUdps == nullptr) || (data == nullptr) || force) {
      m_allUdps = data;
      return true;
    }
    return false;
  }

  ProgramCollection* getAllPrograms() const { return m_allPrograms; }
  template<typename T> ProgramCollection* getAllPrograms(T) = delete;
  ProgramCollection* getAllPrograms(bool createIfNull);
  bool setAllPrograms(ProgramCollection* data, bool force = false) {
    if ((m_allPrograms == nullptr) || (data == nullptr) || force) {
      m_allPrograms = data;
      return true;
    }
    return false;
  }

  ModuleCollection* getAllModules() const { return m_allModules; }
  template<typename T> ModuleCollection* getAllModules(T) = delete;
  ModuleCollection* getAllModules(bool createIfNull);
  bool setAllModules(ModuleCollection* data, bool force = false) {
    if ((m_allModules == nullptr) || (data == nullptr) || force) {
      m_allModules = data;
      return true;
    }
    return false;
  }

  TypespecCollection* getTypespecs() const { return m_typespecs; }
  template<typename T> TypespecCollection* getTypespecs(T) = delete;
  TypespecCollection* getTypespecs(bool createIfNull);
  bool setTypespecs(TypespecCollection* data, bool force = false) {
    if ((m_typespecs == nullptr) || (data == nullptr) || force) {
      m_typespecs = data;
      return true;
    }
    return false;
  }

  LetDeclCollection* getLetDecls() const { return m_letDecls; }
  template<typename T> LetDeclCollection* getLetDecls(T) = delete;
  LetDeclCollection* getLetDecls(bool createIfNull);
  bool setLetDecls(LetDeclCollection* data, bool force = false) {
    if ((m_letDecls == nullptr) || (data == nullptr) || force) {
      m_letDecls = data;
      return true;
    }
    return false;
  }

  TaskFuncCollection* getTaskFuncs() const { return m_taskFuncs; }
  template<typename T> TaskFuncCollection* getTaskFuncs(T) = delete;
  TaskFuncCollection* getTaskFuncs(bool createIfNull);
  bool setTaskFuncs(TaskFuncCollection* data, bool force = false) {
    if ((m_taskFuncs == nullptr) || (data == nullptr) || force) {
      m_taskFuncs = data;
      return true;
    }
    return false;
  }

  TaskFuncDeclCollection* getTaskFuncDecls() const { return m_taskFuncDecls; }
  template<typename T> TaskFuncDeclCollection* getTaskFuncDecls(T) = delete;
  TaskFuncDeclCollection* getTaskFuncDecls(bool createIfNull);
  bool setTaskFuncDecls(TaskFuncDeclCollection* data, bool force = false) {
    if ((m_taskFuncDecls == nullptr) || (data == nullptr) || force) {
      m_taskFuncDecls = data;
      return true;
    }
    return false;
  }

  AnyCollection* getParameters() const { return m_parameters; }
  template<typename T> AnyCollection* getParameters(T) = delete;
  AnyCollection* getParameters(bool createIfNull);
  bool setParameters(AnyCollection* data, bool force = false) {
    if ((m_parameters == nullptr) || (data == nullptr) || force) {
      m_parameters = data;
      return true;
    }
    return false;
  }

  ParamAssignCollection* getParamAssigns() const { return m_paramAssigns; }
  template<typename T> ParamAssignCollection* getParamAssigns(T) = delete;
  ParamAssignCollection* getParamAssigns(bool createIfNull);
  bool setParamAssigns(ParamAssignCollection* data, bool force = false) {
    if ((m_paramAssigns == nullptr) || (data == nullptr) || force) {
      m_paramAssigns = data;
      return true;
    }
    return false;
  }

  VariableCollection* getVariables() const { return m_variables; }
  template<typename T> VariableCollection* getVariables(T) = delete;
  VariableCollection* getVariables(bool createIfNull);
  bool setVariables(VariableCollection* data, bool force = false) {
    if ((m_variables == nullptr) || (data == nullptr) || force) {
      m_variables = data;
      return true;
    }
    return false;
  }

  ModuleCollection* getTopModules() const { return m_topModules; }
  template<typename T> ModuleCollection* getTopModules(T) = delete;
  ModuleCollection* getTopModules(bool createIfNull);
  bool setTopModules(ModuleCollection* data, bool force = false) {
    if ((m_topModules == nullptr) || (data == nullptr) || force) {
      m_topModules = data;
      return true;
    }
    return false;
  }

  BindDirectiveCollection* getBindDirectives() const { return m_bindDirectives; }
  template<typename T> BindDirectiveCollection* getBindDirectives(T) = delete;
  BindDirectiveCollection* getBindDirectives(bool createIfNull);
  bool setBindDirectives(BindDirectiveCollection* data, bool force = false) {
    if ((m_bindDirectives == nullptr) || (data == nullptr) || force) {
      m_bindDirectives = data;
      return true;
    }
    return false;
  }

  LibraryCollection* getLibraries() const { return m_libraries; }
  template<typename T> LibraryCollection* getLibraries(T) = delete;
  LibraryCollection* getLibraries(bool createIfNull);
  bool setLibraries(LibraryCollection* data, bool force = false) {
    if ((m_libraries == nullptr) || (data == nullptr) || force) {
      m_libraries = data;
      return true;
    }
    return false;
  }

  ConfigDeclCollection* getConfigs() const { return m_configs; }
  template<typename T> ConfigDeclCollection* getConfigs(T) = delete;
  ConfigDeclCollection* getConfigs(bool createIfNull);
  bool setConfigs(ConfigDeclCollection* data, bool force = false) {
    if ((m_configs == nullptr) || (data == nullptr) || force) {
      m_configs = data;
      return true;
    }
    return false;
  }

  IncludeStmtCollection* getIncludeStmts() const { return m_includeStmts; }
  template<typename T> IncludeStmtCollection* getIncludeStmts(T) = delete;
  IncludeStmtCollection* getIncludeStmts(bool createIfNull);
  bool setIncludeStmts(IncludeStmtCollection* data, bool force = false) {
    if ((m_includeStmts == nullptr) || (data == nullptr) || force) {
      m_includeStmts = data;
      return true;
    }
    return false;
  }

  CheckerDeclCollection* getCheckerDecls() const { return m_checkerDecls; }
  template<typename T> CheckerDeclCollection* getCheckerDecls(T) = delete;
  CheckerDeclCollection* getCheckerDecls(bool createIfNull);
  bool setCheckerDecls(CheckerDeclCollection* data, bool force = false) {
    if ((m_checkerDecls == nullptr) || (data == nullptr) || force) {
      m_checkerDecls = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiDesign; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Design; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  bool m_elaborated = false;
  SymbolId m_name = BadSymbolId;
  SourceFileCollection* m_sourceFiles = nullptr;
  PackageCollection* m_allPackages = nullptr;
  PackageCollection* m_topPackages = nullptr;
  ClassDefnCollection* m_allClasses = nullptr;
  InterfaceCollection* m_allInterfaces = nullptr;
  UdpDefnCollection* m_allUdps = nullptr;
  ProgramCollection* m_allPrograms = nullptr;
  ModuleCollection* m_allModules = nullptr;
  TypespecCollection* m_typespecs = nullptr;
  LetDeclCollection* m_letDecls = nullptr;
  TaskFuncCollection* m_taskFuncs = nullptr;
  TaskFuncDeclCollection* m_taskFuncDecls = nullptr;
  AnyCollection* m_parameters = nullptr;
  ParamAssignCollection* m_paramAssigns = nullptr;
  VariableCollection* m_variables = nullptr;
  ModuleCollection* m_topModules = nullptr;
  BindDirectiveCollection* m_bindDirectives = nullptr;
  LibraryCollection* m_libraries = nullptr;
  ConfigDeclCollection* m_configs = nullptr;
  IncludeStmtCollection* m_includeStmts = nullptr;
  CheckerDeclCollection* m_checkerDecls = nullptr;
};
}  // namespace uhdm

#endif
