/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   dist_item.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_DIST_ITEM_H
#define UHDM_DIST_ITEM_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class DistItem final : public Any {
  UHDM_IMPLEMENT_RTTI(DistItem, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::DistItem;

  explicit DistItem(Serializer *serializer) : basetype_t(serializer) {}
  DistItem(Serializer *serializer, const DistItem& rhs);
  ~DistItem() override = default;
  DistItem(const DistItem& rhs) = delete;
  DistItem& operator=(const DistItem& rhs) = delete;

  int32_t getDistType() const { return m_distType; }
  bool setDistType(int32_t data) {
    m_distType = data;
    return true;
  }

  Any* getValueRange() { return m_valueRange; }
  const Any* getValueRange() const { return m_valueRange; }
  template <typename T> T* getValueRange() { return any_cast<T>(m_valueRange); }
  template <typename T> const T* getValueRange() const { return any_cast<T>(m_valueRange); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setValueRange(T, bool = false) = delete;
  bool setValueRange(Any* data, bool force = false) {
    if ((m_valueRange == nullptr) || (data == nullptr) || force) {
      m_valueRange = data;
      return true;
    }
    return false;
  }

  Expr* getWeight() { return m_weight; }
  const Expr* getWeight() const { return m_weight; }
  template <typename T> T* getWeight() { return any_cast<T>(m_weight); }
  template <typename T> const T* getWeight() const { return any_cast<T>(m_weight); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setWeight(T, bool = false) = delete;
  bool setWeight(Expr* data, bool force = false) {
    if ((m_weight == nullptr) || (data == nullptr) || force) {
      m_weight = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiDistItem; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::DistItem; }


protected:
  int32_t m_distType = 0;
  Any* m_valueRange = nullptr;
  Expr* m_weight = nullptr;
};
}  // namespace uhdm

#endif
