/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   enum_typespec.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_ENUM_TYPESPEC_H
#define UHDM_ENUM_TYPESPEC_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/typespec.h>

namespace uhdm {
class EnumTypespec final : public Typespec {
  UHDM_IMPLEMENT_RTTI(EnumTypespec, Typespec)

public:
  static constexpr UhdmType kUhdmType = UhdmType::EnumTypespec;

  explicit EnumTypespec(Serializer *serializer) : basetype_t(serializer) {}
  EnumTypespec(Serializer *serializer, const EnumTypespec& rhs);
  ~EnumTypespec() override = default;
  EnumTypespec(const EnumTypespec& rhs) = delete;
  EnumTypespec& operator=(const EnumTypespec& rhs) = delete;

  RefTypespec* getBaseTypespec() { return m_baseTypespec; }
  const RefTypespec* getBaseTypespec() const { return m_baseTypespec; }
  template <typename T> T* getBaseTypespec() { return any_cast<T>(m_baseTypespec); }
  template <typename T> const T* getBaseTypespec() const { return any_cast<T>(m_baseTypespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setBaseTypespec(T, bool = false) = delete;
  bool setBaseTypespec(RefTypespec* data, bool force = false) {
    if ((m_baseTypespec == nullptr) || (data == nullptr) || force) {
      m_baseTypespec = data;
      return true;
    }
    return false;
  }

  EnumConstCollection* getEnumConsts() const { return m_enumConsts; }
  template<typename T> EnumConstCollection* getEnumConsts(T) = delete;
  EnumConstCollection* getEnumConsts(bool createIfNull);
  bool setEnumConsts(EnumConstCollection* data, bool force = false) {
    if ((m_enumConsts == nullptr) || (data == nullptr) || force) {
      m_enumConsts = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiEnumTypespec; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::EnumTypespec; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  RefTypespec* m_baseTypespec = nullptr;
  EnumConstCollection* m_enumConsts = nullptr;
};
}  // namespace uhdm

#endif
