/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   event_stmt.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_EVENT_STMT_H
#define UHDM_EVENT_STMT_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/atomic_stmt.h>

namespace uhdm {
class EventStmt final : public AtomicStmt {
  UHDM_IMPLEMENT_RTTI(EventStmt, AtomicStmt)

public:
  static constexpr UhdmType kUhdmType = UhdmType::EventStmt;

  explicit EventStmt(Serializer *serializer) : basetype_t(serializer) {}
  EventStmt(Serializer *serializer, const EventStmt& rhs);
  ~EventStmt() override = default;
  EventStmt(const EventStmt& rhs) = delete;
  EventStmt& operator=(const EventStmt& rhs) = delete;

  bool getBlocking() const { return m_blocking; }
  bool setBlocking(bool data) {
    m_blocking = data;
    return true;
  }

  NamedEvent* getNamedEvent() { return m_namedEvent; }
  const NamedEvent* getNamedEvent() const { return m_namedEvent; }
  template <typename T> T* getNamedEvent() { return any_cast<T>(m_namedEvent); }
  template <typename T> const T* getNamedEvent() const { return any_cast<T>(m_namedEvent); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setNamedEvent(T, bool = false) = delete;
  bool setNamedEvent(NamedEvent* data, bool force = false) {
    if ((m_namedEvent == nullptr) || (data == nullptr) || force) {
      m_namedEvent = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiEventStmt; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::EventStmt; }


protected:
  bool m_blocking = false;
  NamedEvent* m_namedEvent = nullptr;
};
}  // namespace uhdm

#endif
