/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   fork_stmt.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_FORK_STMT_H
#define UHDM_FORK_STMT_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/scope.h>

namespace uhdm {
class ForkStmt final : public Scope {
  UHDM_IMPLEMENT_RTTI(ForkStmt, Scope)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ForkStmt;

  explicit ForkStmt(Serializer *serializer) : basetype_t(serializer) {}
  ForkStmt(Serializer *serializer, const ForkStmt& rhs);
  ~ForkStmt() override = default;
  ForkStmt(const ForkStmt& rhs) = delete;
  ForkStmt& operator=(const ForkStmt& rhs) = delete;

  int32_t getJoinType() const { return m_joinType; }
  bool setJoinType(int32_t data) {
    m_joinType = data;
    return true;
  }

  AnyCollection* getStmts() const { return m_stmts; }
  template<typename T> AnyCollection* getStmts(T) = delete;
  AnyCollection* getStmts(bool createIfNull);
  bool setStmts(AnyCollection* data, bool force = false) {
    if ((m_stmts == nullptr) || (data == nullptr) || force) {
      m_stmts = data;
      return true;
    }
    return false;
  }

  std::string_view getEndLabel() const;
  bool setEndLabel(std::string_view name);
  Identifier* getEndLabelObj() { return m_endLabel; }
  const Identifier* getEndLabelObj() const { return m_endLabel; }
  template <typename T> T* getEndLabelObj() { return any_cast<T>(m_endLabel); }
  template <typename T> const T* getEndLabelObj() const { return any_cast<T>(m_endLabel); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setEndLabelObj(T, bool = false) = delete;
  bool setEndLabelObj(Identifier* data, bool force = false) {
    if ((m_endLabel == nullptr) || (data == nullptr) || force) {
      m_endLabel = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiFork; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ForkStmt; }


protected:
  int32_t m_joinType = 0;
  AnyCollection* m_stmts = nullptr;
  Identifier* m_endLabel = nullptr;
};
}  // namespace uhdm

#endif
