/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   gate_array.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_GATE_ARRAY_H
#define UHDM_GATE_ARRAY_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/primitive_array.h>

namespace uhdm {
class GateArray final : public PrimitiveArray {
  UHDM_IMPLEMENT_RTTI(GateArray, PrimitiveArray)

public:
  static constexpr UhdmType kUhdmType = UhdmType::GateArray;

  explicit GateArray(Serializer *serializer) : basetype_t(serializer) {}
  GateArray(Serializer *serializer, const GateArray& rhs);
  ~GateArray() override = default;
  GateArray(const GateArray& rhs) = delete;
  GateArray& operator=(const GateArray& rhs) = delete;

  Gate* getGate() { return m_gate; }
  const Gate* getGate() const { return m_gate; }
  template <typename T> T* getGate() { return any_cast<T>(m_gate); }
  template <typename T> const T* getGate() const { return any_cast<T>(m_gate); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setGate(T, bool = false) = delete;
  bool setGate(Gate* data, bool force = false) {
    if ((m_gate == nullptr) || (data == nullptr) || force) {
      m_gate = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiGateArray; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::GateArray; }


protected:
  Gate* m_gate = nullptr;
};
}  // namespace uhdm

#endif
