/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   immediate_cover.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_IMMEDIATE_COVER_H
#define UHDM_IMMEDIATE_COVER_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/atomic_stmt.h>

namespace uhdm {
class ImmediateCover final : public AtomicStmt {
  UHDM_IMPLEMENT_RTTI(ImmediateCover, AtomicStmt)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ImmediateCover;

  explicit ImmediateCover(Serializer *serializer) : basetype_t(serializer) {}
  ImmediateCover(Serializer *serializer, const ImmediateCover& rhs);
  ~ImmediateCover() override = default;
  ImmediateCover(const ImmediateCover& rhs) = delete;
  ImmediateCover& operator=(const ImmediateCover& rhs) = delete;

  int32_t getIsDeferred() const { return m_isDeferred; }
  bool setIsDeferred(int32_t data) {
    m_isDeferred = data;
    return true;
  }

  int32_t getIsFinal() const { return m_isFinal; }
  bool setIsFinal(int32_t data) {
    m_isFinal = data;
    return true;
  }

  Any* getExpr() { return m_expr; }
  const Any* getExpr() const { return m_expr; }
  template <typename T> T* getExpr() { return any_cast<T>(m_expr); }
  template <typename T> const T* getExpr() const { return any_cast<T>(m_expr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setExpr(T, bool = false) = delete;
  bool setExpr(Any* data, bool force = false) {
    if ((m_expr == nullptr) || (data == nullptr) || force) {
      m_expr = data;
      return true;
    }
    return false;
  }

  Any* getStmt() { return m_stmt; }
  const Any* getStmt() const { return m_stmt; }
  template <typename T> T* getStmt() { return any_cast<T>(m_stmt); }
  template <typename T> const T* getStmt() const { return any_cast<T>(m_stmt); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setStmt(T, bool = false) = delete;
  bool setStmt(Any* data, bool force = false) {
    if ((m_stmt == nullptr) || (data == nullptr) || force) {
      m_stmt = data;
      return true;
    }
    return false;
  }

  ClockingBlock* getClockingBlock() { return m_clockingBlock; }
  const ClockingBlock* getClockingBlock() const { return m_clockingBlock; }
  template <typename T> T* getClockingBlock() { return any_cast<T>(m_clockingBlock); }
  template <typename T> const T* getClockingBlock() const { return any_cast<T>(m_clockingBlock); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setClockingBlock(T, bool = false) = delete;
  bool setClockingBlock(ClockingBlock* data, bool force = false) {
    if ((m_clockingBlock == nullptr) || (data == nullptr) || force) {
      m_clockingBlock = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiImmediateCover; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ImmediateCover; }


protected:
  int32_t m_isDeferred = 0;
  int32_t m_isFinal = 0;
  Any* m_expr = nullptr;
  Any* m_stmt = nullptr;
  ClockingBlock* m_clockingBlock = nullptr;
};
}  // namespace uhdm

#endif
