/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   instance.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_INSTANCE_H
#define UHDM_INSTANCE_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/scope.h>

namespace uhdm {
class Instance : public Scope {
  UHDM_IMPLEMENT_RTTI(Instance, Scope)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Instance;

  explicit Instance(Serializer *serializer) : basetype_t(serializer) {}
  Instance(Serializer *serializer, const Instance& rhs);
  ~Instance() override = default;
  Instance(const Instance& rhs) = delete;
  Instance& operator=(const Instance& rhs) = delete;

  std::string_view getDefName() const override;
  bool setDefName(std::string_view data);

  bool getArrayMember() const { return m_arrayMember; }
  bool setArrayMember(bool data) {
    m_arrayMember = data;
    return true;
  }

  bool getCellInstance() const { return m_cellInstance; }
  bool setCellInstance(bool data) {
    m_cellInstance = data;
    return true;
  }

  int32_t getDefNetType() const { return m_defNetType; }
  bool setDefNetType(int32_t data) {
    m_defNetType = data;
    return true;
  }

  std::string_view getDefFile() const;
  bool setDefFile(std::string_view data);

  int32_t getDefLineNo() const { return m_defLineNo; }
  bool setDefLineNo(int32_t data) {
    m_defLineNo = data;
    return true;
  }

  int32_t getDefDelayMode() const { return m_defDelayMode; }
  bool setDefDelayMode(int32_t data) {
    m_defDelayMode = data;
    return true;
  }

  bool getProtected() const { return m_protected; }
  bool setProtected(bool data) {
    m_protected = data;
    return true;
  }

  int32_t getTimePrecision() const { return m_timePrecision; }
  bool setTimePrecision(int32_t data) {
    m_timePrecision = data;
    return true;
  }

  int32_t getTimeUnit() const { return m_timeUnit; }
  bool setTimeUnit(int32_t data) {
    m_timeUnit = data;
    return true;
  }

  int32_t getUnconnDrive() const { return m_unconnDrive; }
  bool setUnconnDrive(int32_t data) {
    m_unconnDrive = data;
    return true;
  }

  RefObj* getLibrary() { return m_library; }
  const RefObj* getLibrary() const { return m_library; }
  template <typename T> T* getLibrary() { return any_cast<T>(m_library); }
  template <typename T> const T* getLibrary() const { return any_cast<T>(m_library); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setLibrary(T, bool = false) = delete;
  bool setLibrary(RefObj* data, bool force = false) {
    if ((m_library == nullptr) || (data == nullptr) || force) {
      m_library = data;
      return true;
    }
    return false;
  }

  std::string_view getCell() const;
  bool setCell(std::string_view data);

  RefObj* getConfig() { return m_config; }
  const RefObj* getConfig() const { return m_config; }
  template <typename T> T* getConfig() { return any_cast<T>(m_config); }
  template <typename T> const T* getConfig() const { return any_cast<T>(m_config); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setConfig(T, bool = false) = delete;
  bool setConfig(RefObj* data, bool force = false) {
    if ((m_config == nullptr) || (data == nullptr) || force) {
      m_config = data;
      return true;
    }
    return false;
  }

  bool getAutomatic() const { return m_automatic; }
  bool setAutomatic(bool data) {
    m_automatic = data;
    return true;
  }

  bool getTop() const { return m_top; }
  bool setTop(bool data) {
    m_top = data;
    return true;
  }

  ProgramCollection* getPrograms() const { return m_programs; }
  template<typename T> ProgramCollection* getPrograms(T) = delete;
  ProgramCollection* getPrograms(bool createIfNull);
  bool setPrograms(ProgramCollection* data, bool force = false) {
    if ((m_programs == nullptr) || (data == nullptr) || force) {
      m_programs = data;
      return true;
    }
    return false;
  }

  ProgramArrayCollection* getProgramArrays() const { return m_programArrays; }
  template<typename T> ProgramArrayCollection* getProgramArrays(T) = delete;
  ProgramArrayCollection* getProgramArrays(bool createIfNull);
  bool setProgramArrays(ProgramArrayCollection* data, bool force = false) {
    if ((m_programArrays == nullptr) || (data == nullptr) || force) {
      m_programArrays = data;
      return true;
    }
    return false;
  }

  ClassDefnCollection* getClassDefns() const { return m_classDefns; }
  template<typename T> ClassDefnCollection* getClassDefns(T) = delete;
  ClassDefnCollection* getClassDefns(bool createIfNull);
  bool setClassDefns(ClassDefnCollection* data, bool force = false) {
    if ((m_classDefns == nullptr) || (data == nullptr) || force) {
      m_classDefns = data;
      return true;
    }
    return false;
  }

  TaskFuncCollection* getTaskFuncs() const { return m_taskFuncs; }
  template<typename T> TaskFuncCollection* getTaskFuncs(T) = delete;
  TaskFuncCollection* getTaskFuncs(bool createIfNull);
  bool setTaskFuncs(TaskFuncCollection* data, bool force = false) {
    if ((m_taskFuncs == nullptr) || (data == nullptr) || force) {
      m_taskFuncs = data;
      return true;
    }
    return false;
  }

  TaskFuncDeclCollection* getTaskFuncDecls() const { return m_taskFuncDecls; }
  template<typename T> TaskFuncDeclCollection* getTaskFuncDecls(T) = delete;
  TaskFuncDeclCollection* getTaskFuncDecls(bool createIfNull);
  bool setTaskFuncDecls(TaskFuncDeclCollection* data, bool force = false) {
    if ((m_taskFuncDecls == nullptr) || (data == nullptr) || force) {
      m_taskFuncDecls = data;
      return true;
    }
    return false;
  }

  NetCollection* getNets() const { return m_nets; }
  template<typename T> NetCollection* getNets(T) = delete;
  NetCollection* getNets(bool createIfNull);
  bool setNets(NetCollection* data, bool force = false) {
    if ((m_nets == nullptr) || (data == nullptr) || force) {
      m_nets = data;
      return true;
    }
    return false;
  }

  SpecParamCollection* getSpecParams() const { return m_specParams; }
  template<typename T> SpecParamCollection* getSpecParams(T) = delete;
  SpecParamCollection* getSpecParams(bool createIfNull);
  bool setSpecParams(SpecParamCollection* data, bool force = false) {
    if ((m_specParams == nullptr) || (data == nullptr) || force) {
      m_specParams = data;
      return true;
    }
    return false;
  }

  AnyCollection* getAssertions() const { return m_assertions; }
  template<typename T> AnyCollection* getAssertions(T) = delete;
  AnyCollection* getAssertions(bool createIfNull);
  bool setAssertions(AnyCollection* data, bool force = false) {
    if ((m_assertions == nullptr) || (data == nullptr) || force) {
      m_assertions = data;
      return true;
    }
    return false;
  }

  Module* getModule() { return m_module; }
  const Module* getModule() const { return m_module; }
  template <typename T> T* getModule() { return any_cast<T>(m_module); }
  template <typename T> const T* getModule() const { return any_cast<T>(m_module); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setModule(T, bool = false) = delete;
  bool setModule(Module* data, bool force = false) {
    if ((m_module == nullptr) || (data == nullptr) || force) {
      m_module = data;
      return true;
    }
    return false;
  }

  Instance* getInstance() { return m_instance; }
  const Instance* getInstance() const { return m_instance; }
  template <typename T> T* getInstance() { return any_cast<T>(m_instance); }
  template <typename T> const T* getInstance() const { return any_cast<T>(m_instance); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInstance(T, bool = false) = delete;
  bool setInstance(Instance* data, bool force = false) {
    if ((m_instance == nullptr) || (data == nullptr) || force) {
      m_instance = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiInstance; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Instance; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  SymbolId m_defName = BadSymbolId;
  bool m_arrayMember = false;
  bool m_cellInstance = false;
  int32_t m_defNetType = 0;
  SymbolId m_defFile = BadSymbolId;
  int32_t m_defLineNo = 0;
  int32_t m_defDelayMode = 0;
  bool m_protected = false;
  int32_t m_timePrecision = 0;
  int32_t m_timeUnit = 0;
  int32_t m_unconnDrive = 0;
  RefObj* m_library = nullptr;
  SymbolId m_cell = BadSymbolId;
  RefObj* m_config = nullptr;
  bool m_automatic = false;
  bool m_top = false;
  ProgramCollection* m_programs = nullptr;
  ProgramArrayCollection* m_programArrays = nullptr;
  ClassDefnCollection* m_classDefns = nullptr;
  TaskFuncCollection* m_taskFuncs = nullptr;
  TaskFuncDeclCollection* m_taskFuncDecls = nullptr;
  NetCollection* m_nets = nullptr;
  SpecParamCollection* m_specParams = nullptr;
  AnyCollection* m_assertions = nullptr;
  Module* m_module = nullptr;
  Instance* m_instance = nullptr;
};
}  // namespace uhdm

#endif
