/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   interface_tf_decl.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_INTERFACE_TF_DECL_H
#define UHDM_INTERFACE_TF_DECL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class InterfaceTFDecl final : public Any {
  UHDM_IMPLEMENT_RTTI(InterfaceTFDecl, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::InterfaceTFDecl;

  explicit InterfaceTFDecl(Serializer *serializer) : basetype_t(serializer) {}
  InterfaceTFDecl(Serializer *serializer, const InterfaceTFDecl& rhs);
  ~InterfaceTFDecl() override = default;
  InterfaceTFDecl(const InterfaceTFDecl& rhs) = delete;
  InterfaceTFDecl& operator=(const InterfaceTFDecl& rhs) = delete;

  int32_t getAccessType() const { return m_accessType; }
  bool setAccessType(int32_t data) {
    m_accessType = data;
    return true;
  }

  TaskCollection* getTasks() const { return m_tasks; }
  template<typename T> TaskCollection* getTasks(T) = delete;
  TaskCollection* getTasks(bool createIfNull);
  bool setTasks(TaskCollection* data, bool force = false) {
    if ((m_tasks == nullptr) || (data == nullptr) || force) {
      m_tasks = data;
      return true;
    }
    return false;
  }

  FunctionCollection* getFunctions() const { return m_functions; }
  template<typename T> FunctionCollection* getFunctions(T) = delete;
  FunctionCollection* getFunctions(bool createIfNull);
  bool setFunctions(FunctionCollection* data, bool force = false) {
    if ((m_functions == nullptr) || (data == nullptr) || force) {
      m_functions = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiInterfaceTfDecl; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::InterfaceTFDecl; }


protected:
  int32_t m_accessType = 0;
  TaskCollection* m_tasks = nullptr;
  FunctionCollection* m_functions = nullptr;
};
}  // namespace uhdm

#endif
