/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   let_decl.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_LET_DECL_H
#define UHDM_LET_DECL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class LetDecl final : public Any {
  UHDM_IMPLEMENT_RTTI(LetDecl, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::LetDecl;

  explicit LetDecl(Serializer *serializer) : basetype_t(serializer) {}
  LetDecl(Serializer *serializer, const LetDecl& rhs);
  ~LetDecl() override = default;
  LetDecl(const LetDecl& rhs) = delete;
  LetDecl& operator=(const LetDecl& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view name);
  Identifier* getNameObj() { return m_name; }
  const Identifier* getNameObj() const { return m_name; }
  template <typename T> T* getNameObj() { return any_cast<T>(m_name); }
  template <typename T> const T* getNameObj() const { return any_cast<T>(m_name); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setNameObj(T, bool = false) = delete;
  bool setNameObj(Identifier* data, bool force = false) {
    if ((m_name == nullptr) || (data == nullptr) || force) {
      m_name = data;
      return true;
    }
    return false;
  }

  Expr* getExpr() { return m_expr; }
  const Expr* getExpr() const { return m_expr; }
  template <typename T> T* getExpr() { return any_cast<T>(m_expr); }
  template <typename T> const T* getExpr() const { return any_cast<T>(m_expr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setExpr(T, bool = false) = delete;
  bool setExpr(Expr* data, bool force = false) {
    if ((m_expr == nullptr) || (data == nullptr) || force) {
      m_expr = data;
      return true;
    }
    return false;
  }

  SeqFormalDeclCollection* getSeqFormalDecls() const { return m_seqFormalDecls; }
  template<typename T> SeqFormalDeclCollection* getSeqFormalDecls(T) = delete;
  SeqFormalDeclCollection* getSeqFormalDecls(bool createIfNull);
  bool setSeqFormalDecls(SeqFormalDeclCollection* data, bool force = false) {
    if ((m_seqFormalDecls == nullptr) || (data == nullptr) || force) {
      m_seqFormalDecls = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiLetDecl; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::LetDecl; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  Identifier* m_name = nullptr;
  Expr* m_expr = nullptr;
  SeqFormalDeclCollection* m_seqFormalDecls = nullptr;
};
}  // namespace uhdm

#endif
