/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   library.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_LIBRARY_H
#define UHDM_LIBRARY_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class Library final : public Any {
  UHDM_IMPLEMENT_RTTI(Library, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Library;

  explicit Library(Serializer *serializer) : basetype_t(serializer) {}
  Library(Serializer *serializer, const Library& rhs);
  ~Library() override = default;
  Library(const Library& rhs) = delete;
  Library& operator=(const Library& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  IdentifierCollection* getSourceFiles() const { return m_sourceFiles; }
  template<typename T> IdentifierCollection* getSourceFiles(T) = delete;
  IdentifierCollection* getSourceFiles(bool createIfNull);
  bool setSourceFiles(IdentifierCollection* data, bool force = false) {
    if ((m_sourceFiles == nullptr) || (data == nullptr) || force) {
      m_sourceFiles = data;
      return true;
    }
    return false;
  }

  AnyCollection* getCells() const { return m_cells; }
  template<typename T> AnyCollection* getCells(T) = delete;
  AnyCollection* getCells(bool createIfNull);
  bool setCells(AnyCollection* data, bool force = false) {
    if ((m_cells == nullptr) || (data == nullptr) || force) {
      m_cells = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiLibrary; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Library; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  SymbolId m_name = BadSymbolId;
  IdentifierCollection* m_sourceFiles = nullptr;
  AnyCollection* m_cells = nullptr;
};
}  // namespace uhdm

#endif
