#ifndef UHDM_LINTER_H
#define UHDM_LINTER_H
#pragma once

#include <uhdm/uhdm_forward_decl.h>
#include <uhdm/vpi_uhdm.h>

#include <string>
#include <vector>

namespace uhdm {
class EventListener;
class Serializer;

class Linter {
 protected:
  using visited_t = AnySet;
  using callstack_t = std::vector<const Any *>;

 public:
  Linter(Serializer &serializer, EventListener *listener);
  virtual ~Linter() = default;

  void check(const Any *object);

  template <typename C>
  std::enable_if_t<std::is_base_of_v<Any, std::remove_pointer_t<typename C::value_type>>>
  check(const C &objects);

  template <typename C>
  std::enable_if_t<std::is_convertible_v<typename C::value_type, vpiHandle>>
  check(const C &handles);

 protected:
  // clang-format off
  virtual void checkAny(const Any *object, int32_t relationId, std::string_view relationName);
  virtual void checkAlias(const Alias* object, int32_t relationId, std::string_view relationName);
  virtual void checkAlways(const Always* object, int32_t relationId, std::string_view relationName);
  virtual void checkAnyPattern(const AnyPattern* object, int32_t relationId, std::string_view relationName);
  virtual void checkArrayExpr(const ArrayExpr* object, int32_t relationId, std::string_view relationName);
  virtual void checkArrayTypespec(const ArrayTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkAssert(const Assert* object, int32_t relationId, std::string_view relationName);
  virtual void checkAssignStmt(const AssignStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkAssignment(const Assignment* object, int32_t relationId, std::string_view relationName);
  virtual void checkAssume(const Assume* object, int32_t relationId, std::string_view relationName);
  virtual void checkAtomicStmt(const AtomicStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkAttribute(const Attribute* object, int32_t relationId, std::string_view relationName);
  virtual void checkBegin(const Begin* object, int32_t relationId, std::string_view relationName);
  virtual void checkBindDirective(const BindDirective* object, int32_t relationId, std::string_view relationName);
  virtual void checkBitSelect(const BitSelect* object, int32_t relationId, std::string_view relationName);
  virtual void checkBitTypespec(const BitTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkBreakStmt(const BreakStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkByteTypespec(const ByteTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkCaseItem(const CaseItem* object, int32_t relationId, std::string_view relationName);
  virtual void checkCaseProperty(const CaseProperty* object, int32_t relationId, std::string_view relationName);
  virtual void checkCasePropertyItem(const CasePropertyItem* object, int32_t relationId, std::string_view relationName);
  virtual void checkCaseStmt(const CaseStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkChandleTypespec(const ChandleTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkCheckerDecl(const CheckerDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkCheckerInst(const CheckerInst* object, int32_t relationId, std::string_view relationName);
  virtual void checkCheckerInstPort(const CheckerInstPort* object, int32_t relationId, std::string_view relationName);
  virtual void checkCheckerPort(const CheckerPort* object, int32_t relationId, std::string_view relationName);
  virtual void checkClassDefn(const ClassDefn* object, int32_t relationId, std::string_view relationName);
  virtual void checkClassObj(const ClassObj* object, int32_t relationId, std::string_view relationName);
  virtual void checkClassTypespec(const ClassTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkClause(const Clause* object, int32_t relationId, std::string_view relationName);
  virtual void checkClockedProperty(const ClockedProperty* object, int32_t relationId, std::string_view relationName);
  virtual void checkClockedSeq(const ClockedSeq* object, int32_t relationId, std::string_view relationName);
  virtual void checkClockingBlock(const ClockingBlock* object, int32_t relationId, std::string_view relationName);
  virtual void checkClockingIODecl(const ClockingIODecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkComment(const Comment* object, int32_t relationId, std::string_view relationName);
  virtual void checkConcurrentAssertions(const ConcurrentAssertions* object, int32_t relationId, std::string_view relationName);
  virtual void checkConfigDecl(const ConfigDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkConfigRule(const ConfigRule* object, int32_t relationId, std::string_view relationName);
  virtual void checkConstant(const Constant* object, int32_t relationId, std::string_view relationName);
  virtual void checkConstrForeach(const ConstrForeach* object, int32_t relationId, std::string_view relationName);
  virtual void checkConstrIf(const ConstrIf* object, int32_t relationId, std::string_view relationName);
  virtual void checkConstrIfElse(const ConstrIfElse* object, int32_t relationId, std::string_view relationName);
  virtual void checkConstraint(const Constraint* object, int32_t relationId, std::string_view relationName);
  virtual void checkConstraintExpr(const ConstraintExpr* object, int32_t relationId, std::string_view relationName);
  virtual void checkConstraintOrdering(const ConstraintOrdering* object, int32_t relationId, std::string_view relationName);
  virtual void checkContAssign(const ContAssign* object, int32_t relationId, std::string_view relationName);
  virtual void checkContAssignBit(const ContAssignBit* object, int32_t relationId, std::string_view relationName);
  virtual void checkContinueStmt(const ContinueStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkCover(const Cover* object, int32_t relationId, std::string_view relationName);
  virtual void checkCoverBin(const CoverBin* object, int32_t relationId, std::string_view relationName);
  virtual void checkCoverCross(const CoverCross* object, int32_t relationId, std::string_view relationName);
  virtual void checkCoverGroup(const CoverGroup* object, int32_t relationId, std::string_view relationName);
  virtual void checkCoverPoint(const CoverPoint* object, int32_t relationId, std::string_view relationName);
  virtual void checkCoverageOption(const CoverageOption* object, int32_t relationId, std::string_view relationName);
  virtual void checkDeassign(const Deassign* object, int32_t relationId, std::string_view relationName);
  virtual void checkDefParam(const DefParam* object, int32_t relationId, std::string_view relationName);
  virtual void checkDelayControl(const DelayControl* object, int32_t relationId, std::string_view relationName);
  virtual void checkDelayTerm(const DelayTerm* object, int32_t relationId, std::string_view relationName);
  virtual void checkDesign(const Design* object, int32_t relationId, std::string_view relationName);
  virtual void checkDisable(const Disable* object, int32_t relationId, std::string_view relationName);
  virtual void checkDisableFork(const DisableFork* object, int32_t relationId, std::string_view relationName);
  virtual void checkDisables(const Disables* object, int32_t relationId, std::string_view relationName);
  virtual void checkDistItem(const DistItem* object, int32_t relationId, std::string_view relationName);
  virtual void checkDistribution(const Distribution* object, int32_t relationId, std::string_view relationName);
  virtual void checkDoWhile(const DoWhile* object, int32_t relationId, std::string_view relationName);
  virtual void checkEnumConst(const EnumConst* object, int32_t relationId, std::string_view relationName);
  virtual void checkEnumTypespec(const EnumTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkEventControl(const EventControl* object, int32_t relationId, std::string_view relationName);
  virtual void checkEventStmt(const EventStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkEventTypespec(const EventTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkExpectStmt(const ExpectStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkExpr(const Expr* object, int32_t relationId, std::string_view relationName);
  virtual void checkExtends(const Extends* object, int32_t relationId, std::string_view relationName);
  virtual void checkFinalStmt(const FinalStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkForStmt(const ForStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkForce(const Force* object, int32_t relationId, std::string_view relationName);
  virtual void checkForeachStmt(const ForeachStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkForeverStmt(const ForeverStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkForkStmt(const ForkStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkFuncCall(const FuncCall* object, int32_t relationId, std::string_view relationName);
  virtual void checkFunction(const Function* object, int32_t relationId, std::string_view relationName);
  virtual void checkFunctionDecl(const FunctionDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkGate(const Gate* object, int32_t relationId, std::string_view relationName);
  virtual void checkGateArray(const GateArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkGenCase(const GenCase* object, int32_t relationId, std::string_view relationName);
  virtual void checkGenFor(const GenFor* object, int32_t relationId, std::string_view relationName);
  virtual void checkGenIf(const GenIf* object, int32_t relationId, std::string_view relationName);
  virtual void checkGenIfElse(const GenIfElse* object, int32_t relationId, std::string_view relationName);
  virtual void checkGenRegion(const GenRegion* object, int32_t relationId, std::string_view relationName);
  virtual void checkGenScope(const GenScope* object, int32_t relationId, std::string_view relationName);
  virtual void checkGenScopeArray(const GenScopeArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkGenStmt(const GenStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkHierPath(const HierPath* object, int32_t relationId, std::string_view relationName);
  virtual void checkIODecl(const IODecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkIdentifier(const Identifier* object, int32_t relationId, std::string_view relationName);
  virtual void checkIfElse(const IfElse* object, int32_t relationId, std::string_view relationName);
  virtual void checkIfStmt(const IfStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkImmediateAssert(const ImmediateAssert* object, int32_t relationId, std::string_view relationName);
  virtual void checkImmediateAssume(const ImmediateAssume* object, int32_t relationId, std::string_view relationName);
  virtual void checkImmediateCover(const ImmediateCover* object, int32_t relationId, std::string_view relationName);
  virtual void checkImplements(const Implements* object, int32_t relationId, std::string_view relationName);
  virtual void checkImplication(const Implication* object, int32_t relationId, std::string_view relationName);
  virtual void checkImportTypespec(const ImportTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkIncludeStmt(const IncludeStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkIndexedPartSelect(const IndexedPartSelect* object, int32_t relationId, std::string_view relationName);
  virtual void checkInitial(const Initial* object, int32_t relationId, std::string_view relationName);
  virtual void checkInstance(const Instance* object, int32_t relationId, std::string_view relationName);
  virtual void checkInstanceArray(const InstanceArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkIntTypespec(const IntTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkIntegerTypespec(const IntegerTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkInterface(const Interface* object, int32_t relationId, std::string_view relationName);
  virtual void checkInterfaceArray(const InterfaceArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkInterfaceTFDecl(const InterfaceTFDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkInterfaceTypespec(const InterfaceTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkLetDecl(const LetDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkLetExpr(const LetExpr* object, int32_t relationId, std::string_view relationName);
  virtual void checkLibrary(const Library* object, int32_t relationId, std::string_view relationName);
  virtual void checkLogicTypespec(const LogicTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkLongIntTypespec(const LongIntTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkMethodFuncCall(const MethodFuncCall* object, int32_t relationId, std::string_view relationName);
  virtual void checkMethodTaskCall(const MethodTaskCall* object, int32_t relationId, std::string_view relationName);
  virtual void checkModPath(const ModPath* object, int32_t relationId, std::string_view relationName);
  virtual void checkModport(const Modport* object, int32_t relationId, std::string_view relationName);
  virtual void checkModule(const Module* object, int32_t relationId, std::string_view relationName);
  virtual void checkModuleArray(const ModuleArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkModuleTypespec(const ModuleTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkMulticlockSequenceExpr(const MulticlockSequenceExpr* object, int32_t relationId, std::string_view relationName);
  virtual void checkNamedEvent(const NamedEvent* object, int32_t relationId, std::string_view relationName);
  virtual void checkNamedEventArray(const NamedEventArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkNet(const Net* object, int32_t relationId, std::string_view relationName);
  virtual void checkNullStmt(const NullStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkOperation(const Operation* object, int32_t relationId, std::string_view relationName);
  virtual void checkOrderedWait(const OrderedWait* object, int32_t relationId, std::string_view relationName);
  virtual void checkPackage(const Package* object, int32_t relationId, std::string_view relationName);
  virtual void checkPackageTypespec(const PackageTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkParamAssign(const ParamAssign* object, int32_t relationId, std::string_view relationName);
  virtual void checkParameter(const Parameter* object, int32_t relationId, std::string_view relationName);
  virtual void checkPartSelect(const PartSelect* object, int32_t relationId, std::string_view relationName);
  virtual void checkPathTerm(const PathTerm* object, int32_t relationId, std::string_view relationName);
  virtual void checkPort(const Port* object, int32_t relationId, std::string_view relationName);
  virtual void checkPortBit(const PortBit* object, int32_t relationId, std::string_view relationName);
  virtual void checkPorts(const Ports* object, int32_t relationId, std::string_view relationName);
  virtual void checkPreprocMacroDefinition(const PreprocMacroDefinition* object, int32_t relationId, std::string_view relationName);
  virtual void checkPreprocMacroInstance(const PreprocMacroInstance* object, int32_t relationId, std::string_view relationName);
  virtual void checkPrimTerm(const PrimTerm* object, int32_t relationId, std::string_view relationName);
  virtual void checkPrimitive(const Primitive* object, int32_t relationId, std::string_view relationName);
  virtual void checkPrimitiveArray(const PrimitiveArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkProcess(const Process* object, int32_t relationId, std::string_view relationName);
  virtual void checkProgram(const Program* object, int32_t relationId, std::string_view relationName);
  virtual void checkProgramArray(const ProgramArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkProgramTypespec(const ProgramTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkPropFormalDecl(const PropFormalDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkPropertyDecl(const PropertyDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkPropertyInst(const PropertyInst* object, int32_t relationId, std::string_view relationName);
  virtual void checkPropertySpec(const PropertySpec* object, int32_t relationId, std::string_view relationName);
  virtual void checkPropertyTypespec(const PropertyTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkRange(const Range* object, int32_t relationId, std::string_view relationName);
  virtual void checkRealTypespec(const RealTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkRefInstance(const RefInstance* object, int32_t relationId, std::string_view relationName);
  virtual void checkRefObj(const RefObj* object, int32_t relationId, std::string_view relationName);
  virtual void checkRefTypespec(const RefTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkReg(const Reg* object, int32_t relationId, std::string_view relationName);
  virtual void checkRegArray(const RegArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkRelease(const Release* object, int32_t relationId, std::string_view relationName);
  virtual void checkRepeat(const Repeat* object, int32_t relationId, std::string_view relationName);
  virtual void checkRepeatControl(const RepeatControl* object, int32_t relationId, std::string_view relationName);
  virtual void checkRestrict(const Restrict* object, int32_t relationId, std::string_view relationName);
  virtual void checkReturnStmt(const ReturnStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkScope(const Scope* object, int32_t relationId, std::string_view relationName);
  virtual void checkSelect(const Select* object, int32_t relationId, std::string_view relationName);
  virtual void checkSeqFormalDecl(const SeqFormalDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkSequenceDecl(const SequenceDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkSequenceInst(const SequenceInst* object, int32_t relationId, std::string_view relationName);
  virtual void checkSequenceTypespec(const SequenceTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkShortIntTypespec(const ShortIntTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkShortRealTypespec(const ShortRealTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkSimpleExpr(const SimpleExpr* object, int32_t relationId, std::string_view relationName);
  virtual void checkSoftDisable(const SoftDisable* object, int32_t relationId, std::string_view relationName);
  virtual void checkSourceFile(const SourceFile* object, int32_t relationId, std::string_view relationName);
  virtual void checkSpecParam(const SpecParam* object, int32_t relationId, std::string_view relationName);
  virtual void checkStringTypespec(const StringTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkStructPattern(const StructPattern* object, int32_t relationId, std::string_view relationName);
  virtual void checkStructTypespec(const StructTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkSwitchArray(const SwitchArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkSwitchTran(const SwitchTran* object, int32_t relationId, std::string_view relationName);
  virtual void checkSysFuncCall(const SysFuncCall* object, int32_t relationId, std::string_view relationName);
  virtual void checkSysTaskCall(const SysTaskCall* object, int32_t relationId, std::string_view relationName);
  virtual void checkTFCall(const TFCall* object, int32_t relationId, std::string_view relationName);
  virtual void checkTableEntry(const TableEntry* object, int32_t relationId, std::string_view relationName);
  virtual void checkTaggedPattern(const TaggedPattern* object, int32_t relationId, std::string_view relationName);
  virtual void checkTask(const Task* object, int32_t relationId, std::string_view relationName);
  virtual void checkTaskCall(const TaskCall* object, int32_t relationId, std::string_view relationName);
  virtual void checkTaskDecl(const TaskDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkTaskFunc(const TaskFunc* object, int32_t relationId, std::string_view relationName);
  virtual void checkTaskFuncDecl(const TaskFuncDecl* object, int32_t relationId, std::string_view relationName);
  virtual void checkTchk(const Tchk* object, int32_t relationId, std::string_view relationName);
  virtual void checkTchkTerm(const TchkTerm* object, int32_t relationId, std::string_view relationName);
  virtual void checkThread(const Thread* object, int32_t relationId, std::string_view relationName);
  virtual void checkTimeTypespec(const TimeTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkTypeParameter(const TypeParameter* object, int32_t relationId, std::string_view relationName);
  virtual void checkTypedefTypespec(const TypedefTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkTypespec(const Typespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkTypespecMember(const TypespecMember* object, int32_t relationId, std::string_view relationName);
  virtual void checkUdp(const Udp* object, int32_t relationId, std::string_view relationName);
  virtual void checkUdpArray(const UdpArray* object, int32_t relationId, std::string_view relationName);
  virtual void checkUdpDefn(const UdpDefn* object, int32_t relationId, std::string_view relationName);
  virtual void checkUdpDefnTypespec(const UdpDefnTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkUnionTypespec(const UnionTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkUniqueness(const Uniqueness* object, int32_t relationId, std::string_view relationName);
  virtual void checkUnsupportedExpr(const UnsupportedExpr* object, int32_t relationId, std::string_view relationName);
  virtual void checkUnsupportedStmt(const UnsupportedStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkUnsupportedTypespec(const UnsupportedTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkUserSystf(const UserSystf* object, int32_t relationId, std::string_view relationName);
  virtual void checkVarSelect(const VarSelect* object, int32_t relationId, std::string_view relationName);
  virtual void checkVariable(const Variable* object, int32_t relationId, std::string_view relationName);
  virtual void checkVoidTypespec(const VoidTypespec* object, int32_t relationId, std::string_view relationName);
  virtual void checkWaitFork(const WaitFork* object, int32_t relationId, std::string_view relationName);
  virtual void checkWaitStmt(const WaitStmt* object, int32_t relationId, std::string_view relationName);
  virtual void checkWaits(const Waits* object, int32_t relationId, std::string_view relationName);
  virtual void checkWhileStmt(const WhileStmt* object, int32_t relationId, std::string_view relationName);
  // clang-format on

  // clang-format off
  virtual void checkAliasCollection(const AliasCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkAlwaysCollection(const AlwaysCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkAnyPatternCollection(const AnyPatternCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkArrayExprCollection(const ArrayExprCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkArrayTypespecCollection(const ArrayTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkAssertCollection(const AssertCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkAssignStmtCollection(const AssignStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkAssignmentCollection(const AssignmentCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkAssumeCollection(const AssumeCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkAtomicStmtCollection(const AtomicStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkAttributeCollection(const AttributeCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkBeginCollection(const BeginCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkBindDirectiveCollection(const BindDirectiveCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkBitSelectCollection(const BitSelectCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkBitTypespecCollection(const BitTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkBreakStmtCollection(const BreakStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkByteTypespecCollection(const ByteTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCaseItemCollection(const CaseItemCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCasePropertyCollection(const CasePropertyCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCasePropertyItemCollection(const CasePropertyItemCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCaseStmtCollection(const CaseStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkChandleTypespecCollection(const ChandleTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCheckerDeclCollection(const CheckerDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCheckerInstCollection(const CheckerInstCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCheckerInstPortCollection(const CheckerInstPortCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCheckerPortCollection(const CheckerPortCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkClassDefnCollection(const ClassDefnCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkClassObjCollection(const ClassObjCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkClassTypespecCollection(const ClassTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkClauseCollection(const ClauseCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkClockedPropertyCollection(const ClockedPropertyCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkClockedSeqCollection(const ClockedSeqCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkClockingBlockCollection(const ClockingBlockCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkClockingIODeclCollection(const ClockingIODeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCommentCollection(const CommentCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConcurrentAssertionsCollection(const ConcurrentAssertionsCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConfigDeclCollection(const ConfigDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConfigRuleCollection(const ConfigRuleCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConstantCollection(const ConstantCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConstrForeachCollection(const ConstrForeachCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConstrIfCollection(const ConstrIfCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConstrIfElseCollection(const ConstrIfElseCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConstraintCollection(const ConstraintCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConstraintExprCollection(const ConstraintExprCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkConstraintOrderingCollection(const ConstraintOrderingCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkContAssignBitCollection(const ContAssignBitCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkContAssignCollection(const ContAssignCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkContinueStmtCollection(const ContinueStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCoverBinCollection(const CoverBinCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCoverCollection(const CoverCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCoverCrossCollection(const CoverCrossCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCoverGroupCollection(const CoverGroupCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCoverPointCollection(const CoverPointCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkCoverageOptionCollection(const CoverageOptionCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDeassignCollection(const DeassignCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDefParamCollection(const DefParamCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDelayControlCollection(const DelayControlCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDelayTermCollection(const DelayTermCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDesignCollection(const DesignCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDisableCollection(const DisableCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDisableForkCollection(const DisableForkCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDisablesCollection(const DisablesCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDistItemCollection(const DistItemCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDistributionCollection(const DistributionCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkDoWhileCollection(const DoWhileCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkEnumConstCollection(const EnumConstCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkEnumTypespecCollection(const EnumTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkEventControlCollection(const EventControlCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkEventStmtCollection(const EventStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkEventTypespecCollection(const EventTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkExpectStmtCollection(const ExpectStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkExprCollection(const ExprCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkExtendsCollection(const ExtendsCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkFinalStmtCollection(const FinalStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkForStmtCollection(const ForStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkForceCollection(const ForceCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkForeachStmtCollection(const ForeachStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkForeverStmtCollection(const ForeverStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkForkStmtCollection(const ForkStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkFuncCallCollection(const FuncCallCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkFunctionCollection(const FunctionCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkFunctionDeclCollection(const FunctionDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGateArrayCollection(const GateArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGateCollection(const GateCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGenCaseCollection(const GenCaseCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGenForCollection(const GenForCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGenIfCollection(const GenIfCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGenIfElseCollection(const GenIfElseCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGenRegionCollection(const GenRegionCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGenScopeArrayCollection(const GenScopeArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGenScopeCollection(const GenScopeCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkGenStmtCollection(const GenStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkHierPathCollection(const HierPathCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkIODeclCollection(const IODeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkIdentifierCollection(const IdentifierCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkIfElseCollection(const IfElseCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkIfStmtCollection(const IfStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkImmediateAssertCollection(const ImmediateAssertCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkImmediateAssumeCollection(const ImmediateAssumeCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkImmediateCoverCollection(const ImmediateCoverCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkImplementsCollection(const ImplementsCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkImplicationCollection(const ImplicationCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkImportTypespecCollection(const ImportTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkIncludeStmtCollection(const IncludeStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkIndexedPartSelectCollection(const IndexedPartSelectCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkInitialCollection(const InitialCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkInstanceArrayCollection(const InstanceArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkInstanceCollection(const InstanceCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkIntTypespecCollection(const IntTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkIntegerTypespecCollection(const IntegerTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkInterfaceArrayCollection(const InterfaceArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkInterfaceCollection(const InterfaceCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkInterfaceTFDeclCollection(const InterfaceTFDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkInterfaceTypespecCollection(const InterfaceTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkLetDeclCollection(const LetDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkLetExprCollection(const LetExprCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkLibraryCollection(const LibraryCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkLogicTypespecCollection(const LogicTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkLongIntTypespecCollection(const LongIntTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkMethodFuncCallCollection(const MethodFuncCallCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkMethodTaskCallCollection(const MethodTaskCallCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkModPathCollection(const ModPathCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkModportCollection(const ModportCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkModuleArrayCollection(const ModuleArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkModuleCollection(const ModuleCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkModuleTypespecCollection(const ModuleTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkMulticlockSequenceExprCollection(const MulticlockSequenceExprCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkNamedEventArrayCollection(const NamedEventArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkNamedEventCollection(const NamedEventCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkNetCollection(const NetCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkNullStmtCollection(const NullStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkOperationCollection(const OperationCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkOrderedWaitCollection(const OrderedWaitCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPackageCollection(const PackageCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPackageTypespecCollection(const PackageTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkParamAssignCollection(const ParamAssignCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkParameterCollection(const ParameterCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPartSelectCollection(const PartSelectCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPathTermCollection(const PathTermCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPortBitCollection(const PortBitCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPortCollection(const PortCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPortsCollection(const PortsCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPreprocMacroDefinitionCollection(const PreprocMacroDefinitionCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPreprocMacroInstanceCollection(const PreprocMacroInstanceCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPrimTermCollection(const PrimTermCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPrimitiveArrayCollection(const PrimitiveArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPrimitiveCollection(const PrimitiveCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkProcessCollection(const ProcessCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkProgramArrayCollection(const ProgramArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkProgramCollection(const ProgramCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkProgramTypespecCollection(const ProgramTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPropFormalDeclCollection(const PropFormalDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPropertyDeclCollection(const PropertyDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPropertyInstCollection(const PropertyInstCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPropertySpecCollection(const PropertySpecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkPropertyTypespecCollection(const PropertyTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRangeCollection(const RangeCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRealTypespecCollection(const RealTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRefInstanceCollection(const RefInstanceCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRefObjCollection(const RefObjCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRefTypespecCollection(const RefTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRegArrayCollection(const RegArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRegCollection(const RegCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkReleaseCollection(const ReleaseCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRepeatCollection(const RepeatCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRepeatControlCollection(const RepeatControlCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkRestrictCollection(const RestrictCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkReturnStmtCollection(const ReturnStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkScopeCollection(const ScopeCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSelectCollection(const SelectCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSeqFormalDeclCollection(const SeqFormalDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSequenceDeclCollection(const SequenceDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSequenceInstCollection(const SequenceInstCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSequenceTypespecCollection(const SequenceTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkShortIntTypespecCollection(const ShortIntTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkShortRealTypespecCollection(const ShortRealTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSimpleExprCollection(const SimpleExprCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSoftDisableCollection(const SoftDisableCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSourceFileCollection(const SourceFileCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSpecParamCollection(const SpecParamCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkStringTypespecCollection(const StringTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkStructPatternCollection(const StructPatternCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkStructTypespecCollection(const StructTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSwitchArrayCollection(const SwitchArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSwitchTranCollection(const SwitchTranCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSysFuncCallCollection(const SysFuncCallCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkSysTaskCallCollection(const SysTaskCallCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTFCallCollection(const TFCallCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTableEntryCollection(const TableEntryCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTaggedPatternCollection(const TaggedPatternCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTaskCallCollection(const TaskCallCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTaskCollection(const TaskCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTaskDeclCollection(const TaskDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTaskFuncCollection(const TaskFuncCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTaskFuncDeclCollection(const TaskFuncDeclCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTchkCollection(const TchkCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTchkTermCollection(const TchkTermCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkThreadCollection(const ThreadCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTimeTypespecCollection(const TimeTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTypeParameterCollection(const TypeParameterCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTypedefTypespecCollection(const TypedefTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTypespecCollection(const TypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkTypespecMemberCollection(const TypespecMemberCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUdpArrayCollection(const UdpArrayCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUdpCollection(const UdpCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUdpDefnCollection(const UdpDefnCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUdpDefnTypespecCollection(const UdpDefnTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUnionTypespecCollection(const UnionTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUniquenessCollection(const UniquenessCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUnsupportedExprCollection(const UnsupportedExprCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUnsupportedStmtCollection(const UnsupportedStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUnsupportedTypespecCollection(const UnsupportedTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkUserSystfCollection(const UserSystfCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkVarSelectCollection(const VarSelectCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkVariableCollection(const VariableCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkVoidTypespecCollection(const VoidTypespecCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkWaitForkCollection(const WaitForkCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkWaitStmtCollection(const WaitStmtCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkWaitsCollection(const WaitsCollection &collection, int32_t relationId, std::string_view relationName);
  virtual void checkWhileStmtCollection(const WhileStmtCollection &collection, int32_t relationId, std::string_view relationName);
  // clang-format on

 private:
  template <typename C,
            typename = typename std::enable_if_t<std::is_base_of_v<Any, std::remove_pointer_t<typename C::value_type>>>>
  void reportDuplicates(const C &collection, int32_t relationId, std::string_view relationName) const;

  template <typename C,
            typename = typename std::enable_if_t<std::is_base_of_v<Any, std::remove_pointer_t<typename C::value_type>>>>
  void check(const C &collection, int32_t relationId, std::string_view relationName) const;

  template <typename C,
            typename = typename std::enable_if_t<std::is_base_of_v<Any, std::remove_pointer_t<typename C::value_type>>>>
  void check(const C &collection, int32_t relationId, std::string_view relationName);

  void check(const Any *object, int32_t relationId, std::string_view relationName);

  // Private helper called from checkModule_; not a per-type hook.
  void checkMultiContAssign_(const ContAssignCollection *assigns);

  // clang-format off
  // Generated private lint hooks for all concrete object types.
  // Key types have hand-written bodies in Linter.cpp; all others are empty stubs.
  void checkAlias_(const Alias *object);
  void checkAlways_(const Always *object);
  void checkAnyPattern_(const AnyPattern *object);
  void checkArrayExpr_(const ArrayExpr *object);
  void checkArrayTypespec_(const ArrayTypespec *object);
  void checkAssert_(const Assert *object);
  void checkAssignStmt_(const AssignStmt *object);
  void checkAssignment_(const Assignment *object);
  void checkAssume_(const Assume *object);
  void checkAttribute_(const Attribute *object);
  void checkBegin_(const Begin *object);
  void checkBindDirective_(const BindDirective *object);
  void checkBitSelect_(const BitSelect *object);
  void checkBitTypespec_(const BitTypespec *object);
  void checkBreakStmt_(const BreakStmt *object);
  void checkByteTypespec_(const ByteTypespec *object);
  void checkCaseItem_(const CaseItem *object);
  void checkCasePropertyItem_(const CasePropertyItem *object);
  void checkCaseProperty_(const CaseProperty *object);
  void checkCaseStmt_(const CaseStmt *object);
  void checkChandleTypespec_(const ChandleTypespec *object);
  void checkCheckerDecl_(const CheckerDecl *object);
  void checkCheckerInstPort_(const CheckerInstPort *object);
  void checkCheckerInst_(const CheckerInst *object);
  void checkCheckerPort_(const CheckerPort *object);
  void checkClassDefn_(const ClassDefn *object);
  void checkClassObj_(const ClassObj *object);
  void checkClassTypespec_(const ClassTypespec *object);
  void checkClause_(const Clause *object);
  void checkClockedProperty_(const ClockedProperty *object);
  void checkClockedSeq_(const ClockedSeq *object);
  void checkClockingBlock_(const ClockingBlock *object);
  void checkClockingIODecl_(const ClockingIODecl *object);
  void checkComment_(const Comment *object);
  void checkConfigDecl_(const ConfigDecl *object);
  void checkConfigRule_(const ConfigRule *object);
  void checkConstant_(const Constant *object);
  void checkConstrForeach_(const ConstrForeach *object);
  void checkConstrIfElse_(const ConstrIfElse *object);
  void checkConstrIf_(const ConstrIf *object);
  void checkConstraintOrdering_(const ConstraintOrdering *object);
  void checkConstraint_(const Constraint *object);
  void checkContAssignBit_(const ContAssignBit *object);
  void checkContAssign_(const ContAssign *object);
  void checkContinueStmt_(const ContinueStmt *object);
  void checkCoverBin_(const CoverBin *object);
  void checkCoverCross_(const CoverCross *object);
  void checkCoverGroup_(const CoverGroup *object);
  void checkCoverPoint_(const CoverPoint *object);
  void checkCover_(const Cover *object);
  void checkCoverageOption_(const CoverageOption *object);
  void checkDeassign_(const Deassign *object);
  void checkDefParam_(const DefParam *object);
  void checkDelayControl_(const DelayControl *object);
  void checkDelayTerm_(const DelayTerm *object);
  void checkDesign_(const Design *object);
  void checkDisableFork_(const DisableFork *object);
  void checkDisable_(const Disable *object);
  void checkDistItem_(const DistItem *object);
  void checkDistribution_(const Distribution *object);
  void checkDoWhile_(const DoWhile *object);
  void checkEnumConst_(const EnumConst *object);
  void checkEnumTypespec_(const EnumTypespec *object);
  void checkEventControl_(const EventControl *object);
  void checkEventStmt_(const EventStmt *object);
  void checkEventTypespec_(const EventTypespec *object);
  void checkExpectStmt_(const ExpectStmt *object);
  void checkExtends_(const Extends *object);
  void checkFinalStmt_(const FinalStmt *object);
  void checkForStmt_(const ForStmt *object);
  void checkForce_(const Force *object);
  void checkForeachStmt_(const ForeachStmt *object);
  void checkForeverStmt_(const ForeverStmt *object);
  void checkForkStmt_(const ForkStmt *object);
  void checkFuncCall_(const FuncCall *object);
  void checkFunctionDecl_(const FunctionDecl *object);
  void checkFunction_(const Function *object);
  void checkGateArray_(const GateArray *object);
  void checkGate_(const Gate *object);
  void checkGenCase_(const GenCase *object);
  void checkGenFor_(const GenFor *object);
  void checkGenIfElse_(const GenIfElse *object);
  void checkGenIf_(const GenIf *object);
  void checkGenRegion_(const GenRegion *object);
  void checkGenScopeArray_(const GenScopeArray *object);
  void checkHierPath_(const HierPath *object);
  void checkIODecl_(const IODecl *object);
  void checkIdentifier_(const Identifier *object);
  void checkIfElse_(const IfElse *object);
  void checkIfStmt_(const IfStmt *object);
  void checkImmediateAssert_(const ImmediateAssert *object);
  void checkImmediateAssume_(const ImmediateAssume *object);
  void checkImmediateCover_(const ImmediateCover *object);
  void checkImplements_(const Implements *object);
  void checkImplication_(const Implication *object);
  void checkImportTypespec_(const ImportTypespec *object);
  void checkIncludeStmt_(const IncludeStmt *object);
  void checkIndexedPartSelect_(const IndexedPartSelect *object);
  void checkInitial_(const Initial *object);
  void checkIntTypespec_(const IntTypespec *object);
  void checkIntegerTypespec_(const IntegerTypespec *object);
  void checkInterfaceArray_(const InterfaceArray *object);
  void checkInterfaceTFDecl_(const InterfaceTFDecl *object);
  void checkInterfaceTypespec_(const InterfaceTypespec *object);
  void checkInterface_(const Interface *object);
  void checkLetDecl_(const LetDecl *object);
  void checkLetExpr_(const LetExpr *object);
  void checkLibrary_(const Library *object);
  void checkLogicTypespec_(const LogicTypespec *object);
  void checkLongIntTypespec_(const LongIntTypespec *object);
  void checkMethodFuncCall_(const MethodFuncCall *object);
  void checkMethodTaskCall_(const MethodTaskCall *object);
  void checkModPath_(const ModPath *object);
  void checkModport_(const Modport *object);
  void checkModuleArray_(const ModuleArray *object);
  void checkModuleTypespec_(const ModuleTypespec *object);
  void checkModule_(const Module *object);
  void checkMulticlockSequenceExpr_(const MulticlockSequenceExpr *object);
  void checkNamedEventArray_(const NamedEventArray *object);
  void checkNamedEvent_(const NamedEvent *object);
  void checkNet_(const Net *object);
  void checkNullStmt_(const NullStmt *object);
  void checkOperation_(const Operation *object);
  void checkOrderedWait_(const OrderedWait *object);
  void checkPackageTypespec_(const PackageTypespec *object);
  void checkPackage_(const Package *object);
  void checkParamAssign_(const ParamAssign *object);
  void checkParameter_(const Parameter *object);
  void checkPartSelect_(const PartSelect *object);
  void checkPathTerm_(const PathTerm *object);
  void checkPortBit_(const PortBit *object);
  void checkPort_(const Port *object);
  void checkPreprocMacroDefinition_(const PreprocMacroDefinition *object);
  void checkPreprocMacroInstance_(const PreprocMacroInstance *object);
  void checkPrimTerm_(const PrimTerm *object);
  void checkProgramArray_(const ProgramArray *object);
  void checkProgramTypespec_(const ProgramTypespec *object);
  void checkProgram_(const Program *object);
  void checkPropFormalDecl_(const PropFormalDecl *object);
  void checkPropertyDecl_(const PropertyDecl *object);
  void checkPropertyInst_(const PropertyInst *object);
  void checkPropertySpec_(const PropertySpec *object);
  void checkPropertyTypespec_(const PropertyTypespec *object);
  void checkRange_(const Range *object);
  void checkRealTypespec_(const RealTypespec *object);
  void checkRefInstance_(const RefInstance *object);
  void checkRefObj_(const RefObj *object);
  void checkRefTypespec_(const RefTypespec *object);
  void checkRegArray_(const RegArray *object);
  void checkReg_(const Reg *object);
  void checkRelease_(const Release *object);
  void checkRepeatControl_(const RepeatControl *object);
  void checkRepeat_(const Repeat *object);
  void checkRestrict_(const Restrict *object);
  void checkReturnStmt_(const ReturnStmt *object);
  void checkSeqFormalDecl_(const SeqFormalDecl *object);
  void checkSequenceDecl_(const SequenceDecl *object);
  void checkSequenceInst_(const SequenceInst *object);
  void checkSequenceTypespec_(const SequenceTypespec *object);
  void checkShortIntTypespec_(const ShortIntTypespec *object);
  void checkShortRealTypespec_(const ShortRealTypespec *object);
  void checkSoftDisable_(const SoftDisable *object);
  void checkSourceFile_(const SourceFile *object);
  void checkSpecParam_(const SpecParam *object);
  void checkStringTypespec_(const StringTypespec *object);
  void checkStructPattern_(const StructPattern *object);
  void checkStructTypespec_(const StructTypespec *object);
  void checkSwitchArray_(const SwitchArray *object);
  void checkSwitchTran_(const SwitchTran *object);
  void checkSysFuncCall_(const SysFuncCall *object);
  void checkSysTaskCall_(const SysTaskCall *object);
  void checkTableEntry_(const TableEntry *object);
  void checkTaggedPattern_(const TaggedPattern *object);
  void checkTaskCall_(const TaskCall *object);
  void checkTaskDecl_(const TaskDecl *object);
  void checkTask_(const Task *object);
  void checkTchkTerm_(const TchkTerm *object);
  void checkTchk_(const Tchk *object);
  void checkThread_(const Thread *object);
  void checkTimeTypespec_(const TimeTypespec *object);
  void checkTypeParameter_(const TypeParameter *object);
  void checkTypedefTypespec_(const TypedefTypespec *object);
  void checkTypespecMember_(const TypespecMember *object);
  void checkUdpArray_(const UdpArray *object);
  void checkUdpDefnTypespec_(const UdpDefnTypespec *object);
  void checkUdpDefn_(const UdpDefn *object);
  void checkUdp_(const Udp *object);
  void checkUnionTypespec_(const UnionTypespec *object);
  void checkUniqueness_(const Uniqueness *object);
  void checkUnsupportedExpr_(const UnsupportedExpr *object);
  void checkUnsupportedStmt_(const UnsupportedStmt *object);
  void checkUnsupportedTypespec_(const UnsupportedTypespec *object);
  void checkUserSystf_(const UserSystf *object);
  void checkVarSelect_(const VarSelect *object);
  void checkVariable_(const Variable *object);
  void checkVoidTypespec_(const VoidTypespec *object);
  void checkWaitFork_(const WaitFork *object);
  void checkWaitStmt_(const WaitStmt *object);
  void checkWhileStmt_(const WhileStmt *object);

  // Generated private lint hooks for all collection types.
  void checkAliasCollection_(const AliasCollection &collection);
  void checkAlwaysCollection_(const AlwaysCollection &collection);
  void checkAnyPatternCollection_(const AnyPatternCollection &collection);
  void checkArrayExprCollection_(const ArrayExprCollection &collection);
  void checkArrayTypespecCollection_(const ArrayTypespecCollection &collection);
  void checkAssertCollection_(const AssertCollection &collection);
  void checkAssignStmtCollection_(const AssignStmtCollection &collection);
  void checkAssignmentCollection_(const AssignmentCollection &collection);
  void checkAssumeCollection_(const AssumeCollection &collection);
  void checkAtomicStmtCollection_(const AtomicStmtCollection &collection);
  void checkAttributeCollection_(const AttributeCollection &collection);
  void checkBeginCollection_(const BeginCollection &collection);
  void checkBindDirectiveCollection_(const BindDirectiveCollection &collection);
  void checkBitSelectCollection_(const BitSelectCollection &collection);
  void checkBitTypespecCollection_(const BitTypespecCollection &collection);
  void checkBreakStmtCollection_(const BreakStmtCollection &collection);
  void checkByteTypespecCollection_(const ByteTypespecCollection &collection);
  void checkCaseItemCollection_(const CaseItemCollection &collection);
  void checkCasePropertyCollection_(const CasePropertyCollection &collection);
  void checkCasePropertyItemCollection_(const CasePropertyItemCollection &collection);
  void checkCaseStmtCollection_(const CaseStmtCollection &collection);
  void checkChandleTypespecCollection_(const ChandleTypespecCollection &collection);
  void checkCheckerDeclCollection_(const CheckerDeclCollection &collection);
  void checkCheckerInstCollection_(const CheckerInstCollection &collection);
  void checkCheckerInstPortCollection_(const CheckerInstPortCollection &collection);
  void checkCheckerPortCollection_(const CheckerPortCollection &collection);
  void checkClassDefnCollection_(const ClassDefnCollection &collection);
  void checkClassObjCollection_(const ClassObjCollection &collection);
  void checkClassTypespecCollection_(const ClassTypespecCollection &collection);
  void checkClauseCollection_(const ClauseCollection &collection);
  void checkClockedPropertyCollection_(const ClockedPropertyCollection &collection);
  void checkClockedSeqCollection_(const ClockedSeqCollection &collection);
  void checkClockingBlockCollection_(const ClockingBlockCollection &collection);
  void checkClockingIODeclCollection_(const ClockingIODeclCollection &collection);
  void checkCommentCollection_(const CommentCollection &collection);
  void checkConcurrentAssertionsCollection_(const ConcurrentAssertionsCollection &collection);
  void checkConfigDeclCollection_(const ConfigDeclCollection &collection);
  void checkConfigRuleCollection_(const ConfigRuleCollection &collection);
  void checkConstantCollection_(const ConstantCollection &collection);
  void checkConstrForeachCollection_(const ConstrForeachCollection &collection);
  void checkConstrIfCollection_(const ConstrIfCollection &collection);
  void checkConstrIfElseCollection_(const ConstrIfElseCollection &collection);
  void checkConstraintCollection_(const ConstraintCollection &collection);
  void checkConstraintExprCollection_(const ConstraintExprCollection &collection);
  void checkConstraintOrderingCollection_(const ConstraintOrderingCollection &collection);
  void checkContAssignBitCollection_(const ContAssignBitCollection &collection);
  void checkContAssignCollection_(const ContAssignCollection &collection);
  void checkContinueStmtCollection_(const ContinueStmtCollection &collection);
  void checkCoverBinCollection_(const CoverBinCollection &collection);
  void checkCoverCollection_(const CoverCollection &collection);
  void checkCoverCrossCollection_(const CoverCrossCollection &collection);
  void checkCoverGroupCollection_(const CoverGroupCollection &collection);
  void checkCoverPointCollection_(const CoverPointCollection &collection);
  void checkCoverageOptionCollection_(const CoverageOptionCollection &collection);
  void checkDeassignCollection_(const DeassignCollection &collection);
  void checkDefParamCollection_(const DefParamCollection &collection);
  void checkDelayControlCollection_(const DelayControlCollection &collection);
  void checkDelayTermCollection_(const DelayTermCollection &collection);
  void checkDesignCollection_(const DesignCollection &collection);
  void checkDisableCollection_(const DisableCollection &collection);
  void checkDisableForkCollection_(const DisableForkCollection &collection);
  void checkDisablesCollection_(const DisablesCollection &collection);
  void checkDistItemCollection_(const DistItemCollection &collection);
  void checkDistributionCollection_(const DistributionCollection &collection);
  void checkDoWhileCollection_(const DoWhileCollection &collection);
  void checkEnumConstCollection_(const EnumConstCollection &collection);
  void checkEnumTypespecCollection_(const EnumTypespecCollection &collection);
  void checkEventControlCollection_(const EventControlCollection &collection);
  void checkEventStmtCollection_(const EventStmtCollection &collection);
  void checkEventTypespecCollection_(const EventTypespecCollection &collection);
  void checkExpectStmtCollection_(const ExpectStmtCollection &collection);
  void checkExprCollection_(const ExprCollection &collection);
  void checkExtendsCollection_(const ExtendsCollection &collection);
  void checkFinalStmtCollection_(const FinalStmtCollection &collection);
  void checkForStmtCollection_(const ForStmtCollection &collection);
  void checkForceCollection_(const ForceCollection &collection);
  void checkForeachStmtCollection_(const ForeachStmtCollection &collection);
  void checkForeverStmtCollection_(const ForeverStmtCollection &collection);
  void checkForkStmtCollection_(const ForkStmtCollection &collection);
  void checkFuncCallCollection_(const FuncCallCollection &collection);
  void checkFunctionCollection_(const FunctionCollection &collection);
  void checkFunctionDeclCollection_(const FunctionDeclCollection &collection);
  void checkGateArrayCollection_(const GateArrayCollection &collection);
  void checkGateCollection_(const GateCollection &collection);
  void checkGenCaseCollection_(const GenCaseCollection &collection);
  void checkGenForCollection_(const GenForCollection &collection);
  void checkGenIfCollection_(const GenIfCollection &collection);
  void checkGenIfElseCollection_(const GenIfElseCollection &collection);
  void checkGenRegionCollection_(const GenRegionCollection &collection);
  void checkGenScopeArrayCollection_(const GenScopeArrayCollection &collection);
  void checkGenScopeCollection_(const GenScopeCollection &collection);
  void checkGenStmtCollection_(const GenStmtCollection &collection);
  void checkHierPathCollection_(const HierPathCollection &collection);
  void checkIODeclCollection_(const IODeclCollection &collection);
  void checkIdentifierCollection_(const IdentifierCollection &collection);
  void checkIfElseCollection_(const IfElseCollection &collection);
  void checkIfStmtCollection_(const IfStmtCollection &collection);
  void checkImmediateAssertCollection_(const ImmediateAssertCollection &collection);
  void checkImmediateAssumeCollection_(const ImmediateAssumeCollection &collection);
  void checkImmediateCoverCollection_(const ImmediateCoverCollection &collection);
  void checkImplementsCollection_(const ImplementsCollection &collection);
  void checkImplicationCollection_(const ImplicationCollection &collection);
  void checkImportTypespecCollection_(const ImportTypespecCollection &collection);
  void checkIncludeStmtCollection_(const IncludeStmtCollection &collection);
  void checkIndexedPartSelectCollection_(const IndexedPartSelectCollection &collection);
  void checkInitialCollection_(const InitialCollection &collection);
  void checkInstanceArrayCollection_(const InstanceArrayCollection &collection);
  void checkInstanceCollection_(const InstanceCollection &collection);
  void checkIntTypespecCollection_(const IntTypespecCollection &collection);
  void checkIntegerTypespecCollection_(const IntegerTypespecCollection &collection);
  void checkInterfaceArrayCollection_(const InterfaceArrayCollection &collection);
  void checkInterfaceCollection_(const InterfaceCollection &collection);
  void checkInterfaceTFDeclCollection_(const InterfaceTFDeclCollection &collection);
  void checkInterfaceTypespecCollection_(const InterfaceTypespecCollection &collection);
  void checkLetDeclCollection_(const LetDeclCollection &collection);
  void checkLetExprCollection_(const LetExprCollection &collection);
  void checkLibraryCollection_(const LibraryCollection &collection);
  void checkLogicTypespecCollection_(const LogicTypespecCollection &collection);
  void checkLongIntTypespecCollection_(const LongIntTypespecCollection &collection);
  void checkMethodFuncCallCollection_(const MethodFuncCallCollection &collection);
  void checkMethodTaskCallCollection_(const MethodTaskCallCollection &collection);
  void checkModPathCollection_(const ModPathCollection &collection);
  void checkModportCollection_(const ModportCollection &collection);
  void checkModuleArrayCollection_(const ModuleArrayCollection &collection);
  void checkModuleCollection_(const ModuleCollection &collection);
  void checkModuleTypespecCollection_(const ModuleTypespecCollection &collection);
  void checkMulticlockSequenceExprCollection_(const MulticlockSequenceExprCollection &collection);
  void checkNamedEventArrayCollection_(const NamedEventArrayCollection &collection);
  void checkNamedEventCollection_(const NamedEventCollection &collection);
  void checkNetCollection_(const NetCollection &collection);
  void checkNullStmtCollection_(const NullStmtCollection &collection);
  void checkOperationCollection_(const OperationCollection &collection);
  void checkOrderedWaitCollection_(const OrderedWaitCollection &collection);
  void checkPackageCollection_(const PackageCollection &collection);
  void checkPackageTypespecCollection_(const PackageTypespecCollection &collection);
  void checkParamAssignCollection_(const ParamAssignCollection &collection);
  void checkParameterCollection_(const ParameterCollection &collection);
  void checkPartSelectCollection_(const PartSelectCollection &collection);
  void checkPathTermCollection_(const PathTermCollection &collection);
  void checkPortBitCollection_(const PortBitCollection &collection);
  void checkPortCollection_(const PortCollection &collection);
  void checkPortsCollection_(const PortsCollection &collection);
  void checkPreprocMacroDefinitionCollection_(const PreprocMacroDefinitionCollection &collection);
  void checkPreprocMacroInstanceCollection_(const PreprocMacroInstanceCollection &collection);
  void checkPrimTermCollection_(const PrimTermCollection &collection);
  void checkPrimitiveArrayCollection_(const PrimitiveArrayCollection &collection);
  void checkPrimitiveCollection_(const PrimitiveCollection &collection);
  void checkProcessCollection_(const ProcessCollection &collection);
  void checkProgramArrayCollection_(const ProgramArrayCollection &collection);
  void checkProgramCollection_(const ProgramCollection &collection);
  void checkProgramTypespecCollection_(const ProgramTypespecCollection &collection);
  void checkPropFormalDeclCollection_(const PropFormalDeclCollection &collection);
  void checkPropertyDeclCollection_(const PropertyDeclCollection &collection);
  void checkPropertyInstCollection_(const PropertyInstCollection &collection);
  void checkPropertySpecCollection_(const PropertySpecCollection &collection);
  void checkPropertyTypespecCollection_(const PropertyTypespecCollection &collection);
  void checkRangeCollection_(const RangeCollection &collection);
  void checkRealTypespecCollection_(const RealTypespecCollection &collection);
  void checkRefInstanceCollection_(const RefInstanceCollection &collection);
  void checkRefObjCollection_(const RefObjCollection &collection);
  void checkRefTypespecCollection_(const RefTypespecCollection &collection);
  void checkRegArrayCollection_(const RegArrayCollection &collection);
  void checkRegCollection_(const RegCollection &collection);
  void checkReleaseCollection_(const ReleaseCollection &collection);
  void checkRepeatCollection_(const RepeatCollection &collection);
  void checkRepeatControlCollection_(const RepeatControlCollection &collection);
  void checkRestrictCollection_(const RestrictCollection &collection);
  void checkReturnStmtCollection_(const ReturnStmtCollection &collection);
  void checkScopeCollection_(const ScopeCollection &collection);
  void checkSelectCollection_(const SelectCollection &collection);
  void checkSeqFormalDeclCollection_(const SeqFormalDeclCollection &collection);
  void checkSequenceDeclCollection_(const SequenceDeclCollection &collection);
  void checkSequenceInstCollection_(const SequenceInstCollection &collection);
  void checkSequenceTypespecCollection_(const SequenceTypespecCollection &collection);
  void checkShortIntTypespecCollection_(const ShortIntTypespecCollection &collection);
  void checkShortRealTypespecCollection_(const ShortRealTypespecCollection &collection);
  void checkSimpleExprCollection_(const SimpleExprCollection &collection);
  void checkSoftDisableCollection_(const SoftDisableCollection &collection);
  void checkSourceFileCollection_(const SourceFileCollection &collection);
  void checkSpecParamCollection_(const SpecParamCollection &collection);
  void checkStringTypespecCollection_(const StringTypespecCollection &collection);
  void checkStructPatternCollection_(const StructPatternCollection &collection);
  void checkStructTypespecCollection_(const StructTypespecCollection &collection);
  void checkSwitchArrayCollection_(const SwitchArrayCollection &collection);
  void checkSwitchTranCollection_(const SwitchTranCollection &collection);
  void checkSysFuncCallCollection_(const SysFuncCallCollection &collection);
  void checkSysTaskCallCollection_(const SysTaskCallCollection &collection);
  void checkTFCallCollection_(const TFCallCollection &collection);
  void checkTableEntryCollection_(const TableEntryCollection &collection);
  void checkTaggedPatternCollection_(const TaggedPatternCollection &collection);
  void checkTaskCallCollection_(const TaskCallCollection &collection);
  void checkTaskCollection_(const TaskCollection &collection);
  void checkTaskDeclCollection_(const TaskDeclCollection &collection);
  void checkTaskFuncCollection_(const TaskFuncCollection &collection);
  void checkTaskFuncDeclCollection_(const TaskFuncDeclCollection &collection);
  void checkTchkCollection_(const TchkCollection &collection);
  void checkTchkTermCollection_(const TchkTermCollection &collection);
  void checkThreadCollection_(const ThreadCollection &collection);
  void checkTimeTypespecCollection_(const TimeTypespecCollection &collection);
  void checkTypeParameterCollection_(const TypeParameterCollection &collection);
  void checkTypedefTypespecCollection_(const TypedefTypespecCollection &collection);
  void checkTypespecCollection_(const TypespecCollection &collection);
  void checkTypespecMemberCollection_(const TypespecMemberCollection &collection);
  void checkUdpArrayCollection_(const UdpArrayCollection &collection);
  void checkUdpCollection_(const UdpCollection &collection);
  void checkUdpDefnCollection_(const UdpDefnCollection &collection);
  void checkUdpDefnTypespecCollection_(const UdpDefnTypespecCollection &collection);
  void checkUnionTypespecCollection_(const UnionTypespecCollection &collection);
  void checkUniquenessCollection_(const UniquenessCollection &collection);
  void checkUnsupportedExprCollection_(const UnsupportedExprCollection &collection);
  void checkUnsupportedStmtCollection_(const UnsupportedStmtCollection &collection);
  void checkUnsupportedTypespecCollection_(const UnsupportedTypespecCollection &collection);
  void checkUserSystfCollection_(const UserSystfCollection &collection);
  void checkVarSelectCollection_(const VarSelectCollection &collection);
  void checkVariableCollection_(const VariableCollection &collection);
  void checkVoidTypespecCollection_(const VoidTypespecCollection &collection);
  void checkWaitForkCollection_(const WaitForkCollection &collection);
  void checkWaitStmtCollection_(const WaitStmtCollection &collection);
  void checkWaitsCollection_(const WaitsCollection &collection);
  void checkWhileStmtCollection_(const WhileStmtCollection &collection);
  // clang-format on

 protected:
  Serializer &m_serializer;
  EventListener *const m_eventListener = nullptr;
  visited_t m_visited;
  callstack_t m_callstack;
  bool m_abortRequested = false;
};

inline void Linter::check(const Any *object) { check(object, 0, ""); }

template <typename C>
inline std::enable_if_t<std::is_base_of_v<Any, std::remove_pointer_t<typename C::value_type>>>
Linter::check(const C &objects) {
  for (const Any *object : objects) {
    check(object, 0, "");
  }
}

template <typename C>
inline std::enable_if_t<std::is_convertible_v<typename C::value_type, vpiHandle>>
Linter::check(const C &handles) {
  for (const vpiHandle &h : handles) {
    check((const Any *)((const UhdmHandle *)h)->object, 0, "");
  }
}
}  // namespace uhdm

#endif  // UHDM_LINTER_H
