/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   modport.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_MODPORT_H
#define UHDM_MODPORT_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class Modport final : public Any {
  UHDM_IMPLEMENT_RTTI(Modport, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Modport;

  explicit Modport(Serializer *serializer) : basetype_t(serializer) {}
  Modport(Serializer *serializer, const Modport& rhs);
  ~Modport() override = default;
  Modport(const Modport& rhs) = delete;
  Modport& operator=(const Modport& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view name);
  Identifier* getNameObj() { return m_name; }
  const Identifier* getNameObj() const { return m_name; }
  template <typename T> T* getNameObj() { return any_cast<T>(m_name); }
  template <typename T> const T* getNameObj() const { return any_cast<T>(m_name); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setNameObj(T, bool = false) = delete;
  bool setNameObj(Identifier* data, bool force = false) {
    if ((m_name == nullptr) || (data == nullptr) || force) {
      m_name = data;
      return true;
    }
    return false;
  }

  IODeclCollection* getIODecls() const { return m_iODecls; }
  template<typename T> IODeclCollection* getIODecls(T) = delete;
  IODeclCollection* getIODecls(bool createIfNull);
  bool setIODecls(IODeclCollection* data, bool force = false) {
    if ((m_iODecls == nullptr) || (data == nullptr) || force) {
      m_iODecls = data;
      return true;
    }
    return false;
  }

  Interface* getInterface() { return m_interface; }
  const Interface* getInterface() const { return m_interface; }
  template <typename T> T* getInterface() { return any_cast<T>(m_interface); }
  template <typename T> const T* getInterface() const { return any_cast<T>(m_interface); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInterface(T, bool = false) = delete;
  bool setInterface(Interface* data, bool force = false) {
    if ((m_interface == nullptr) || (data == nullptr) || force) {
      m_interface = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiModport; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Modport; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  Identifier* m_name = nullptr;
  IODeclCollection* m_iODecls = nullptr;
  Interface* m_interface = nullptr;
};
}  // namespace uhdm

#endif
