/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   module.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_MODULE_H
#define UHDM_MODULE_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/instance.h>

namespace uhdm {
class Module final : public Instance {
  UHDM_IMPLEMENT_RTTI(Module, Instance)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Module;

  explicit Module(Serializer *serializer) : basetype_t(serializer) {}
  Module(Serializer *serializer, const Module& rhs);
  ~Module() override = default;
  Module(const Module& rhs) = delete;
  Module& operator=(const Module& rhs) = delete;

  int32_t getIndex() const { return m_index; }
  bool setIndex(int32_t data) {
    m_index = data;
    return true;
  }

  bool getTopModule() const { return m_topModule; }
  bool setTopModule(bool data) {
    m_topModule = data;
    return true;
  }

  int32_t getDefDecayTime() const { return m_defDecayTime; }
  bool setDefDecayTime(int32_t data) {
    m_defDecayTime = data;
    return true;
  }

  ClockingBlock* getGlobalClocking() { return m_globalClocking; }
  const ClockingBlock* getGlobalClocking() const { return m_globalClocking; }
  template <typename T> T* getGlobalClocking() { return any_cast<T>(m_globalClocking); }
  template <typename T> const T* getGlobalClocking() const { return any_cast<T>(m_globalClocking); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setGlobalClocking(T, bool = false) = delete;
  bool setGlobalClocking(ClockingBlock* data, bool force = false) {
    if ((m_globalClocking == nullptr) || (data == nullptr) || force) {
      m_globalClocking = data;
      return true;
    }
    return false;
  }

  ClockingBlock* getDefaultClocking() { return m_defaultClocking; }
  const ClockingBlock* getDefaultClocking() const { return m_defaultClocking; }
  template <typename T> T* getDefaultClocking() { return any_cast<T>(m_defaultClocking); }
  template <typename T> const T* getDefaultClocking() const { return any_cast<T>(m_defaultClocking); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setDefaultClocking(T, bool = false) = delete;
  bool setDefaultClocking(ClockingBlock* data, bool force = false) {
    if ((m_defaultClocking == nullptr) || (data == nullptr) || force) {
      m_defaultClocking = data;
      return true;
    }
    return false;
  }

  Any* getDefaultDisableIff() { return m_defaultDisableIff; }
  const Any* getDefaultDisableIff() const { return m_defaultDisableIff; }
  template <typename T> T* getDefaultDisableIff() { return any_cast<T>(m_defaultDisableIff); }
  template <typename T> const T* getDefaultDisableIff() const { return any_cast<T>(m_defaultDisableIff); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setDefaultDisableIff(T, bool = false) = delete;
  bool setDefaultDisableIff(Any* data, bool force = false) {
    if ((m_defaultDisableIff == nullptr) || (data == nullptr) || force) {
      m_defaultDisableIff = data;
      return true;
    }
    return false;
  }

  ModuleArray* getModuleArray() { return m_moduleArray; }
  const ModuleArray* getModuleArray() const { return m_moduleArray; }
  template <typename T> T* getModuleArray() { return any_cast<T>(m_moduleArray); }
  template <typename T> const T* getModuleArray() const { return any_cast<T>(m_moduleArray); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setModuleArray(T, bool = false) = delete;
  bool setModuleArray(ModuleArray* data, bool force = false) {
    if ((m_moduleArray == nullptr) || (data == nullptr) || force) {
      m_moduleArray = data;
      return true;
    }
    return false;
  }

  InstanceArray* getInstanceArray() { return m_instanceArray; }
  const InstanceArray* getInstanceArray() const { return m_instanceArray; }
  template <typename T> T* getInstanceArray() { return any_cast<T>(m_instanceArray); }
  template <typename T> const T* getInstanceArray() const { return any_cast<T>(m_instanceArray); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInstanceArray(T, bool = false) = delete;
  bool setInstanceArray(InstanceArray* data, bool force = false) {
    if ((m_instanceArray == nullptr) || (data == nullptr) || force) {
      m_instanceArray = data;
      return true;
    }
    return false;
  }

  PortCollection* getPorts() const { return m_ports; }
  template<typename T> PortCollection* getPorts(T) = delete;
  PortCollection* getPorts(bool createIfNull);
  bool setPorts(PortCollection* data, bool force = false) {
    if ((m_ports == nullptr) || (data == nullptr) || force) {
      m_ports = data;
      return true;
    }
    return false;
  }

  InterfaceCollection* getInterfaces() const { return m_interfaces; }
  template<typename T> InterfaceCollection* getInterfaces(T) = delete;
  InterfaceCollection* getInterfaces(bool createIfNull);
  bool setInterfaces(InterfaceCollection* data, bool force = false) {
    if ((m_interfaces == nullptr) || (data == nullptr) || force) {
      m_interfaces = data;
      return true;
    }
    return false;
  }

  InterfaceArrayCollection* getInterfaceArrays() const { return m_interfaceArrays; }
  template<typename T> InterfaceArrayCollection* getInterfaceArrays(T) = delete;
  InterfaceArrayCollection* getInterfaceArrays(bool createIfNull);
  bool setInterfaceArrays(InterfaceArrayCollection* data, bool force = false) {
    if ((m_interfaceArrays == nullptr) || (data == nullptr) || force) {
      m_interfaceArrays = data;
      return true;
    }
    return false;
  }

  ProcessCollection* getProcesses() const { return m_processes; }
  template<typename T> ProcessCollection* getProcesses(T) = delete;
  ProcessCollection* getProcesses(bool createIfNull);
  bool setProcesses(ProcessCollection* data, bool force = false) {
    if ((m_processes == nullptr) || (data == nullptr) || force) {
      m_processes = data;
      return true;
    }
    return false;
  }

  ModuleCollection* getModules() const { return m_modules; }
  template<typename T> ModuleCollection* getModules(T) = delete;
  ModuleCollection* getModules(bool createIfNull);
  bool setModules(ModuleCollection* data, bool force = false) {
    if ((m_modules == nullptr) || (data == nullptr) || force) {
      m_modules = data;
      return true;
    }
    return false;
  }

  ModuleArrayCollection* getModuleArrays() const { return m_moduleArrays; }
  template<typename T> ModuleArrayCollection* getModuleArrays(T) = delete;
  ModuleArrayCollection* getModuleArrays(bool createIfNull);
  bool setModuleArrays(ModuleArrayCollection* data, bool force = false) {
    if ((m_moduleArrays == nullptr) || (data == nullptr) || force) {
      m_moduleArrays = data;
      return true;
    }
    return false;
  }

  GenScopeArrayCollection* getGenScopeArrays() const { return m_genScopeArrays; }
  template<typename T> GenScopeArrayCollection* getGenScopeArrays(T) = delete;
  GenScopeArrayCollection* getGenScopeArrays(bool createIfNull);
  bool setGenScopeArrays(GenScopeArrayCollection* data, bool force = false) {
    if ((m_genScopeArrays == nullptr) || (data == nullptr) || force) {
      m_genScopeArrays = data;
      return true;
    }
    return false;
  }

  ContAssignCollection* getContAssigns() const { return m_contAssigns; }
  template<typename T> ContAssignCollection* getContAssigns(T) = delete;
  ContAssignCollection* getContAssigns(bool createIfNull);
  bool setContAssigns(ContAssignCollection* data, bool force = false) {
    if ((m_contAssigns == nullptr) || (data == nullptr) || force) {
      m_contAssigns = data;
      return true;
    }
    return false;
  }

  PrimitiveCollection* getPrimitives() const { return m_primitives; }
  template<typename T> PrimitiveCollection* getPrimitives(T) = delete;
  PrimitiveCollection* getPrimitives(bool createIfNull);
  bool setPrimitives(PrimitiveCollection* data, bool force = false) {
    if ((m_primitives == nullptr) || (data == nullptr) || force) {
      m_primitives = data;
      return true;
    }
    return false;
  }

  PrimitiveArrayCollection* getPrimitiveArrays() const { return m_primitiveArrays; }
  template<typename T> PrimitiveArrayCollection* getPrimitiveArrays(T) = delete;
  PrimitiveArrayCollection* getPrimitiveArrays(bool createIfNull);
  bool setPrimitiveArrays(PrimitiveArrayCollection* data, bool force = false) {
    if ((m_primitiveArrays == nullptr) || (data == nullptr) || force) {
      m_primitiveArrays = data;
      return true;
    }
    return false;
  }

  ModPathCollection* getModPaths() const { return m_modPaths; }
  template<typename T> ModPathCollection* getModPaths(T) = delete;
  ModPathCollection* getModPaths(bool createIfNull);
  bool setModPaths(ModPathCollection* data, bool force = false) {
    if ((m_modPaths == nullptr) || (data == nullptr) || force) {
      m_modPaths = data;
      return true;
    }
    return false;
  }

  TchkCollection* getTchks() const { return m_tchks; }
  template<typename T> TchkCollection* getTchks(T) = delete;
  TchkCollection* getTchks(bool createIfNull);
  bool setTchks(TchkCollection* data, bool force = false) {
    if ((m_tchks == nullptr) || (data == nullptr) || force) {
      m_tchks = data;
      return true;
    }
    return false;
  }

  DefParamCollection* getDefParams() const { return m_defParams; }
  template<typename T> DefParamCollection* getDefParams(T) = delete;
  DefParamCollection* getDefParams(bool createIfNull);
  bool setDefParams(DefParamCollection* data, bool force = false) {
    if ((m_defParams == nullptr) || (data == nullptr) || force) {
      m_defParams = data;
      return true;
    }
    return false;
  }

  IODeclCollection* getIODecls() const { return m_iODecls; }
  template<typename T> IODeclCollection* getIODecls(T) = delete;
  IODeclCollection* getIODecls(bool createIfNull);
  bool setIODecls(IODeclCollection* data, bool force = false) {
    if ((m_iODecls == nullptr) || (data == nullptr) || force) {
      m_iODecls = data;
      return true;
    }
    return false;
  }

  AliasCollection* getAliases() const { return m_aliases; }
  template<typename T> AliasCollection* getAliases(T) = delete;
  AliasCollection* getAliases(bool createIfNull);
  bool setAliases(AliasCollection* data, bool force = false) {
    if ((m_aliases == nullptr) || (data == nullptr) || force) {
      m_aliases = data;
      return true;
    }
    return false;
  }

  ClockingBlockCollection* getClockingBlocks() const { return m_clockingBlocks; }
  template<typename T> ClockingBlockCollection* getClockingBlocks(T) = delete;
  ClockingBlockCollection* getClockingBlocks(bool createIfNull);
  bool setClockingBlocks(ClockingBlockCollection* data, bool force = false) {
    if ((m_clockingBlocks == nullptr) || (data == nullptr) || force) {
      m_clockingBlocks = data;
      return true;
    }
    return false;
  }

  TFCallCollection* getSysTaskCalls() const { return m_sysTaskCalls; }
  template<typename T> TFCallCollection* getSysTaskCalls(T) = delete;
  TFCallCollection* getSysTaskCalls(bool createIfNull);
  bool setSysTaskCalls(TFCallCollection* data, bool force = false) {
    if ((m_sysTaskCalls == nullptr) || (data == nullptr) || force) {
      m_sysTaskCalls = data;
      return true;
    }
    return false;
  }

  RefInstanceCollection* getRefInstances() const { return m_refInstances; }
  template<typename T> RefInstanceCollection* getRefInstances(T) = delete;
  RefInstanceCollection* getRefInstances(bool createIfNull);
  bool setRefInstances(RefInstanceCollection* data, bool force = false) {
    if ((m_refInstances == nullptr) || (data == nullptr) || force) {
      m_refInstances = data;
      return true;
    }
    return false;
  }

  AnyCollection* getGenStmts() const { return m_genStmts; }
  template<typename T> AnyCollection* getGenStmts(T) = delete;
  AnyCollection* getGenStmts(bool createIfNull);
  bool setGenStmts(AnyCollection* data, bool force = false) {
    if ((m_genStmts == nullptr) || (data == nullptr) || force) {
      m_genStmts = data;
      return true;
    }
    return false;
  }

  BindDirectiveCollection* getBindDirectives() const { return m_bindDirectives; }
  template<typename T> BindDirectiveCollection* getBindDirectives(T) = delete;
  BindDirectiveCollection* getBindDirectives(bool createIfNull);
  bool setBindDirectives(BindDirectiveCollection* data, bool force = false) {
    if ((m_bindDirectives == nullptr) || (data == nullptr) || force) {
      m_bindDirectives = data;
      return true;
    }
    return false;
  }

  std::string_view getEndLabel() const;
  bool setEndLabel(std::string_view name);
  Identifier* getEndLabelObj() { return m_endLabel; }
  const Identifier* getEndLabelObj() const { return m_endLabel; }
  template <typename T> T* getEndLabelObj() { return any_cast<T>(m_endLabel); }
  template <typename T> const T* getEndLabelObj() const { return any_cast<T>(m_endLabel); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setEndLabelObj(T, bool = false) = delete;
  bool setEndLabelObj(Identifier* data, bool force = false) {
    if ((m_endLabel == nullptr) || (data == nullptr) || force) {
      m_endLabel = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiModule; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Module; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  int32_t m_index = 0;
  bool m_topModule = false;
  int32_t m_defDecayTime = 0;
  ClockingBlock* m_globalClocking = nullptr;
  ClockingBlock* m_defaultClocking = nullptr;
  Any* m_defaultDisableIff = nullptr;
  ModuleArray* m_moduleArray = nullptr;
  InstanceArray* m_instanceArray = nullptr;
  PortCollection* m_ports = nullptr;
  InterfaceCollection* m_interfaces = nullptr;
  InterfaceArrayCollection* m_interfaceArrays = nullptr;
  ProcessCollection* m_processes = nullptr;
  ModuleCollection* m_modules = nullptr;
  ModuleArrayCollection* m_moduleArrays = nullptr;
  GenScopeArrayCollection* m_genScopeArrays = nullptr;
  ContAssignCollection* m_contAssigns = nullptr;
  PrimitiveCollection* m_primitives = nullptr;
  PrimitiveArrayCollection* m_primitiveArrays = nullptr;
  ModPathCollection* m_modPaths = nullptr;
  TchkCollection* m_tchks = nullptr;
  DefParamCollection* m_defParams = nullptr;
  IODeclCollection* m_iODecls = nullptr;
  AliasCollection* m_aliases = nullptr;
  ClockingBlockCollection* m_clockingBlocks = nullptr;
  TFCallCollection* m_sysTaskCalls = nullptr;
  RefInstanceCollection* m_refInstances = nullptr;
  AnyCollection* m_genStmts = nullptr;
  BindDirectiveCollection* m_bindDirectives = nullptr;
  Identifier* m_endLabel = nullptr;
};
}  // namespace uhdm

#endif
