/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   module_array.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_MODULE_ARRAY_H
#define UHDM_MODULE_ARRAY_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/instance_array.h>

namespace uhdm {
class ModuleArray final : public InstanceArray {
  UHDM_IMPLEMENT_RTTI(ModuleArray, InstanceArray)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ModuleArray;

  explicit ModuleArray(Serializer *serializer) : basetype_t(serializer) {}
  ModuleArray(Serializer *serializer, const ModuleArray& rhs);
  ~ModuleArray() override = default;
  ModuleArray(const ModuleArray& rhs) = delete;
  ModuleArray& operator=(const ModuleArray& rhs) = delete;

  Module* getModule() { return m_module; }
  const Module* getModule() const { return m_module; }
  template <typename T> T* getModule() { return any_cast<T>(m_module); }
  template <typename T> const T* getModule() const { return any_cast<T>(m_module); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setModule(T, bool = false) = delete;
  bool setModule(Module* data, bool force = false) {
    if ((m_module == nullptr) || (data == nullptr) || force) {
      m_module = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiModuleArray; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ModuleArray; }


protected:
  Module* m_module = nullptr;
};
}  // namespace uhdm

#endif
