/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   named_event.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_NAMED_EVENT_H
#define UHDM_NAMED_EVENT_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class NamedEvent final : public Any {
  UHDM_IMPLEMENT_RTTI(NamedEvent, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::NamedEvent;

  explicit NamedEvent(Serializer *serializer) : basetype_t(serializer) {}
  NamedEvent(Serializer *serializer, const NamedEvent& rhs);
  ~NamedEvent() override = default;
  NamedEvent(const NamedEvent& rhs) = delete;
  NamedEvent& operator=(const NamedEvent& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  std::string_view getFullName() const;
  bool setFullName(std::string_view data);

  bool getArrayMember() const { return m_arrayMember; }
  bool setArrayMember(bool data) {
    m_arrayMember = data;
    return true;
  }

  bool getAutomatic() const { return m_automatic; }
  bool setAutomatic(bool data) {
    m_automatic = data;
    return true;
  }

  int32_t getAllocScheme() const { return m_allocScheme; }
  bool setAllocScheme(int32_t data) {
    m_allocScheme = data;
    return true;
  }

  AttributeCollection* getAttributes() const { return m_attributes; }
  template<typename T> AttributeCollection* getAttributes(T) = delete;
  AttributeCollection* getAttributes(bool createIfNull);
  bool setAttributes(AttributeCollection* data, bool force = false) {
    if ((m_attributes == nullptr) || (data == nullptr) || force) {
      m_attributes = data;
      return true;
    }
    return false;
  }

  RefTypespec* getTypespec() { return m_typespec; }
  const RefTypespec* getTypespec() const { return m_typespec; }
  template <typename T> T* getTypespec() { return any_cast<T>(m_typespec); }
  template <typename T> const T* getTypespec() const { return any_cast<T>(m_typespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTypespec(T, bool = false) = delete;
  bool setTypespec(RefTypespec* data, bool force = false) {
    if ((m_typespec == nullptr) || (data == nullptr) || force) {
      m_typespec = data;
      return true;
    }
    return false;
  }

  ThreadCollection* getWaitingProcesses() const { return m_waitingProcesses; }
  template<typename T> ThreadCollection* getWaitingProcesses(T) = delete;
  ThreadCollection* getWaitingProcesses(bool createIfNull);
  bool setWaitingProcesses(ThreadCollection* data, bool force = false) {
    if ((m_waitingProcesses == nullptr) || (data == nullptr) || force) {
      m_waitingProcesses = data;
      return true;
    }
    return false;
  }

  std::string_view getEndLabel() const;
  bool setEndLabel(std::string_view name);
  Identifier* getEndLabelObj() { return m_endLabel; }
  const Identifier* getEndLabelObj() const { return m_endLabel; }
  template <typename T> T* getEndLabelObj() { return any_cast<T>(m_endLabel); }
  template <typename T> const T* getEndLabelObj() const { return any_cast<T>(m_endLabel); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setEndLabelObj(T, bool = false) = delete;
  bool setEndLabelObj(Identifier* data, bool force = false) {
    if ((m_endLabel == nullptr) || (data == nullptr) || force) {
      m_endLabel = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiNamedEvent; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::NamedEvent; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  SymbolId m_name = BadSymbolId;
  SymbolId m_fullName = BadSymbolId;
  bool m_arrayMember = false;
  bool m_automatic = false;
  int32_t m_allocScheme = 0;
  AttributeCollection* m_attributes = nullptr;
  RefTypespec* m_typespec = nullptr;
  ThreadCollection* m_waitingProcesses = nullptr;
  Identifier* m_endLabel = nullptr;
};
}  // namespace uhdm

#endif
