/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   operation.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_OPERATION_H
#define UHDM_OPERATION_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/expr.h>

namespace uhdm {
class Operation final : public Expr {
  UHDM_IMPLEMENT_RTTI(Operation, Expr)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Operation;

  explicit Operation(Serializer *serializer) : basetype_t(serializer) {}
  Operation(Serializer *serializer, const Operation& rhs);
  ~Operation() override = default;
  Operation(const Operation& rhs) = delete;
  Operation& operator=(const Operation& rhs) = delete;

  int32_t getOpType() const { return m_opType; }
  bool setOpType(int32_t data) {
    m_opType = data;
    return true;
  }

  bool getReordered() const { return m_reordered; }
  bool setReordered(bool data) {
    m_reordered = data;
    return true;
  }

  bool getFlattened() const { return m_flattened; }
  bool setFlattened(bool data) {
    m_flattened = data;
    return true;
  }

  bool getOpStrong() const { return m_opStrong; }
  bool setOpStrong(bool data) {
    m_opStrong = data;
    return true;
  }

  AnyCollection* getOperands() const { return m_operands; }
  template<typename T> AnyCollection* getOperands(T) = delete;
  AnyCollection* getOperands(bool createIfNull);
  bool setOperands(AnyCollection* data, bool force = false) {
    if ((m_operands == nullptr) || (data == nullptr) || force) {
      m_operands = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiOperation; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Operation; }


protected:
  int32_t m_opType = 0;
  bool m_reordered = false;
  bool m_flattened = false;
  bool m_opStrong = false;
  AnyCollection* m_operands = nullptr;
};
}  // namespace uhdm

#endif
