/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   ports.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_PORTS_H
#define UHDM_PORTS_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class Ports : public Any {
  UHDM_IMPLEMENT_RTTI(Ports, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Ports;

  explicit Ports(Serializer *serializer) : basetype_t(serializer) {}
  Ports(Serializer *serializer, const Ports& rhs);
  ~Ports() override = default;
  Ports(const Ports& rhs) = delete;
  Ports& operator=(const Ports& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  bool getExplicitName() const { return m_explicitName; }
  bool setExplicitName(bool data) {
    m_explicitName = data;
    return true;
  }

  int32_t getPortIndex() const { return m_portIndex; }
  bool setPortIndex(int32_t data) {
    m_portIndex = data;
    return true;
  }

  int32_t getPortType() const { return m_portType; }
  bool setPortType(int32_t data) {
    m_portType = data;
    return true;
  }

  bool getScalar() const { return m_scalar; }
  bool setScalar(bool data) {
    m_scalar = data;
    return true;
  }

  bool getVector() const { return m_vector; }
  bool setVector(bool data) {
    m_vector = data;
    return true;
  }

  bool getConnByName() const { return m_connByName; }
  bool setConnByName(bool data) {
    m_connByName = data;
    return true;
  }

  int32_t getDirection() const { return m_direction; }
  bool setDirection(int32_t data) {
    m_direction = data;
    return true;
  }

  int32_t getSize() const { return m_size; }
  bool setSize(int32_t data) {
    m_size = data;
    return true;
  }

  Any* getLowConn() { return m_lowConn; }
  const Any* getLowConn() const { return m_lowConn; }
  template <typename T> T* getLowConn() { return any_cast<T>(m_lowConn); }
  template <typename T> const T* getLowConn() const { return any_cast<T>(m_lowConn); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setLowConn(T, bool = false) = delete;
  bool setLowConn(Any* data, bool force = false) {
    if ((m_lowConn == nullptr) || (data == nullptr) || force) {
      m_lowConn = data;
      return true;
    }
    return false;
  }

  Any* getHighConn() { return m_highConn; }
  const Any* getHighConn() const { return m_highConn; }
  template <typename T> T* getHighConn() { return any_cast<T>(m_highConn); }
  template <typename T> const T* getHighConn() const { return any_cast<T>(m_highConn); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setHighConn(T, bool = false) = delete;
  bool setHighConn(Any* data, bool force = false) {
    if ((m_highConn == nullptr) || (data == nullptr) || force) {
      m_highConn = data;
      return true;
    }
    return false;
  }

  RefTypespec* getTypespec() { return m_typespec; }
  const RefTypespec* getTypespec() const { return m_typespec; }
  template <typename T> T* getTypespec() { return any_cast<T>(m_typespec); }
  template <typename T> const T* getTypespec() const { return any_cast<T>(m_typespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTypespec(T, bool = false) = delete;
  bool setTypespec(RefTypespec* data, bool force = false) {
    if ((m_typespec == nullptr) || (data == nullptr) || force) {
      m_typespec = data;
      return true;
    }
    return false;
  }

  Instance* getInstance() { return m_instance; }
  const Instance* getInstance() const { return m_instance; }
  template <typename T> T* getInstance() { return any_cast<T>(m_instance); }
  template <typename T> const T* getInstance() const { return any_cast<T>(m_instance); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInstance(T, bool = false) = delete;
  bool setInstance(Instance* data, bool force = false) {
    if ((m_instance == nullptr) || (data == nullptr) || force) {
      m_instance = data;
      return true;
    }
    return false;
  }

  Module* getModule() { return m_module; }
  const Module* getModule() const { return m_module; }
  template <typename T> T* getModule() { return any_cast<T>(m_module); }
  template <typename T> const T* getModule() const { return any_cast<T>(m_module); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setModule(T, bool = false) = delete;
  bool setModule(Module* data, bool force = false) {
    if ((m_module == nullptr) || (data == nullptr) || force) {
      m_module = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiPorts; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Ports; }


protected:
  SymbolId m_name = BadSymbolId;
  bool m_explicitName = false;
  int32_t m_portIndex = 0;
  int32_t m_portType = 0;
  bool m_scalar = false;
  bool m_vector = false;
  bool m_connByName = false;
  int32_t m_direction = 0;
  int32_t m_size = 0;
  Any* m_lowConn = nullptr;
  Any* m_highConn = nullptr;
  RefTypespec* m_typespec = nullptr;
  Instance* m_instance = nullptr;
  Module* m_module = nullptr;
};
}  // namespace uhdm

#endif
