/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   primitive.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_PRIMITIVE_H
#define UHDM_PRIMITIVE_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class Primitive : public Any {
  UHDM_IMPLEMENT_RTTI(Primitive, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Primitive;

  explicit Primitive(Serializer *serializer) : basetype_t(serializer) {}
  Primitive(Serializer *serializer, const Primitive& rhs);
  ~Primitive() override = default;
  Primitive(const Primitive& rhs) = delete;
  Primitive& operator=(const Primitive& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  std::string_view getFullName() const;
  bool setFullName(std::string_view data);

  std::string_view getDefName() const override;
  bool setDefName(std::string_view name);
  Identifier* getDefNameObj() { return m_defName; }
  const Identifier* getDefNameObj() const { return m_defName; }
  template <typename T> T* getDefNameObj() { return any_cast<T>(m_defName); }
  template <typename T> const T* getDefNameObj() const { return any_cast<T>(m_defName); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setDefNameObj(T, bool = false) = delete;
  bool setDefNameObj(Identifier* data, bool force = false) {
    if ((m_defName == nullptr) || (data == nullptr) || force) {
      m_defName = data;
      return true;
    }
    return false;
  }

  bool getArrayMember() const { return m_arrayMember; }
  bool setArrayMember(bool data) {
    m_arrayMember = data;
    return true;
  }

  std::string_view getVpiDelay() const;
  bool setVpiDelay(std::string_view data);

  int32_t getPrimType() const { return m_primType; }
  bool setPrimType(int32_t data) {
    m_primType = data;
    return true;
  }

  int32_t getStrength0() const { return m_strength0; }
  bool setStrength0(int32_t data) {
    m_strength0 = data;
    return true;
  }

  int32_t getStrength1() const { return m_strength1; }
  bool setStrength1(int32_t data) {
    m_strength1 = data;
    return true;
  }

  AttributeCollection* getAttributes() const { return m_attributes; }
  template<typename T> AttributeCollection* getAttributes(T) = delete;
  AttributeCollection* getAttributes(bool createIfNull);
  bool setAttributes(AttributeCollection* data, bool force = false) {
    if ((m_attributes == nullptr) || (data == nullptr) || force) {
      m_attributes = data;
      return true;
    }
    return false;
  }

  ExprCollection* getDelays() const { return m_delays; }
  template<typename T> ExprCollection* getDelays(T) = delete;
  ExprCollection* getDelays(bool createIfNull);
  bool setDelays(ExprCollection* data, bool force = false) {
    if ((m_delays == nullptr) || (data == nullptr) || force) {
      m_delays = data;
      return true;
    }
    return false;
  }

  Expr* getIndex() { return m_index; }
  const Expr* getIndex() const { return m_index; }
  template <typename T> T* getIndex() { return any_cast<T>(m_index); }
  template <typename T> const T* getIndex() const { return any_cast<T>(m_index); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setIndex(T, bool = false) = delete;
  bool setIndex(Expr* data, bool force = false) {
    if ((m_index == nullptr) || (data == nullptr) || force) {
      m_index = data;
      return true;
    }
    return false;
  }

  PrimTermCollection* getPrimTerms() const { return m_primTerms; }
  template<typename T> PrimTermCollection* getPrimTerms(T) = delete;
  PrimTermCollection* getPrimTerms(bool createIfNull);
  bool setPrimTerms(PrimTermCollection* data, bool force = false) {
    if ((m_primTerms == nullptr) || (data == nullptr) || force) {
      m_primTerms = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiPrimitive; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Primitive; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  SymbolId m_name = BadSymbolId;
  SymbolId m_fullName = BadSymbolId;
  Identifier* m_defName = nullptr;
  bool m_arrayMember = false;
  SymbolId m_vpiDelay = BadSymbolId;
  int32_t m_primType = 0;
  int32_t m_strength0 = 0;
  int32_t m_strength1 = 0;
  AttributeCollection* m_attributes = nullptr;
  ExprCollection* m_delays = nullptr;
  Expr* m_index = nullptr;
  PrimTermCollection* m_primTerms = nullptr;
};
}  // namespace uhdm

#endif
