/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   primitive_array.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_PRIMITIVE_ARRAY_H
#define UHDM_PRIMITIVE_ARRAY_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/instance_array.h>

namespace uhdm {
class PrimitiveArray : public InstanceArray {
  UHDM_IMPLEMENT_RTTI(PrimitiveArray, InstanceArray)

public:
  static constexpr UhdmType kUhdmType = UhdmType::PrimitiveArray;

  explicit PrimitiveArray(Serializer *serializer) : basetype_t(serializer) {}
  PrimitiveArray(Serializer *serializer, const PrimitiveArray& rhs);
  ~PrimitiveArray() override = default;
  PrimitiveArray(const PrimitiveArray& rhs) = delete;
  PrimitiveArray& operator=(const PrimitiveArray& rhs) = delete;

  Expr* getDelay() { return m_delay; }
  const Expr* getDelay() const { return m_delay; }
  template <typename T> T* getDelay() { return any_cast<T>(m_delay); }
  template <typename T> const T* getDelay() const { return any_cast<T>(m_delay); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setDelay(T, bool = false) = delete;
  bool setDelay(Expr* data, bool force = false) {
    if ((m_delay == nullptr) || (data == nullptr) || force) {
      m_delay = data;
      return true;
    }
    return false;
  }

  PrimitiveCollection* getPrimitives() const { return m_primitives; }
  template<typename T> PrimitiveCollection* getPrimitives(T) = delete;
  PrimitiveCollection* getPrimitives(bool createIfNull);
  bool setPrimitives(PrimitiveCollection* data, bool force = false) {
    if ((m_primitives == nullptr) || (data == nullptr) || force) {
      m_primitives = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiPrimitiveArray; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::PrimitiveArray; }


protected:
  Expr* m_delay = nullptr;
  PrimitiveCollection* m_primitives = nullptr;
};
}  // namespace uhdm

#endif
