/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   property_inst.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_PROPERTY_INST_H
#define UHDM_PROPERTY_INST_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class PropertyInst final : public Any {
  UHDM_IMPLEMENT_RTTI(PropertyInst, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::PropertyInst;

  explicit PropertyInst(Serializer *serializer) : basetype_t(serializer) {}
  PropertyInst(Serializer *serializer, const PropertyInst& rhs);
  ~PropertyInst() override = default;
  PropertyInst(const PropertyInst& rhs) = delete;
  PropertyInst& operator=(const PropertyInst& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  Any* getDisableCondition() { return m_disableCondition; }
  const Any* getDisableCondition() const { return m_disableCondition; }
  template <typename T> T* getDisableCondition() { return any_cast<T>(m_disableCondition); }
  template <typename T> const T* getDisableCondition() const { return any_cast<T>(m_disableCondition); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setDisableCondition(T, bool = false) = delete;
  bool setDisableCondition(Any* data, bool force = false) {
    if ((m_disableCondition == nullptr) || (data == nullptr) || force) {
      m_disableCondition = data;
      return true;
    }
    return false;
  }

  AnyCollection* getArguments() const { return m_arguments; }
  template<typename T> AnyCollection* getArguments(T) = delete;
  AnyCollection* getArguments(bool createIfNull);
  bool setArguments(AnyCollection* data, bool force = false) {
    if ((m_arguments == nullptr) || (data == nullptr) || force) {
      m_arguments = data;
      return true;
    }
    return false;
  }

  PropertyDecl* getPropertyDecl() { return m_propertyDecl; }
  const PropertyDecl* getPropertyDecl() const { return m_propertyDecl; }
  template <typename T> T* getPropertyDecl() { return any_cast<T>(m_propertyDecl); }
  template <typename T> const T* getPropertyDecl() const { return any_cast<T>(m_propertyDecl); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setPropertyDecl(T, bool = false) = delete;
  bool setPropertyDecl(PropertyDecl* data, bool force = false) {
    if ((m_propertyDecl == nullptr) || (data == nullptr) || force) {
      m_propertyDecl = data;
      return true;
    }
    return false;
  }

  ClockingBlock* getClockingBlock() { return m_clockingBlock; }
  const ClockingBlock* getClockingBlock() const { return m_clockingBlock; }
  template <typename T> T* getClockingBlock() { return any_cast<T>(m_clockingBlock); }
  template <typename T> const T* getClockingBlock() const { return any_cast<T>(m_clockingBlock); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setClockingBlock(T, bool = false) = delete;
  bool setClockingBlock(ClockingBlock* data, bool force = false) {
    if ((m_clockingBlock == nullptr) || (data == nullptr) || force) {
      m_clockingBlock = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiPropertyInst; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::PropertyInst; }


protected:
  SymbolId m_name = BadSymbolId;
  Any* m_disableCondition = nullptr;
  AnyCollection* m_arguments = nullptr;
  PropertyDecl* m_propertyDecl = nullptr;
  ClockingBlock* m_clockingBlock = nullptr;
};
}  // namespace uhdm

#endif
