/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   ref_obj.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_REF_OBJ_H
#define UHDM_REF_OBJ_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/simple_expr.h>

namespace uhdm {
class RefObj final : public SimpleExpr {
  UHDM_IMPLEMENT_RTTI(RefObj, SimpleExpr)

public:
  static constexpr UhdmType kUhdmType = UhdmType::RefObj;

  explicit RefObj(Serializer *serializer) : basetype_t(serializer) {}
  RefObj(Serializer *serializer, const RefObj& rhs);
  ~RefObj() override = default;
  RefObj(const RefObj& rhs) = delete;
  RefObj& operator=(const RefObj& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  std::string_view getFullName() const;
  bool setFullName(std::string_view data);

  std::string_view getDefName() const override;
  bool setDefName(std::string_view data);

  bool getGeneric() const { return m_generic; }
  bool setGeneric(bool data) {
    m_generic = data;
    return true;
  }

  Any* getActual() { return m_actual; }
  const Any* getActual() const { return m_actual; }
  template <typename T> T* getActual() { return any_cast<T>(m_actual); }
  template <typename T> const T* getActual() const { return any_cast<T>(m_actual); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setActual(T, bool = false) = delete;
  bool setActual(Any* data, bool force = false) {
    if ((m_actual == nullptr) || (data == nullptr) || force) {
      m_actual = data;
      return true;
    }
    return false;
  }

  bool getStructMember() const { return m_structMember; }
  bool setStructMember(bool data) {
    m_structMember = data;
    return true;
  }

  uint32_t getVpiType() const override { return vpiRefObj; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::RefObj; }


protected:
  SymbolId m_name = BadSymbolId;
  SymbolId m_fullName = BadSymbolId;
  SymbolId m_defName = BadSymbolId;
  bool m_generic = false;
  Any* m_actual = nullptr;
  bool m_structMember = false;
};
}  // namespace uhdm

#endif
