/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   ref_instance.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_REF_INSTANCE_H
#define UHDM_REF_INSTANCE_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class RefInstance final : public Any {
  UHDM_IMPLEMENT_RTTI(RefInstance, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::RefInstance;

  explicit RefInstance(Serializer *serializer) : basetype_t(serializer) {}
  RefInstance(Serializer *serializer, const RefInstance& rhs);
  ~RefInstance() override = default;
  RefInstance(const RefInstance& rhs) = delete;
  RefInstance& operator=(const RefInstance& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  RefTypespec* getTypespec() { return m_typespec; }
  const RefTypespec* getTypespec() const { return m_typespec; }
  template <typename T> T* getTypespec() { return any_cast<T>(m_typespec); }
  template <typename T> const T* getTypespec() const { return any_cast<T>(m_typespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTypespec(T, bool = false) = delete;
  bool setTypespec(RefTypespec* data, bool force = false) {
    if ((m_typespec == nullptr) || (data == nullptr) || force) {
      m_typespec = data;
      return true;
    }
    return false;
  }

  ParamAssignCollection* getParamAssigns() const { return m_paramAssigns; }
  template<typename T> ParamAssignCollection* getParamAssigns(T) = delete;
  ParamAssignCollection* getParamAssigns(bool createIfNull);
  bool setParamAssigns(ParamAssignCollection* data, bool force = false) {
    if ((m_paramAssigns == nullptr) || (data == nullptr) || force) {
      m_paramAssigns = data;
      return true;
    }
    return false;
  }

  PortCollection* getPorts() const { return m_ports; }
  template<typename T> PortCollection* getPorts(T) = delete;
  PortCollection* getPorts(bool createIfNull);
  bool setPorts(PortCollection* data, bool force = false) {
    if ((m_ports == nullptr) || (data == nullptr) || force) {
      m_ports = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiRefInstance; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::RefInstance; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  SymbolId m_name = BadSymbolId;
  RefTypespec* m_typespec = nullptr;
  ParamAssignCollection* m_paramAssigns = nullptr;
  PortCollection* m_ports = nullptr;
};
}  // namespace uhdm

#endif
