/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   reg.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_REG_H
#define UHDM_REG_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class Reg final : public Any {
  UHDM_IMPLEMENT_RTTI(Reg, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Reg;

  explicit Reg(Serializer *serializer) : basetype_t(serializer) {}
  Reg(Serializer *serializer, const Reg& rhs);
  ~Reg() override = default;
  Reg(const Reg& rhs) = delete;
  Reg& operator=(const Reg& rhs) = delete;

  Expr* getLeftExpr() { return m_leftExpr; }
  const Expr* getLeftExpr() const { return m_leftExpr; }
  template <typename T> T* getLeftExpr() { return any_cast<T>(m_leftExpr); }
  template <typename T> const T* getLeftExpr() const { return any_cast<T>(m_leftExpr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setLeftExpr(T, bool = false) = delete;
  bool setLeftExpr(Expr* data, bool force = false) {
    if ((m_leftExpr == nullptr) || (data == nullptr) || force) {
      m_leftExpr = data;
      return true;
    }
    return false;
  }

  Expr* getRightExpr() { return m_rightExpr; }
  const Expr* getRightExpr() const { return m_rightExpr; }
  template <typename T> T* getRightExpr() { return any_cast<T>(m_rightExpr); }
  template <typename T> const T* getRightExpr() const { return any_cast<T>(m_rightExpr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setRightExpr(T, bool = false) = delete;
  bool setRightExpr(Expr* data, bool force = false) {
    if ((m_rightExpr == nullptr) || (data == nullptr) || force) {
      m_rightExpr = data;
      return true;
    }
    return false;
  }

  Expr* getIndex() { return m_index; }
  const Expr* getIndex() const { return m_index; }
  template <typename T> T* getIndex() { return any_cast<T>(m_index); }
  template <typename T> const T* getIndex() const { return any_cast<T>(m_index); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setIndex(T, bool = false) = delete;
  bool setIndex(Expr* data, bool force = false) {
    if ((m_index == nullptr) || (data == nullptr) || force) {
      m_index = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiReg; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Reg; }


protected:
  Expr* m_leftExpr = nullptr;
  Expr* m_rightExpr = nullptr;
  Expr* m_index = nullptr;
};
}  // namespace uhdm

#endif
