/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   return_stmt.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_RETURN_STMT_H
#define UHDM_RETURN_STMT_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/atomic_stmt.h>

namespace uhdm {
class ReturnStmt final : public AtomicStmt {
  UHDM_IMPLEMENT_RTTI(ReturnStmt, AtomicStmt)

public:
  static constexpr UhdmType kUhdmType = UhdmType::ReturnStmt;

  explicit ReturnStmt(Serializer *serializer) : basetype_t(serializer) {}
  ReturnStmt(Serializer *serializer, const ReturnStmt& rhs);
  ~ReturnStmt() override = default;
  ReturnStmt(const ReturnStmt& rhs) = delete;
  ReturnStmt& operator=(const ReturnStmt& rhs) = delete;

  Expr* getCondition() { return m_condition; }
  const Expr* getCondition() const { return m_condition; }
  template <typename T> T* getCondition() { return any_cast<T>(m_condition); }
  template <typename T> const T* getCondition() const { return any_cast<T>(m_condition); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setCondition(T, bool = false) = delete;
  bool setCondition(Expr* data, bool force = false) {
    if ((m_condition == nullptr) || (data == nullptr) || force) {
      m_condition = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiReturn; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::ReturnStmt; }


protected:
  Expr* m_condition = nullptr;
};
}  // namespace uhdm

#endif
