/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   seq_formal_decl.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_SEQ_FORMAL_DECL_H
#define UHDM_SEQ_FORMAL_DECL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class SeqFormalDecl final : public Any {
  UHDM_IMPLEMENT_RTTI(SeqFormalDecl, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::SeqFormalDecl;

  explicit SeqFormalDecl(Serializer *serializer) : basetype_t(serializer) {}
  SeqFormalDecl(Serializer *serializer, const SeqFormalDecl& rhs);
  ~SeqFormalDecl() override = default;
  SeqFormalDecl(const SeqFormalDecl& rhs) = delete;
  SeqFormalDecl& operator=(const SeqFormalDecl& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view name);
  Identifier* getNameObj() { return m_name; }
  const Identifier* getNameObj() const { return m_name; }
  template <typename T> T* getNameObj() { return any_cast<T>(m_name); }
  template <typename T> const T* getNameObj() const { return any_cast<T>(m_name); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setNameObj(T, bool = false) = delete;
  bool setNameObj(Identifier* data, bool force = false) {
    if ((m_name == nullptr) || (data == nullptr) || force) {
      m_name = data;
      return true;
    }
    return false;
  }

  int32_t getDirection() const { return m_direction; }
  bool setDirection(int32_t data) {
    m_direction = data;
    return true;
  }

  AttributeCollection* getAttributes() const { return m_attributes; }
  template<typename T> AttributeCollection* getAttributes(T) = delete;
  AttributeCollection* getAttributes(bool createIfNull);
  bool setAttributes(AttributeCollection* data, bool force = false) {
    if ((m_attributes == nullptr) || (data == nullptr) || force) {
      m_attributes = data;
      return true;
    }
    return false;
  }

  Any* getExpr() { return m_expr; }
  const Any* getExpr() const { return m_expr; }
  template <typename T> T* getExpr() { return any_cast<T>(m_expr); }
  template <typename T> const T* getExpr() const { return any_cast<T>(m_expr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setExpr(T, bool = false) = delete;
  bool setExpr(Any* data, bool force = false) {
    if ((m_expr == nullptr) || (data == nullptr) || force) {
      m_expr = data;
      return true;
    }
    return false;
  }

  RefTypespec* getTypespec() { return m_typespec; }
  const RefTypespec* getTypespec() const { return m_typespec; }
  template <typename T> T* getTypespec() { return any_cast<T>(m_typespec); }
  template <typename T> const T* getTypespec() const { return any_cast<T>(m_typespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTypespec(T, bool = false) = delete;
  bool setTypespec(RefTypespec* data, bool force = false) {
    if ((m_typespec == nullptr) || (data == nullptr) || force) {
      m_typespec = data;
      return true;
    }
    return false;
  }

  int32_t getFormalType() const { return m_formalType; }
  bool setFormalType(int32_t data) {
    m_formalType = data;
    return true;
  }

  uint32_t getVpiType() const override { return vpiSeqFormalDecl; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::SeqFormalDecl; }


protected:
  Identifier* m_name = nullptr;
  int32_t m_direction = 0;
  AttributeCollection* m_attributes = nullptr;
  Any* m_expr = nullptr;
  RefTypespec* m_typespec = nullptr;
  int32_t m_formalType = 0;
};
}  // namespace uhdm

#endif
