/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   sequence_decl.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_SEQUENCE_DECL_H
#define UHDM_SEQUENCE_DECL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class SequenceDecl final : public Any {
  UHDM_IMPLEMENT_RTTI(SequenceDecl, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::SequenceDecl;

  explicit SequenceDecl(Serializer *serializer) : basetype_t(serializer) {}
  SequenceDecl(Serializer *serializer, const SequenceDecl& rhs);
  ~SequenceDecl() override = default;
  SequenceDecl(const SequenceDecl& rhs) = delete;
  SequenceDecl& operator=(const SequenceDecl& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view name);
  Identifier* getNameObj() { return m_name; }
  const Identifier* getNameObj() const { return m_name; }
  template <typename T> T* getNameObj() { return any_cast<T>(m_name); }
  template <typename T> const T* getNameObj() const { return any_cast<T>(m_name); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setNameObj(T, bool = false) = delete;
  bool setNameObj(Identifier* data, bool force = false) {
    if ((m_name == nullptr) || (data == nullptr) || force) {
      m_name = data;
      return true;
    }
    return false;
  }

  std::string_view getFullName() const;
  bool setFullName(std::string_view data);

  AttributeCollection* getAttributes() const { return m_attributes; }
  template<typename T> AttributeCollection* getAttributes(T) = delete;
  AttributeCollection* getAttributes(bool createIfNull);
  bool setAttributes(AttributeCollection* data, bool force = false) {
    if ((m_attributes == nullptr) || (data == nullptr) || force) {
      m_attributes = data;
      return true;
    }
    return false;
  }

  VariableCollection* getVariables() const { return m_variables; }
  template<typename T> VariableCollection* getVariables(T) = delete;
  VariableCollection* getVariables(bool createIfNull);
  bool setVariables(VariableCollection* data, bool force = false) {
    if ((m_variables == nullptr) || (data == nullptr) || force) {
      m_variables = data;
      return true;
    }
    return false;
  }

  Any* getExpr() { return m_expr; }
  const Any* getExpr() const { return m_expr; }
  template <typename T> T* getExpr() { return any_cast<T>(m_expr); }
  template <typename T> const T* getExpr() const { return any_cast<T>(m_expr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setExpr(T, bool = false) = delete;
  bool setExpr(Any* data, bool force = false) {
    if ((m_expr == nullptr) || (data == nullptr) || force) {
      m_expr = data;
      return true;
    }
    return false;
  }

  SeqFormalDeclCollection* getSeqFormalDecls() const { return m_seqFormalDecls; }
  template<typename T> SeqFormalDeclCollection* getSeqFormalDecls(T) = delete;
  SeqFormalDeclCollection* getSeqFormalDecls(bool createIfNull);
  bool setSeqFormalDecls(SeqFormalDeclCollection* data, bool force = false) {
    if ((m_seqFormalDecls == nullptr) || (data == nullptr) || force) {
      m_seqFormalDecls = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiSequenceDecl; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::SequenceDecl; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  Identifier* m_name = nullptr;
  SymbolId m_fullName = BadSymbolId;
  AttributeCollection* m_attributes = nullptr;
  VariableCollection* m_variables = nullptr;
  Any* m_expr = nullptr;
  SeqFormalDeclCollection* m_seqFormalDecls = nullptr;
};
}  // namespace uhdm

#endif
