/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   switch_array.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_SWITCH_ARRAY_H
#define UHDM_SWITCH_ARRAY_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/primitive_array.h>

namespace uhdm {
class SwitchArray final : public PrimitiveArray {
  UHDM_IMPLEMENT_RTTI(SwitchArray, PrimitiveArray)

public:
  static constexpr UhdmType kUhdmType = UhdmType::SwitchArray;

  explicit SwitchArray(Serializer *serializer) : basetype_t(serializer) {}
  SwitchArray(Serializer *serializer, const SwitchArray& rhs);
  ~SwitchArray() override = default;
  SwitchArray(const SwitchArray& rhs) = delete;
  SwitchArray& operator=(const SwitchArray& rhs) = delete;

  SwitchTran* getSwitchTran() { return m_switchTran; }
  const SwitchTran* getSwitchTran() const { return m_switchTran; }
  template <typename T> T* getSwitchTran() { return any_cast<T>(m_switchTran); }
  template <typename T> const T* getSwitchTran() const { return any_cast<T>(m_switchTran); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setSwitchTran(T, bool = false) = delete;
  bool setSwitchTran(SwitchTran* data, bool force = false) {
    if ((m_switchTran == nullptr) || (data == nullptr) || force) {
      m_switchTran = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiSwitchArray; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::SwitchArray; }


protected:
  SwitchTran* m_switchTran = nullptr;
};
}  // namespace uhdm

#endif
