/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   tagged_pattern.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_TAGGED_PATTERN_H
#define UHDM_TAGGED_PATTERN_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class TaggedPattern final : public Any {
  UHDM_IMPLEMENT_RTTI(TaggedPattern, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::TaggedPattern;

  explicit TaggedPattern(Serializer *serializer) : basetype_t(serializer) {}
  TaggedPattern(Serializer *serializer, const TaggedPattern& rhs);
  ~TaggedPattern() override = default;
  TaggedPattern(const TaggedPattern& rhs) = delete;
  TaggedPattern& operator=(const TaggedPattern& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  Expr* getTag() { return m_tag; }
  const Expr* getTag() const { return m_tag; }
  template <typename T> T* getTag() { return any_cast<T>(m_tag); }
  template <typename T> const T* getTag() const { return any_cast<T>(m_tag); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTag(T, bool = false) = delete;
  bool setTag(Expr* data, bool force = false) {
    if ((m_tag == nullptr) || (data == nullptr) || force) {
      m_tag = data;
      return true;
    }
    return false;
  }

  Any* getPattern() { return m_pattern; }
  const Any* getPattern() const { return m_pattern; }
  template <typename T> T* getPattern() { return any_cast<T>(m_pattern); }
  template <typename T> const T* getPattern() const { return any_cast<T>(m_pattern); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setPattern(T, bool = false) = delete;
  bool setPattern(Any* data, bool force = false) {
    if ((m_pattern == nullptr) || (data == nullptr) || force) {
      m_pattern = data;
      return true;
    }
    return false;
  }

  RefTypespec* getTypespec() { return m_typespec; }
  const RefTypespec* getTypespec() const { return m_typespec; }
  template <typename T> T* getTypespec() { return any_cast<T>(m_typespec); }
  template <typename T> const T* getTypespec() const { return any_cast<T>(m_typespec); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTypespec(T, bool = false) = delete;
  bool setTypespec(RefTypespec* data, bool force = false) {
    if ((m_typespec == nullptr) || (data == nullptr) || force) {
      m_typespec = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiTaggedPattern; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::TaggedPattern; }


protected:
  SymbolId m_name = BadSymbolId;
  Expr* m_tag = nullptr;
  Any* m_pattern = nullptr;
  RefTypespec* m_typespec = nullptr;
};
}  // namespace uhdm

#endif
