/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   task_decl.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_TASK_DECL_H
#define UHDM_TASK_DECL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/task_func_decl.h>

namespace uhdm {
class TaskDecl final : public TaskFuncDecl {
  UHDM_IMPLEMENT_RTTI(TaskDecl, TaskFuncDecl)

public:
  static constexpr UhdmType kUhdmType = UhdmType::TaskDecl;

  explicit TaskDecl(Serializer *serializer) : basetype_t(serializer) {}
  TaskDecl(Serializer *serializer, const TaskDecl& rhs);
  ~TaskDecl() override = default;
  TaskDecl(const TaskDecl& rhs) = delete;
  TaskDecl& operator=(const TaskDecl& rhs) = delete;

  uint32_t getVpiType() const override { return vpiTaskDecl; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::TaskDecl; }


protected:

};
}  // namespace uhdm

#endif
