/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   task_func.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_TASK_FUNC_H
#define UHDM_TASK_FUNC_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/scope.h>

namespace uhdm {
class TaskFunc : public Scope {
  UHDM_IMPLEMENT_RTTI(TaskFunc, Scope)

public:
  static constexpr UhdmType kUhdmType = UhdmType::TaskFunc;

  explicit TaskFunc(Serializer *serializer) : basetype_t(serializer) {}
  TaskFunc(Serializer *serializer, const TaskFunc& rhs);
  ~TaskFunc() override = default;
  TaskFunc(const TaskFunc& rhs) = delete;
  TaskFunc& operator=(const TaskFunc& rhs) = delete;

  bool getMethod() const { return m_method; }
  bool setMethod(bool data) {
    m_method = data;
    return true;
  }

  int32_t getAccessType() const { return m_accessType; }
  bool setAccessType(int32_t data) {
    m_accessType = data;
    return true;
  }

  int32_t getVisibility() const { return m_visibility; }
  bool setVisibility(int32_t data) {
    m_visibility = data;
    return true;
  }

  bool getVirtual() const { return m_virtual; }
  bool setVirtual(bool data) {
    m_virtual = data;
    return true;
  }

  bool getAutomatic() const { return m_automatic; }
  bool setAutomatic(bool data) {
    m_automatic = data;
    return true;
  }

  bool getDPIPure() const { return m_dPIPure; }
  bool setDPIPure(bool data) {
    m_dPIPure = data;
    return true;
  }

  bool getDPIContext() const { return m_dPIContext; }
  bool setDPIContext(bool data) {
    m_dPIContext = data;
    return true;
  }

  int32_t getDPICStr() const { return m_dPICStr; }
  bool setDPICStr(int32_t data) {
    m_dPICStr = data;
    return true;
  }

  std::string_view getDPICIdentifier() const;
  bool setDPICIdentifier(std::string_view data);

  Expr* getLeftExpr() { return m_leftExpr; }
  const Expr* getLeftExpr() const { return m_leftExpr; }
  template <typename T> T* getLeftExpr() { return any_cast<T>(m_leftExpr); }
  template <typename T> const T* getLeftExpr() const { return any_cast<T>(m_leftExpr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setLeftExpr(T, bool = false) = delete;
  bool setLeftExpr(Expr* data, bool force = false) {
    if ((m_leftExpr == nullptr) || (data == nullptr) || force) {
      m_leftExpr = data;
      return true;
    }
    return false;
  }

  Expr* getRightExpr() { return m_rightExpr; }
  const Expr* getRightExpr() const { return m_rightExpr; }
  template <typename T> T* getRightExpr() { return any_cast<T>(m_rightExpr); }
  template <typename T> const T* getRightExpr() const { return any_cast<T>(m_rightExpr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setRightExpr(T, bool = false) = delete;
  bool setRightExpr(Expr* data, bool force = false) {
    if ((m_rightExpr == nullptr) || (data == nullptr) || force) {
      m_rightExpr = data;
      return true;
    }
    return false;
  }

  TaskFuncDeclCollection* getTaskFuncDecls() const { return m_taskFuncDecls; }
  template<typename T> TaskFuncDeclCollection* getTaskFuncDecls(T) = delete;
  TaskFuncDeclCollection* getTaskFuncDecls(bool createIfNull);
  bool setTaskFuncDecls(TaskFuncDeclCollection* data, bool force = false) {
    if ((m_taskFuncDecls == nullptr) || (data == nullptr) || force) {
      m_taskFuncDecls = data;
      return true;
    }
    return false;
  }

  IODeclCollection* getIODecls() const { return m_iODecls; }
  template<typename T> IODeclCollection* getIODecls(T) = delete;
  IODeclCollection* getIODecls(bool createIfNull);
  bool setIODecls(IODeclCollection* data, bool force = false) {
    if ((m_iODecls == nullptr) || (data == nullptr) || force) {
      m_iODecls = data;
      return true;
    }
    return false;
  }

  Any* getStmt() { return m_stmt; }
  const Any* getStmt() const { return m_stmt; }
  template <typename T> T* getStmt() { return any_cast<T>(m_stmt); }
  template <typename T> const T* getStmt() const { return any_cast<T>(m_stmt); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setStmt(T, bool = false) = delete;
  bool setStmt(Any* data, bool force = false) {
    if ((m_stmt == nullptr) || (data == nullptr) || force) {
      m_stmt = data;
      return true;
    }
    return false;
  }

  Instance* getInstance() { return m_instance; }
  const Instance* getInstance() const { return m_instance; }
  template <typename T> T* getInstance() { return any_cast<T>(m_instance); }
  template <typename T> const T* getInstance() const { return any_cast<T>(m_instance); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInstance(T, bool = false) = delete;
  bool setInstance(Instance* data, bool force = false) {
    if ((m_instance == nullptr) || (data == nullptr) || force) {
      m_instance = data;
      return true;
    }
    return false;
  }

  std::string_view getEndLabel() const;
  bool setEndLabel(std::string_view name);
  Identifier* getEndLabelObj() { return m_endLabel; }
  const Identifier* getEndLabelObj() const { return m_endLabel; }
  template <typename T> T* getEndLabelObj() { return any_cast<T>(m_endLabel); }
  template <typename T> const T* getEndLabelObj() const { return any_cast<T>(m_endLabel); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setEndLabelObj(T, bool = false) = delete;
  bool setEndLabelObj(Identifier* data, bool force = false) {
    if ((m_endLabel == nullptr) || (data == nullptr) || force) {
      m_endLabel = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiTaskFunc; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::TaskFunc; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  bool m_method = false;
  int32_t m_accessType = 0;
  int32_t m_visibility = 0;
  bool m_virtual = false;
  bool m_automatic = false;
  bool m_dPIPure = false;
  bool m_dPIContext = false;
  int32_t m_dPICStr = 0;
  SymbolId m_dPICIdentifier = BadSymbolId;
  Expr* m_leftExpr = nullptr;
  Expr* m_rightExpr = nullptr;
  TaskFuncDeclCollection* m_taskFuncDecls = nullptr;
  IODeclCollection* m_iODecls = nullptr;
  Any* m_stmt = nullptr;
  Instance* m_instance = nullptr;
  Identifier* m_endLabel = nullptr;
};
}  // namespace uhdm

#endif
