/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   tf_call.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_TF_CALL_H
#define UHDM_TF_CALL_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/expr.h>

namespace uhdm {
class TFCall : public Expr {
  UHDM_IMPLEMENT_RTTI(TFCall, Expr)

public:
  static constexpr UhdmType kUhdmType = UhdmType::TFCall;

  explicit TFCall(Serializer *serializer) : basetype_t(serializer) {}
  TFCall(Serializer *serializer, const TFCall& rhs);
  ~TFCall() override = default;
  TFCall(const TFCall& rhs) = delete;
  TFCall& operator=(const TFCall& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view name);
  Identifier* getNameObj() { return m_name; }
  const Identifier* getNameObj() const { return m_name; }
  template <typename T> T* getNameObj() { return any_cast<T>(m_name); }
  template <typename T> const T* getNameObj() const { return any_cast<T>(m_name); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setNameObj(T, bool = false) = delete;
  bool setNameObj(Identifier* data, bool force = false) {
    if ((m_name == nullptr) || (data == nullptr) || force) {
      m_name = data;
      return true;
    }
    return false;
  }

  Scope* getScope() { return m_scope; }
  const Scope* getScope() const { return m_scope; }
  template <typename T> T* getScope() { return any_cast<T>(m_scope); }
  template <typename T> const T* getScope() const { return any_cast<T>(m_scope); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setScope(T, bool = false) = delete;
  bool setScope(Scope* data, bool force = false) {
    if ((m_scope == nullptr) || (data == nullptr) || force) {
      m_scope = data;
      return true;
    }
    return false;
  }

  TaskFunc* getTaskFunc() { return m_taskFunc; }
  const TaskFunc* getTaskFunc() const { return m_taskFunc; }
  template <typename T> T* getTaskFunc() { return any_cast<T>(m_taskFunc); }
  template <typename T> const T* getTaskFunc() const { return any_cast<T>(m_taskFunc); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTaskFunc(T, bool = false) = delete;
  bool setTaskFunc(TaskFunc* data, bool force = false) {
    if ((m_taskFunc == nullptr) || (data == nullptr) || force) {
      m_taskFunc = data;
      return true;
    }
    return false;
  }

  AnyCollection* getArguments() const { return m_arguments; }
  template<typename T> AnyCollection* getArguments(T) = delete;
  AnyCollection* getArguments(bool createIfNull);
  bool setArguments(AnyCollection* data, bool force = false) {
    if ((m_arguments == nullptr) || (data == nullptr) || force) {
      m_arguments = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiSysTfCall; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::TFCall; }


protected:
  Identifier* m_name = nullptr;
  Scope* m_scope = nullptr;
  TaskFunc* m_taskFunc = nullptr;
  AnyCollection* m_arguments = nullptr;
};
}  // namespace uhdm

#endif
