/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   typespec.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_TYPESPEC_H
#define UHDM_TYPESPEC_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/any.h>

namespace uhdm {
class Typespec : public Any {
  UHDM_IMPLEMENT_RTTI(Typespec, Any)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Typespec;

  explicit Typespec(Serializer *serializer) : basetype_t(serializer) {}
  Typespec(Serializer *serializer, const Typespec& rhs);
  ~Typespec() override = default;
  Typespec(const Typespec& rhs) = delete;
  Typespec& operator=(const Typespec& rhs) = delete;

  Instance* getInstance() { return m_instance; }
  const Instance* getInstance() const { return m_instance; }
  template <typename T> T* getInstance() { return any_cast<T>(m_instance); }
  template <typename T> const T* getInstance() const { return any_cast<T>(m_instance); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInstance(T, bool = false) = delete;
  bool setInstance(Instance* data, bool force = false) {
    if ((m_instance == nullptr) || (data == nullptr) || force) {
      m_instance = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiTypespec; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Typespec; }


protected:
  Instance* m_instance = nullptr;
};
}  // namespace uhdm

#endif
