/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   type_parameter.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_TYPE_PARAMETER_H
#define UHDM_TYPE_PARAMETER_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/typespec.h>

namespace uhdm {
class TypeParameter final : public Typespec {
  UHDM_IMPLEMENT_RTTI(TypeParameter, Typespec)

public:
  static constexpr UhdmType kUhdmType = UhdmType::TypeParameter;

  explicit TypeParameter(Serializer *serializer) : basetype_t(serializer) {}
  TypeParameter(Serializer *serializer, const TypeParameter& rhs);
  ~TypeParameter() override = default;
  TypeParameter(const TypeParameter& rhs) = delete;
  TypeParameter& operator=(const TypeParameter& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  std::string_view getFullName() const;
  bool setFullName(std::string_view data);

  bool getLocalParam() const { return m_localParam; }
  bool setLocalParam(bool data) {
    m_localParam = data;
    return true;
  }

  RefTypespec* getExpr() { return m_expr; }
  const RefTypespec* getExpr() const { return m_expr; }
  template <typename T> T* getExpr() { return any_cast<T>(m_expr); }
  template <typename T> const T* getExpr() const { return any_cast<T>(m_expr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setExpr(T, bool = false) = delete;
  bool setExpr(RefTypespec* data, bool force = false) {
    if ((m_expr == nullptr) || (data == nullptr) || force) {
      m_expr = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiTypeParameter; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::TypeParameter; }


protected:
  SymbolId m_name = BadSymbolId;
  SymbolId m_fullName = BadSymbolId;
  bool m_localParam = false;
  RefTypespec* m_expr = nullptr;
};
}  // namespace uhdm

#endif
