/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   udp_defn.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_UDP_DEFN_H
#define UHDM_UDP_DEFN_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/scope.h>

namespace uhdm {
class UdpDefn final : public Scope {
  UHDM_IMPLEMENT_RTTI(UdpDefn, Scope)

public:
  static constexpr UhdmType kUhdmType = UhdmType::UdpDefn;

  explicit UdpDefn(Serializer *serializer) : basetype_t(serializer) {}
  UdpDefn(Serializer *serializer, const UdpDefn& rhs);
  ~UdpDefn() override = default;
  UdpDefn(const UdpDefn& rhs) = delete;
  UdpDefn& operator=(const UdpDefn& rhs) = delete;

  int32_t getSize() const { return m_size; }
  bool setSize(int32_t data) {
    m_size = data;
    return true;
  }

  bool getProtected() const { return m_protected; }
  bool setProtected(bool data) {
    m_protected = data;
    return true;
  }

  int32_t getPrimType() const { return m_primType; }
  bool setPrimType(int32_t data) {
    m_primType = data;
    return true;
  }

  IODeclCollection* getIODecls() const { return m_iODecls; }
  template<typename T> IODeclCollection* getIODecls(T) = delete;
  IODeclCollection* getIODecls(bool createIfNull);
  bool setIODecls(IODeclCollection* data, bool force = false) {
    if ((m_iODecls == nullptr) || (data == nullptr) || force) {
      m_iODecls = data;
      return true;
    }
    return false;
  }

  TableEntryCollection* getTableEntries() const { return m_tableEntries; }
  template<typename T> TableEntryCollection* getTableEntries(T) = delete;
  TableEntryCollection* getTableEntries(bool createIfNull);
  bool setTableEntries(TableEntryCollection* data, bool force = false) {
    if ((m_tableEntries == nullptr) || (data == nullptr) || force) {
      m_tableEntries = data;
      return true;
    }
    return false;
  }

  Initial* getInitial() { return m_initial; }
  const Initial* getInitial() const { return m_initial; }
  template <typename T> T* getInitial() { return any_cast<T>(m_initial); }
  template <typename T> const T* getInitial() const { return any_cast<T>(m_initial); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInitial(T, bool = false) = delete;
  bool setInitial(Initial* data, bool force = false) {
    if ((m_initial == nullptr) || (data == nullptr) || force) {
      m_initial = data;
      return true;
    }
    return false;
  }

  std::string_view getEndLabel() const;
  bool setEndLabel(std::string_view name);
  Identifier* getEndLabelObj() { return m_endLabel; }
  const Identifier* getEndLabelObj() const { return m_endLabel; }
  template <typename T> T* getEndLabelObj() { return any_cast<T>(m_endLabel); }
  template <typename T> const T* getEndLabelObj() const { return any_cast<T>(m_endLabel); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setEndLabelObj(T, bool = false) = delete;
  bool setEndLabelObj(Identifier* data, bool force = false) {
    if ((m_endLabel == nullptr) || (data == nullptr) || force) {
      m_endLabel = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiUdpDefn; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::UdpDefn; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  int32_t m_size = 0;
  bool m_protected = false;
  int32_t m_primType = 0;
  IODeclCollection* m_iODecls = nullptr;
  TableEntryCollection* m_tableEntries = nullptr;
  Initial* m_initial = nullptr;
  Identifier* m_endLabel = nullptr;
};
}  // namespace uhdm

#endif
