/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   unsupported_typespec.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_UNSUPPORTED_TYPESPEC_H
#define UHDM_UNSUPPORTED_TYPESPEC_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/typespec.h>

namespace uhdm {
class UnsupportedTypespec final : public Typespec {
  UHDM_IMPLEMENT_RTTI(UnsupportedTypespec, Typespec)

public:
  static constexpr UhdmType kUhdmType = UhdmType::UnsupportedTypespec;

  explicit UnsupportedTypespec(Serializer *serializer) : basetype_t(serializer) {}
  UnsupportedTypespec(Serializer *serializer, const UnsupportedTypespec& rhs);
  ~UnsupportedTypespec() override = default;
  UnsupportedTypespec(const UnsupportedTypespec& rhs) = delete;
  UnsupportedTypespec& operator=(const UnsupportedTypespec& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view name);
  Identifier* getNameObj() { return m_name; }
  const Identifier* getNameObj() const { return m_name; }
  template <typename T> T* getNameObj() { return any_cast<T>(m_name); }
  template <typename T> const T* getNameObj() const { return any_cast<T>(m_name); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setNameObj(T, bool = false) = delete;
  bool setNameObj(Identifier* data, bool force = false) {
    if ((m_name == nullptr) || (data == nullptr) || force) {
      m_name = data;
      return true;
    }
    return false;
  }

  bool getPacked() const { return m_packed; }
  bool setPacked(bool data) {
    m_packed = data;
    return true;
  }

  RangeCollection* getRanges() const { return m_ranges; }
  template<typename T> RangeCollection* getRanges(T) = delete;
  RangeCollection* getRanges(bool createIfNull);
  bool setRanges(RangeCollection* data, bool force = false) {
    if ((m_ranges == nullptr) || (data == nullptr) || force) {
      m_ranges = data;
      return true;
    }
    return false;
  }

  ParamAssignCollection* getParamAssigns() const { return m_paramAssigns; }
  template<typename T> ParamAssignCollection* getParamAssigns(T) = delete;
  ParamAssignCollection* getParamAssigns(bool createIfNull);
  bool setParamAssigns(ParamAssignCollection* data, bool force = false) {
    if ((m_paramAssigns == nullptr) || (data == nullptr) || force) {
      m_paramAssigns = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiUnsupportedTypespec; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::UnsupportedTypespec; }

 protected:
  void onChildAdded(Any* child) override;
  void onChildRemoved(Any* child) override;

protected:
  Identifier* m_name = nullptr;
  bool m_packed = false;
  RangeCollection* m_ranges = nullptr;
  ParamAssignCollection* m_paramAssigns = nullptr;
};
}  // namespace uhdm

#endif
