/*
 Do not modify, auto-generated by classes.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   variable.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef UHDM_VARIABLE_H
#define UHDM_VARIABLE_H

#include <uhdm/sv_vpi_user.h>
#include <uhdm/uhdm_vpi_user.h>

#include <uhdm/containers.h>
#include <uhdm/simple_expr.h>

namespace uhdm {
class Variable final : public SimpleExpr {
  UHDM_IMPLEMENT_RTTI(Variable, SimpleExpr)

public:
  static constexpr UhdmType kUhdmType = UhdmType::Variable;

  explicit Variable(Serializer *serializer) : basetype_t(serializer) {}
  Variable(Serializer *serializer, const Variable& rhs);
  ~Variable() override = default;
  Variable(const Variable& rhs) = delete;
  Variable& operator=(const Variable& rhs) = delete;

  std::string_view getName() const override;
  bool setName(std::string_view data);

  std::string_view getFullName() const;
  bool setFullName(std::string_view data);

  bool getArrayMember() const { return m_arrayMember; }
  bool setArrayMember(bool data) {
    m_arrayMember = data;
    return true;
  }

  bool getAutomatic() const { return m_automatic; }
  bool setAutomatic(bool data) {
    m_automatic = data;
    return true;
  }

  int32_t getAllocScheme() const { return m_allocScheme; }
  bool setAllocScheme(int32_t data) {
    m_allocScheme = data;
    return true;
  }

  bool getConstantVariable() const { return m_constantVariable; }
  bool setConstantVariable(bool data) {
    m_constantVariable = data;
    return true;
  }

  bool getIsRandomized() const { return m_isRandomized; }
  bool setIsRandomized(bool data) {
    m_isRandomized = data;
    return true;
  }

  int32_t getRandType() const { return m_randType; }
  bool setRandType(int32_t data) {
    m_randType = data;
    return true;
  }

  int32_t getNetType() const { return m_netType; }
  bool setNetType(int32_t data) {
    m_netType = data;
    return true;
  }

  bool getStructUnionMember() const { return m_structUnionMember; }
  bool setStructUnionMember(bool data) {
    m_structUnionMember = data;
    return true;
  }

  bool getScalar() const { return m_scalar; }
  bool setScalar(bool data) {
    m_scalar = data;
    return true;
  }

  int32_t getVisibility() const { return m_visibility; }
  bool setVisibility(int32_t data) {
    m_visibility = data;
    return true;
  }

  bool getVector() const { return m_vector; }
  bool setVector(bool data) {
    m_vector = data;
    return true;
  }

  PortsCollection* getPortInsts() const { return m_portInsts; }
  template<typename T> PortsCollection* getPortInsts(T) = delete;
  PortsCollection* getPortInsts(bool createIfNull);
  bool setPortInsts(PortsCollection* data, bool force = false) {
    if ((m_portInsts == nullptr) || (data == nullptr) || force) {
      m_portInsts = data;
      return true;
    }
    return false;
  }

  AnyCollection* getDrivers() const { return m_drivers; }
  template<typename T> AnyCollection* getDrivers(T) = delete;
  AnyCollection* getDrivers(bool createIfNull);
  bool setDrivers(AnyCollection* data, bool force = false) {
    if ((m_drivers == nullptr) || (data == nullptr) || force) {
      m_drivers = data;
      return true;
    }
    return false;
  }

  AnyCollection* getLoads() const { return m_loads; }
  template<typename T> AnyCollection* getLoads(T) = delete;
  AnyCollection* getLoads(bool createIfNull);
  bool setLoads(AnyCollection* data, bool force = false) {
    if ((m_loads == nullptr) || (data == nullptr) || force) {
      m_loads = data;
      return true;
    }
    return false;
  }

  PrimTermCollection* getPrimTerms() const { return m_primTerms; }
  template<typename T> PrimTermCollection* getPrimTerms(T) = delete;
  PrimTermCollection* getPrimTerms(bool createIfNull);
  bool setPrimTerms(PrimTermCollection* data, bool force = false) {
    if ((m_primTerms == nullptr) || (data == nullptr) || force) {
      m_primTerms = data;
      return true;
    }
    return false;
  }

  ContAssignCollection* getContAssigns() const { return m_contAssigns; }
  template<typename T> ContAssignCollection* getContAssigns(T) = delete;
  ContAssignCollection* getContAssigns(bool createIfNull);
  bool setContAssigns(ContAssignCollection* data, bool force = false) {
    if ((m_contAssigns == nullptr) || (data == nullptr) || force) {
      m_contAssigns = data;
      return true;
    }
    return false;
  }

  PathTerm* getPathTerm() { return m_pathTerm; }
  const PathTerm* getPathTerm() const { return m_pathTerm; }
  template <typename T> T* getPathTerm() { return any_cast<T>(m_pathTerm); }
  template <typename T> const T* getPathTerm() const { return any_cast<T>(m_pathTerm); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setPathTerm(T, bool = false) = delete;
  bool setPathTerm(PathTerm* data, bool force = false) {
    if ((m_pathTerm == nullptr) || (data == nullptr) || force) {
      m_pathTerm = data;
      return true;
    }
    return false;
  }

  TchkTerm* getTchkTerm() { return m_tchkTerm; }
  const TchkTerm* getTchkTerm() const { return m_tchkTerm; }
  template <typename T> T* getTchkTerm() { return any_cast<T>(m_tchkTerm); }
  template <typename T> const T* getTchkTerm() const { return any_cast<T>(m_tchkTerm); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setTchkTerm(T, bool = false) = delete;
  bool setTchkTerm(TchkTerm* data, bool force = false) {
    if ((m_tchkTerm == nullptr) || (data == nullptr) || force) {
      m_tchkTerm = data;
      return true;
    }
    return false;
  }

  Module* getModule() { return m_module; }
  const Module* getModule() const { return m_module; }
  template <typename T> T* getModule() { return any_cast<T>(m_module); }
  template <typename T> const T* getModule() const { return any_cast<T>(m_module); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setModule(T, bool = false) = delete;
  bool setModule(Module* data, bool force = false) {
    if ((m_module == nullptr) || (data == nullptr) || force) {
      m_module = data;
      return true;
    }
    return false;
  }

  Instance* getInstance() { return m_instance; }
  const Instance* getInstance() const { return m_instance; }
  template <typename T> T* getInstance() { return any_cast<T>(m_instance); }
  template <typename T> const T* getInstance() const { return any_cast<T>(m_instance); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setInstance(T, bool = false) = delete;
  bool setInstance(Instance* data, bool force = false) {
    if ((m_instance == nullptr) || (data == nullptr) || force) {
      m_instance = data;
      return true;
    }
    return false;
  }

  Scope* getScope() { return m_scope; }
  const Scope* getScope() const { return m_scope; }
  template <typename T> T* getScope() { return any_cast<T>(m_scope); }
  template <typename T> const T* getScope() const { return any_cast<T>(m_scope); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setScope(T, bool = false) = delete;
  bool setScope(Scope* data, bool force = false) {
    if ((m_scope == nullptr) || (data == nullptr) || force) {
      m_scope = data;
      return true;
    }
    return false;
  }

  Expr* getExpr() { return m_expr; }
  const Expr* getExpr() const { return m_expr; }
  template <typename T> T* getExpr() { return any_cast<T>(m_expr); }
  template <typename T> const T* getExpr() const { return any_cast<T>(m_expr); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setExpr(T, bool = false) = delete;
  bool setExpr(Expr* data, bool force = false) {
    if ((m_expr == nullptr) || (data == nullptr) || force) {
      m_expr = data;
      return true;
    }
    return false;
  }

  ExprCollection* getIndexes() const { return m_indexes; }
  template<typename T> ExprCollection* getIndexes(T) = delete;
  ExprCollection* getIndexes(bool createIfNull);
  bool setIndexes(ExprCollection* data, bool force = false) {
    if ((m_indexes == nullptr) || (data == nullptr) || force) {
      m_indexes = data;
      return true;
    }
    return false;
  }

  Expr* getValue() { return m_value; }
  const Expr* getValue() const { return m_value; }
  template <typename T> T* getValue() { return any_cast<T>(m_value); }
  template <typename T> const T* getValue() const { return any_cast<T>(m_value); }
  template <typename T,
            typename = typename std::enable_if_t<!std::is_base_of_v<Any, std::remove_pointer_t<T>> &&
                                                 !std::is_same<T, std::nullptr_t>::value>>
  bool setValue(T, bool = false) = delete;
  bool setValue(Expr* data, bool force = false) {
    if ((m_value == nullptr) || (data == nullptr) || force) {
      m_value = data;
      return true;
    }
    return false;
  }

  uint32_t getVpiType() const override { return vpiVariable; }
  const Any* getByVpiName(std::string_view name) const override;
  get_by_vpi_type_return_t getByVpiType(int32_t type) const override;
  vpi_property_value_t getVpiPropertyValue(int32_t property) const override;

  int32_t compare(const Any* other, UhdmComparer* comparer) const override;

  using basetype_t::isFiltered;
  bool isFiltered(const Any *data, int32_t relation) const override;

  void swap(const Any* what, Any* with) override;
  void swap(const AnyMap<Any*>& replacements) override;

  UhdmType getUhdmType() const override { return UhdmType::Variable; }


protected:
  SymbolId m_name = BadSymbolId;
  SymbolId m_fullName = BadSymbolId;
  bool m_arrayMember = false;
  bool m_automatic = false;
  int32_t m_allocScheme = 0;
  bool m_constantVariable = false;
  bool m_isRandomized = false;
  int32_t m_randType = 0;
  int32_t m_netType = 0;
  bool m_structUnionMember = false;
  bool m_scalar = false;
  int32_t m_visibility = 0;
  bool m_vector = false;
  PortsCollection* m_portInsts = nullptr;
  AnyCollection* m_drivers = nullptr;
  AnyCollection* m_loads = nullptr;
  PrimTermCollection* m_primTerms = nullptr;
  ContAssignCollection* m_contAssigns = nullptr;
  PathTerm* m_pathTerm = nullptr;
  TchkTerm* m_tchkTerm = nullptr;
  Module* m_module = nullptr;
  Instance* m_instance = nullptr;
  Scope* m_scope = nullptr;
  Expr* m_expr = nullptr;
  ExprCollection* m_indexes = nullptr;
  Expr* m_value = nullptr;
};
}  // namespace uhdm

#endif
