/*
 Copyright 2020 Apotell

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// ============================================================================
// SystemVerilog source under test:
//   tests/Google/chapter-21/21.6--value.sv   (:name: value_plusargs,
//   :description: $value$plusargs test, :tags: 21.6,
//   :type: simulation parsing)
// ----------------------------------------------------------------------------
//   module top();
//
//   integer i;
//
//   initial begin
//       if ($value$plusargs("TEST=%d", i)) $display("i=%d", i);
//       else
//           $display("TEST not found");
//   end
//
//   endmodule
// ============================================================================
//
// IEEE 1800-2023 constructs present in this file, and what each one pins down
// statically (all of this was derived by reading the .sv text above and the
// LRM; nothing here was taken from tool output):
//
//   Sec 6.11.1 "Integer data types" -- "integer" is a 4-state 32-bit SIGNED
//       type, and an integer_atom_type in the Sec 6.8 variable declaration
//       grammar, never a net_type (Sec 6.7). "i" is a Variable, and it is the
//       file's only declaration.
//   Sec 9.2.2 "Initial procedures" / Sec 9.3.1 "Sequential blocks" -- the one
//       "initial begin ... end" gives exactly one Initial process whose body
//       is a Begin. Nothing is declared inside the block, so "i" resolves
//       outward to the module scope.
//   Sec 12.4 "Conditional if-else statement" -- the whole if/else is ONE
//       statement_or_null, so the Begin holds exactly one entry. Because a
//       trailing "else" is written, the model's node kind is the if-with-else
//       form rather than the bare if form. Neither arm is written with
//       begin/end -- the else's body simply sits on the following line, which
//       changes nothing about the grammar -- so each arm is a single
//       statement_or_null that must bind directly and must NOT be wrapped in
//       a Begin.
//   Sec 12.4.2 "Violation reports generated by unique-if and priority-if
//       constructs" -- no "unique", "unique0" or "priority" keyword precedes
//       the "if", so the statement carries no such qualifier.
//   Sec 21.6 "Command line input" -- this is the clause the file is named
//       for, and the contrast with its sibling 21.6--test.sv is the whole
//       point. Both routines are system FUNCTIONS returning nonzero on a
//       match, which is why either can stand as an if condition and why
//       neither may be a SysTaskCall. They differ in what else they do:
//           $test$plusargs (string)                 -- one argument, reports
//                                                      only whether a plusarg
//                                                      matched.
//           $value$plusargs (user_string, variable) -- TWO arguments; on a
//                                                      match it also EXTRACTS
//                                                      the value and writes it
//                                                      into the variable.
//       So this call must carry exactly two arguments, and the second must be
//       a REFERENCE to a declared object -- a destination cannot be a
//       literal. The user_string carries a format specification ("%d") which
//       tells the routine how to convert the text it finds.
//   Sec 21.2.1 "$display and $write" -- $display is a system TASK, hence a
//       SysTaskCall. Here the two arms differ not only in their text but in
//       their ARGUMENT COUNT: the then-arm prints a format plus the value it
//       just extracted (two arguments), while the else-arm prints a bare
//       message (one argument).
//   Sec 5.9 "String literals" -- a string literal is an unsigned integer
//       constant 8 bits wide per character: "TEST=%d" is 7 * 8 = 56 bits,
//       "i=%d" is 4 * 8 = 32 bits and "TEST not found" is 14 * 8 = 112 bits.
//
// ----------------------------------------------------------------------------
// WHAT IS CHECKED (every assertion below names a concrete value):
//   - module "top" exists, has no Nets, no ports, no parameters and no
//     continuous assignments, and declares exactly ONE Variable, "i",
//     resolving to an IntegerTypespec with no declaration initializer.
//   - "top" has exactly one process, and it is an Initial and explicitly not
//     a FinalStmt.
//   - the Initial's body is a Begin that declares no variables of its own and
//     holds exactly ONE statement, because Sec 12.4 makes the whole if/else a
//     single statement.
//   - that statement is an IfElse -- the form that carries an else-branch,
//     explicitly not the bare IfStmt -- and its getQualifier() is
//     vpiNoQualifier, since no unique/unique0/priority keyword is written.
//   - its condition is a SysFuncCall named "$value$plusargs" and explicitly
//     NOT a SysTaskCall, carrying exactly TWO arguments: a Constant with
//     constType vpiStringConst, value "TEST=%d" and size 56 bits, then a
//     RefObj named "i" bound by object identity to the declared Variable.
//   - that second argument is explicitly NOT a Constant: Sec 21.6 makes it
//     the destination the extracted value is written into, and a destination
//     must be a reference to a declared object. This two-argument,
//     writes-a-destination shape is exactly what separates $value$plusargs
//     from the one-argument $test$plusargs of the sibling fixture.
//   - its then-branch binds DIRECTLY to a SysTaskCall named "$display" with
//     no Begin wrapper, carrying exactly TWO arguments: a vpiStringConst
//     Constant "i=%d" of size 32 bits, then a RefObj "i" bound to the same
//     declared Variable.
//   - its else-branch binds DIRECTLY to a SysTaskCall named "$display" with
//     no Begin wrapper, carrying exactly ONE argument: a vpiStringConst
//     Constant "TEST not found" of size 112 bits.
//   - the two $display calls are two DISTINCT nodes, and they differ in
//     argument count as well as in text, so a model that folded the two arms
//     together would fail on both counts.
//   - the compiler reports zero fatal / syntax / error diagnostics: every
//     construct above is legal per the clauses cited, and the source carries
//     no ":should_fail_because:" tag.
//
// ----------------------------------------------------------------------------
// WHAT IS NOT CHECKED, AND WHY (permanently out of scope -- HLC is a static
// compiler/elaborator and never a simulator):
//   - Which branch is taken. Sec 21.6 makes $value$plusargs's result depend on
//     the command line the simulation is invoked with, so the answer does not
//     exist until something runs. Nothing in the model records a call's
//     result. The nearest real assertion is
//     IfConditionIsValuePlusargsMatchingTestEqualsPercentD, which pins the
//     query that would be asked.
//   - The value extracted into "i". It exists only once the call runs;
//     Variable::getValue() exposes only a declaration-time initializer, and
//     "integer i;" has none, so no field anywhere records a post-call value.
//     The nearest real assertion is
//     ValuePlusargsSecondArgumentIsTheDestinationVariable, which pins which
//     declared object the value would be written into.
//   - What "%d" means when the call runs -- consuming and converting a
//     decimal field -- and likewise what "%d" means to $display. Interpreting
//     a format specification is work done while time advances. What the
//     source DOES determine is the exact text of all three literals, and all
//     three are asserted verbatim.
//   - The printed output itself and any trailing newline. Formatting happens
//     while time advances. The nearest real assertions are
//     ThenBranchDisplaysTheExtractedValue and
//     ElseBranchDisplaysTestNotFound.
//   - Whether a plusarg matching "TEST=" was in fact supplied. That is a
//     property of how the simulation is launched, not of this source file.
//   - The Begin's own name. No ": label" is written, so the block is unnamed;
//     whether the model leaves the name empty or synthesizes an implicit
//     scope name is a tool-internal convention the source does not determine.
//     The scoping fact that matters is asserted instead, by
//     InitialBodyIsBeginWithExactlyOneStatement, which requires the block to
//     own no variables of its own.
//   - The design-level typespec collection's size and which scope owns the
//     shared IntegerTypespec / string typespec nodes. Typespec sharing is
//     likewise a tool-internal convention that the source text does not
//     determine.
//   - The warning count. Whether a legal file also draws advisory warnings is
//     tool policy, not something the LRM fixes, so only the fatal/syntax/
//     error counts are asserted below.
//
// No getElaborated() gating is used anywhere in this file. That is the
// correct answer here rather than an omission: the fixture has no parameters,
// no constant expressions needing reduction, no generate constructs and no
// module instantiations, so nothing in it comes into existence only after
// elaboration. Every value asserted below is established by parsing and name
// resolution alone.
// ============================================================================

#include <hlc/Common/Session.h>
#include <hlc/ErrorReporting/ErrorContainer.h>
#include <hlc/SourceCompile/Compiler.h>
#include <hlc/Tests/Test.h>

#include <hldb/Utils.h>
#include <hldb/any_type.h>
#include <hldb/begin.h>
#include <hldb/constant.h>
#include <hldb/design.h>
#include <hldb/final_stmt.h>
#include <hldb/if_else.h>
#include <hldb/if_stmt.h>
#include <hldb/initial.h>
#include <hldb/integer_typespec.h>
#include <hldb/module.h>
#include <hldb/net.h>
#include <hldb/process_stmt.h>
#include <hldb/ref_obj.h>
#include <hldb/ref_typespec.h>
#include <hldb/sys_func_call.h>
#include <hldb/sys_task_call.h>
#include <hldb/variable.h>
#include <hldb/vpi_user.h>

namespace hlc {

class ValuePlusargsTest : public Test {
 public:
  static void SetUpTestSuite() { Compile(__FILE__, {"-f", "21.6--value.hlc"}); }
  static void TearDownTestSuite() { Shutdown(); }

 protected:
  static const hldb::Module *getTop() { return hldb::findByName<hldb::Module>("top", m_design->getAllModules()); }

  // "integer i;" -- the file's one and only declaration.
  static const hldb::Variable *getI() {
    const hldb::Module *const top = getTop();
    if (top == nullptr) return nullptr;
    return hldb::findByName<hldb::Variable>("i", top->getVariables());
  }

  // "initial begin ... end" -- the module's only process.
  static const hldb::Begin *getInitialBody() {
    const hldb::Module *const top = getTop();
    if (top == nullptr || top->getProcesses() == nullptr || top->getProcesses()->empty()) return nullptr;
    const hldb::Initial *const init = any_cast<hldb::Initial>(top->getProcesses()->at(0));
    return (init == nullptr) ? nullptr : init->getStmt<hldb::Begin>();
  }

  // Sec 12.4: the whole if/else is the block's single statement, and because
  // a trailing "else" is written it takes the if-with-else form.
  static const hldb::IfElse *getIfElse() {
    const hldb::Begin *const body = getInitialBody();
    if (body == nullptr || body->getStmts() == nullptr || body->getStmts()->empty()) return nullptr;
    return any_cast<hldb::IfElse>(body->getStmts()->at(0));
  }

  // Every reference in this file names the one declared variable "i". This
  // checks that a given argument is bound to it, not merely spelled alike.
  static void checkArgumentIsI(const hldb::Any *argument, const char *where) {
    const hldb::RefObj *const ref = any_cast<hldb::RefObj>(argument);
    ASSERT_NE(ref, nullptr) << where << " should be a RefObj";
    EXPECT_EQ(ref->getName(), "i");
    EXPECT_EQ(ref->getActual<hldb::Variable>(), getI()) << where << " must bind to the one declared Variable 'i'";
  }

  // Sec 5.9: a string literal is 8 bits per character.
  static void checkStringLiteral(const hldb::Any *argument, const char *expectedText, int32_t expectedSize,
                                 const char *where) {
    const hldb::Constant *const literal = any_cast<hldb::Constant>(argument);
    ASSERT_NE(literal, nullptr) << where << " should be a Constant";
    EXPECT_EQ(literal->getConstType(), vpiStringConst) << where;
    EXPECT_EQ(literal->getValue(), expectedText) << where;
    EXPECT_EQ(literal->getSize(), expectedSize) << where << ": Sec 5.9 -- 8 bits per character";
  }
};

// --- module scope and its single declaration ---------------------------------

TEST_F(ValuePlusargsTest, ModuleTopExists) { EXPECT_NE(getTop(), nullptr); }

// Sec 6.7 lists the net_type keywords; "integer" is not one of them, and
// "module top();" has an empty port list, so nothing here declares a net or
// drives one continuously.
TEST_F(ValuePlusargsTest, ModuleHasNoNetsNoPortsNoParametersAndNoContinuousAssignments) {
  const hldb::Module *const top = getTop();
  ASSERT_NE(top, nullptr);
  EXPECT_TRUE(top->getNets() == nullptr || top->getNets()->empty())
      << "'integer' is not a net-type keyword (IEEE 1800-2023 Sec 6.7)";
  EXPECT_TRUE(top->getPorts() == nullptr || top->getPorts()->empty()) << "'module top();' has an empty port list";
  EXPECT_TRUE(top->getParameters() == nullptr || top->getParameters()->empty())
      << "no parameter is declared anywhere in this file";
  EXPECT_TRUE(top->getContAssigns() == nullptr || top->getContAssigns()->empty())
      << "the file contains no 'assign' statement";
}

// Sec 6.11.1: "integer" is the 4-state 32-bit signed type, and it is the only
// object this file declares -- unlike the sibling 21.6--test.sv, which
// declares nothing at all because $test$plusargs needs no destination.
TEST_F(ValuePlusargsTest, ModuleHasExactlyOneIntegerVariableI) {
  const hldb::Module *const top = getTop();
  ASSERT_NE(top, nullptr);
  ASSERT_NE(top->getVariables(), nullptr) << "'integer i;' must be a Variable (Sec 6.8)";
  ASSERT_EQ(top->getVariables()->size(), 1u) << "'integer i;' is the file's only declaration";

  const hldb::Variable *const i = getI();
  ASSERT_NE(i, nullptr);
  ASSERT_NE(i->getTypespec<hldb::RefTypespec>(), nullptr);
  EXPECT_NE(i->getTypespec<hldb::RefTypespec>()->getActual<hldb::IntegerTypespec>(), nullptr)
      << "Sec 6.11.1: 'integer' is the 4-state type, so it must resolve to an IntegerTypespec, not an "
         "IntTypespec";
  EXPECT_EQ(i->getValue(), nullptr) << "'integer i;' is declared with no '=' initializer";
}

// --- the single procedure -----------------------------------------------------

// Sec 9.2.2: one "initial" keyword, one Initial process -- and nothing else.
TEST_F(ValuePlusargsTest, ModuleHasExactlyOneInitialProcess) {
  const hldb::Module *const top = getTop();
  ASSERT_NE(top, nullptr);
  ASSERT_NE(top->getProcesses(), nullptr);
  ASSERT_EQ(top->getProcesses()->size(), 1u) << "the file writes exactly one procedure";
  EXPECT_NE(any_cast<hldb::Initial>(top->getProcesses()->at(0)), nullptr) << "that procedure is an 'initial'";
  EXPECT_EQ(any_cast<hldb::FinalStmt>(top->getProcesses()->at(0)), nullptr)
      << "no 'final' keyword is written in this file";
}

// Sec 12.4: the whole "if ... else ..." is ONE statement_or_null, so the block
// holds one entry -- not one for the if and another for the else.
TEST_F(ValuePlusargsTest, InitialBodyIsBeginWithExactlyOneStatement) {
  const hldb::Begin *const body = getInitialBody();
  ASSERT_NE(body, nullptr) << "'initial begin ... end' body should be a Begin";
  EXPECT_TRUE(body->getVariables() == nullptr || body->getVariables()->empty())
      << "no block_item_declaration is written inside the begin-end (Sec 9.3.1); 'i' resolves outward "
         "to the module scope";
  ASSERT_NE(body->getStmts(), nullptr);
  EXPECT_EQ(body->getStmts()->size(), 1u)
      << "Sec 12.4: the if and its else are a single statement, so the block holds one entry, not two";
}

// --- the conditional ----------------------------------------------------------

// Sec 12.4: a trailing "else" is written, so this is the if-with-else form,
// not the bare if. Sec 12.4.2: no unique/unique0/priority keyword precedes it.
TEST_F(ValuePlusargsTest, StatementIsAnUnqualifiedIfElse) {
  const hldb::Begin *const body = getInitialBody();
  ASSERT_NE(body, nullptr);
  ASSERT_NE(body->getStmts(), nullptr);
  ASSERT_EQ(body->getStmts()->size(), 1u);

  EXPECT_EQ(any_cast<hldb::IfStmt>(body->getStmts()->at(0)), nullptr)
      << "Sec 12.4: an 'else' branch is written, so this is not the bare if form";
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr) << "the block's one statement should be an IfElse";
  EXPECT_EQ(ifElse->getQualifier(), vpiNoQualifier)
      << "Sec 12.4.2: no unique/unique0/priority keyword precedes this if";
}

// THE POINT OF THIS FIXTURE. Sec 21.6: $value$plusargs returns nonzero on a
// match -- which is why it can be a condition at all, and why it is a system
// function -- and takes the user_string first.
TEST_F(ValuePlusargsTest, IfConditionIsValuePlusargsMatchingTestEqualsPercentD) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);

  EXPECT_EQ(ifElse->getCondition<hldb::SysTaskCall>(), nullptr)
      << "IEEE 1800-2023 Sec 21.6: $value$plusargs returns a value -- that is why it can be a "
         "condition at all -- so it is a system function, not a system task";
  const hldb::SysFuncCall *const cond = ifElse->getCondition<hldb::SysFuncCall>();
  ASSERT_NE(cond, nullptr) << "the condition should be a SysFuncCall";
  EXPECT_EQ(cond->getName(), "$value$plusargs")
      << "Sec 21.6 spells the name with two dollar signs, and it is not '$test$plusargs' -- the two "
         "routines differ in whether they extract a value";

  ASSERT_NE(cond->getArguments(), nullptr);
  ASSERT_EQ(cond->getArguments()->size(), 2u)
      << "Sec 21.6: '$value$plusargs(user_string, variable)' takes TWO arguments, unlike the "
         "one-argument $test$plusargs of the sibling fixture";
  checkStringLiteral(cond->getArguments()->at(0), "TEST=%d", 56, "the $value$plusargs user_string");
}

// Sec 21.6: on a match the routine writes the extracted value INTO the second
// argument, so that argument is a destination and must be a reference to a
// declared object -- it cannot be a literal. This is the structural
// consequence that separates $value$plusargs from $test$plusargs.
TEST_F(ValuePlusargsTest, ValuePlusargsSecondArgumentIsTheDestinationVariable) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);
  const hldb::SysFuncCall *const cond = ifElse->getCondition<hldb::SysFuncCall>();
  ASSERT_NE(cond, nullptr);
  ASSERT_NE(cond->getArguments(), nullptr);
  ASSERT_EQ(cond->getArguments()->size(), 2u);

  EXPECT_EQ(any_cast<hldb::Constant>(cond->getArguments()->at(1)), nullptr)
      << "Sec 21.6: the second argument is the destination the extracted value is written into, so it "
         "must be a reference to a declared object and never a literal";
  checkArgumentIsI(cond->getArguments()->at(1), "the $value$plusargs destination argument");
}

// --- the two arms -------------------------------------------------------------

// Sec 12.4: the then-arm is a single statement_or_null written without
// begin/end, so it must bind directly. Sec 21.2.1: $display is a task, and
// here it prints the value just extracted, so it carries two arguments.
TEST_F(ValuePlusargsTest, ThenBranchDisplaysTheExtractedValue) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);
  EXPECT_EQ(ifElse->getStmt<hldb::Begin>(), nullptr)
      << "Sec 12.4: no begin/end was written on the then-branch, so it must not be wrapped in a Begin";
  EXPECT_EQ(ifElse->getStmt<hldb::SysFuncCall>(), nullptr)
      << "IEEE 1800-2023 Sec 21.2.1: $display returns nothing, so it is a system task";

  const hldb::SysTaskCall *const call = ifElse->getStmt<hldb::SysTaskCall>();
  ASSERT_NE(call, nullptr) << "the then-branch should be a $display SysTaskCall";
  EXPECT_EQ(call->getName(), "$display");
  ASSERT_NE(call->getArguments(), nullptr);
  ASSERT_EQ(call->getArguments()->size(), 2u) << "'$display(\"i=%d\", i)' passes a format string and one value";
  checkStringLiteral(call->getArguments()->at(0), "i=%d", 32, "the then-branch format string");
  checkArgumentIsI(call->getArguments()->at(1), "the then-branch printed value");
}

// Sec 12.4: likewise for the else-arm -- writing its body on the next line
// changes nothing about the grammar, so it too binds directly. It prints a
// bare message, so it carries one argument and no value.
TEST_F(ValuePlusargsTest, ElseBranchDisplaysTestNotFound) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);
  ASSERT_NE(ifElse->getElseStmt(), nullptr) << "Sec 12.4: an 'else' branch is written, so one must be present";
  EXPECT_EQ(ifElse->getElseStmt<hldb::Begin>(), nullptr)
      << "Sec 12.4: no begin/end was written on the else-branch -- putting its body on the next line "
         "does not create one";
  EXPECT_EQ(ifElse->getElseStmt<hldb::SysFuncCall>(), nullptr)
      << "IEEE 1800-2023 Sec 21.2.1: $display returns nothing, so it is a system task";

  const hldb::SysTaskCall *const call = ifElse->getElseStmt<hldb::SysTaskCall>();
  ASSERT_NE(call, nullptr) << "the else-branch should be a $display SysTaskCall";
  EXPECT_EQ(call->getName(), "$display");
  ASSERT_NE(call->getArguments(), nullptr);
  ASSERT_EQ(call->getArguments()->size(), 1u) << "'$display(\"TEST not found\")' passes only the message";
  checkStringLiteral(call->getArguments()->at(0), "TEST not found", 112, "the else-branch message");
}

// The two arms are separately written calls, and here they differ in argument
// count as well as in text -- so a model that folded the branches together
// would fail on both counts.
TEST_F(ValuePlusargsTest, TheTwoArmsAreDistinctCallsWithDifferentArgumentCounts) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);

  const hldb::SysTaskCall *const thenCall = ifElse->getStmt<hldb::SysTaskCall>();
  const hldb::SysTaskCall *const elseCall = ifElse->getElseStmt<hldb::SysTaskCall>();
  ASSERT_NE(thenCall, nullptr);
  ASSERT_NE(elseCall, nullptr);
  EXPECT_NE(thenCall, elseCall) << "the two branches are two separately written calls and must be two "
                                   "separate nodes";

  ASSERT_NE(thenCall->getArguments(), nullptr);
  ASSERT_NE(elseCall->getArguments(), nullptr);
  EXPECT_EQ(thenCall->getArguments()->size(), 2u) << "the then-arm prints the extracted value alongside its format";
  EXPECT_EQ(elseCall->getArguments()->size(), 1u) << "the else-arm has no value to print";

  const hldb::Constant *const thenText = any_cast<hldb::Constant>(thenCall->getArguments()->at(0));
  const hldb::Constant *const elseText = any_cast<hldb::Constant>(elseCall->getArguments()->at(0));
  ASSERT_NE(thenText, nullptr);
  ASSERT_NE(elseText, nullptr);
  EXPECT_NE(thenText->getValue(), elseText->getValue()) << "the two arms print different text";
}

// --- compiler diagnostics -----------------------------------------------------

// The source carries no ":should_fail_because:" tag and every construct in it
// is legal per the clauses cited above, so nothing may be reported as an
// error. (The warning count is deliberately not asserted -- see the header.)
TEST_F(ValuePlusargsTest, CompilerReportsZeroErrors) {
  ASSERT_NE(m_session->getErrorContainer(), nullptr);
  const ErrorContainer::Stats stats = m_session->getErrorContainer()->getErrorStats();
  EXPECT_EQ(stats.nbFatal, 0);
  EXPECT_EQ(stats.nbSyntax, 0);
  EXPECT_EQ(stats.nbError, 0);
}

}  // namespace hlc

int main(int argc, char **argv) {
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
