/*
 Copyright 2020 Apotell

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

// ============================================================================
// SystemVerilog source under test:
//   tests/Google/chapter-21/21.6--test.sv   (:name: test_plusargs,
//   :description: $test$plusargs test, :tags: 21.6,
//   :type: simulation parsing)
// ----------------------------------------------------------------------------
//   module top();
//
//   initial begin
//       if ($test$plusargs("TEST")) $display("TEST argument found");
//       else $display("TEST argument not found");
//   end
//
//   endmodule
// ============================================================================
//
// IEEE 1800-2023 constructs present in this file, and what each one pins down
// statically (all of this was derived by reading the .sv text above and the
// LRM; nothing here was taken from tool output):
//
//   Sec 9.2.2 "Initial procedures" / Sec 9.3.1 "Sequential blocks" -- the one
//       "initial begin ... end" gives exactly one Initial process whose body
//       is a Begin. Nothing is declared anywhere in this file: the module has
//       no ports, no nets, no variables and no parameters, and the block
//       declares nothing of its own either. This is the leanest fixture in
//       chapter 21 -- everything it has to say is in the shape of one
//       statement.
//   Sec 12.4 "Conditional if-else statement" -- the whole if/else is ONE
//       statement_or_null, so the Begin holds exactly one entry, not two or
//       three. Because a trailing "else" is written, the model's node kind is
//       the if-with-else form rather than the bare if form.
//   Sec 12.4.2 "Violation reports generated by unique-if and priority-if
//       constructs" -- no "unique", "unique0" or "priority" keyword precedes
//       the "if", so the statement carries no such qualifier.
//   Sec 12.4 again (grammar) -- neither branch is written with begin/end.
//       Each arm is a single statement_or_null, so each must bind directly
//       and must NOT be wrapped in a Begin.
//   Sec 21.6 "Command line input" -- this is the clause the file is named
//       for. "$test$plusargs(string)" is a system FUNCTION that returns
//       nonzero when the given string matches a plusarg supplied on the
//       command line. That it returns a value is exactly why it can stand as
//       an if condition at all, and it is why it must appear as a SysFuncCall
//       and never as a SysTaskCall. Its name is spelled with two dollar
//       signs, "$test$plusargs", which is the LRM's own spelling and not a
//       "$test" call with a "$plusargs" suffix.
//   Sec 21.2.1 "$display and $write" -- $display is a system TASK, hence a
//       SysTaskCall, and here each call passes exactly one argument: the
//       literal text to print. The two calls carry DIFFERENT text, which is
//       the only thing distinguishing the two arms statically.
//   Sec 5.9 "String literals" -- a string literal is an unsigned integer
//       constant 8 bits wide per character: "TEST" is 4 * 8 = 32 bits,
//       "TEST argument found" is 19 * 8 = 152 bits and "TEST argument not
//       found" is 23 * 8 = 184 bits.
//
// ----------------------------------------------------------------------------
// WHAT IS CHECKED (every assertion below names a concrete value):
//   - module "top" exists and declares nothing at all: no Nets, no
//     Variables, no ports, no parameters and no continuous assignments.
//   - "top" has exactly one process, and it is an Initial and explicitly not
//     a FinalStmt.
//   - the Initial's body is a Begin that declares no variables of its own and
//     holds exactly ONE statement, because Sec 12.4 makes the whole if/else a
//     single statement.
//   - that statement is an IfElse -- the form that carries an else-branch --
//     and its getQualifier() is vpiNoQualifier, since no unique/unique0/
//     priority keyword is written.
//   - its condition is a SysFuncCall named "$test$plusargs" and explicitly
//     NOT a SysTaskCall, carrying exactly one argument: a Constant with
//     constType vpiStringConst, value "TEST" and size 32 bits.
//   - its then-branch binds DIRECTLY to a SysTaskCall named "$display" with
//     no Begin wrapper, and that call carries exactly one argument, a
//     vpiStringConst Constant whose value is "TEST argument found" and whose
//     size is 152 bits.
//   - its else-branch binds DIRECTLY to a SysTaskCall named "$display" with
//     no Begin wrapper, and that call carries exactly one argument, a
//     vpiStringConst Constant whose value is "TEST argument not found" and
//     whose size is 184 bits.
//   - the two $display calls are two DISTINCT nodes carrying two DIFFERENT
//     format strings, so a model that folded the two arms together would
//     fail.
//   - the compiler reports zero fatal / syntax / error diagnostics: every
//     construct above is legal per the clauses cited, and the source carries
//     no ":should_fail_because:" tag.
//
// ----------------------------------------------------------------------------
// WHAT IS NOT CHECKED, AND WHY (permanently out of scope -- HLC is a static
// compiler/elaborator and never a simulator):
//   - Which branch is taken. Sec 21.6 makes $test$plusargs's result depend on
//     the command line the simulation is invoked with, so the answer does not
//     exist until something runs; and even then a compiler has no command
//     line of the simulated kind to consult. Nothing in the model records a
//     call's result. The nearest real assertion is
//     IfConditionIsTestPlusargsOnTheStringTEST, which pins the query that
//     would be asked.
//   - The text actually printed, and any trailing newline. Formatting happens
//     while time advances. What the source DOES determine is the exact text
//     of both literals, and both are asserted verbatim, by
//     ThenBranchDisplaysArgumentFound and ElseBranchDisplaysArgumentNotFound.
//   - Whether a plusarg named "TEST" was in fact supplied. That is a property
//     of how the simulation is launched, not of this source file. The nearest
//     real assertion is again IfConditionIsTestPlusargsOnTheStringTEST, which
//     pins the string being matched.
//   - The Begin's own name. No ": label" is written, so the block is unnamed;
//     whether the model leaves the name empty or synthesizes an implicit
//     scope name is a tool-internal convention the source does not determine.
//     The scoping fact that matters is asserted instead, by
//     InitialBodyIsBeginWithExactlyOneStatement, which requires the block to
//     own no variables of its own.
//   - The design-level typespec collection's size and which scope owns the
//     shared string typespec nodes. Typespec sharing is likewise a
//     tool-internal convention that the source text does not determine.
//   - The warning count. Whether a legal file also draws advisory warnings is
//     tool policy, not something the LRM fixes, so only the fatal/syntax/
//     error counts are asserted below.
//
// No getElaborated() gating is used anywhere in this file. That is the
// correct answer here rather than an omission: the fixture declares no
// object at all, so there is no parameter, no constant expression to reduce,
// no generate construct and no module instantiation -- nothing in it comes
// into existence only after elaboration. Every value asserted below is
// established by parsing alone.
// ============================================================================

#include <hlc/Common/Session.h>
#include <hlc/ErrorReporting/ErrorContainer.h>
#include <hlc/SourceCompile/Compiler.h>
#include <hlc/Tests/Test.h>

#include <hldb/Utils.h>
#include <hldb/any_type.h>
#include <hldb/begin.h>
#include <hldb/constant.h>
#include <hldb/design.h>
#include <hldb/final_stmt.h>
#include <hldb/if_else.h>
#include <hldb/if_stmt.h>
#include <hldb/initial.h>
#include <hldb/module.h>
#include <hldb/net.h>
#include <hldb/process_stmt.h>
#include <hldb/sys_func_call.h>
#include <hldb/sys_task_call.h>
#include <hldb/variable.h>
#include <hldb/vpi_user.h>

namespace hlc {

class TestPlusargsTest : public Test {
 public:
  static void SetUpTestSuite() { Compile(__FILE__, {"-f", "21.6--test.hlc"}); }
  static void TearDownTestSuite() { Shutdown(); }

 protected:
  static const hldb::Module *getTop() { return hldb::findByName<hldb::Module>("top", m_design->getAllModules()); }

  // "initial begin ... end" -- the module's only process.
  static const hldb::Begin *getInitialBody() {
    const hldb::Module *const top = getTop();
    if (top == nullptr || top->getProcesses() == nullptr || top->getProcesses()->empty()) return nullptr;
    const hldb::Initial *const init = any_cast<hldb::Initial>(top->getProcesses()->at(0));
    return (init == nullptr) ? nullptr : init->getStmt<hldb::Begin>();
  }

  // Sec 12.4: the whole if/else is the block's single statement, and because
  // a trailing "else" is written it takes the if-with-else form.
  static const hldb::IfElse *getIfElse() {
    const hldb::Begin *const body = getInitialBody();
    if (body == nullptr || body->getStmts() == nullptr || body->getStmts()->empty()) return nullptr;
    return any_cast<hldb::IfElse>(body->getStmts()->at(0));
  }

  // Shared body for the two "$display(<text>);" arms, which differ only in
  // which branch they hang off and in the literal they carry.
  static void checkDisplayArm(const hldb::SysTaskCall *call, const char *expectedText, int32_t expectedSize,
                              const char *where) {
    ASSERT_NE(call, nullptr) << where << " should be a $display SysTaskCall (Sec 21.2.1)";
    EXPECT_EQ(call->getName(), "$display");
    ASSERT_NE(call->getArguments(), nullptr) << where;
    ASSERT_EQ(call->getArguments()->size(), 1u) << where << ": the call passes just the text to print";

    const hldb::Constant *const text = any_cast<hldb::Constant>(call->getArguments()->at(0));
    ASSERT_NE(text, nullptr) << where << ": the argument is a string literal";
    EXPECT_EQ(text->getConstType(), vpiStringConst) << where;
    EXPECT_EQ(text->getValue(), expectedText) << where;
    EXPECT_EQ(text->getSize(), expectedSize) << where << ": Sec 5.9 -- 8 bits per character";
  }
};

// --- module scope: the file declares nothing at all --------------------------

TEST_F(TestPlusargsTest, ModuleTopExists) { EXPECT_NE(getTop(), nullptr); }

// Sec 6.7 / Sec 6.8: not a single declaration appears anywhere in this file,
// so every one of the module's declaration collections must come back empty.
// Asserting the emptiness is what makes the later statement-shape checks
// meaningful -- nothing was quietly invented to support them.
TEST_F(TestPlusargsTest, ModuleTopDeclaresNothingAtAll) {
  const hldb::Module *const top = getTop();
  ASSERT_NE(top, nullptr);
  EXPECT_TRUE(top->getNets() == nullptr || top->getNets()->empty())
      << "no net-type keyword (IEEE 1800-2023 Sec 6.7) appears anywhere in this file";
  EXPECT_TRUE(top->getVariables() == nullptr || top->getVariables()->empty())
      << "no variable is declared anywhere in this file (Sec 6.8)";
  EXPECT_TRUE(top->getPorts() == nullptr || top->getPorts()->empty()) << "'module top();' has an empty port list";
  EXPECT_TRUE(top->getParameters() == nullptr || top->getParameters()->empty())
      << "no parameter is declared anywhere in this file";
  EXPECT_TRUE(top->getContAssigns() == nullptr || top->getContAssigns()->empty())
      << "the file contains no 'assign' statement";
}

// Sec 9.2.2: one "initial" keyword, one Initial process -- and nothing else.
TEST_F(TestPlusargsTest, ModuleHasExactlyOneInitialProcess) {
  const hldb::Module *const top = getTop();
  ASSERT_NE(top, nullptr);
  ASSERT_NE(top->getProcesses(), nullptr);
  ASSERT_EQ(top->getProcesses()->size(), 1u) << "the file writes exactly one procedure";
  EXPECT_NE(any_cast<hldb::Initial>(top->getProcesses()->at(0)), nullptr) << "that procedure is an 'initial'";
  EXPECT_EQ(any_cast<hldb::FinalStmt>(top->getProcesses()->at(0)), nullptr)
      << "no 'final' keyword is written in this file";
}

// Sec 12.4: the whole "if ... else ..." is ONE statement_or_null, so the block
// holds one entry -- not one for the if and another for the else.
TEST_F(TestPlusargsTest, InitialBodyIsBeginWithExactlyOneStatement) {
  const hldb::Begin *const body = getInitialBody();
  ASSERT_NE(body, nullptr) << "'initial begin ... end' body should be a Begin";
  EXPECT_TRUE(body->getVariables() == nullptr || body->getVariables()->empty())
      << "no block_item_declaration is written inside the begin-end (Sec 9.3.1)";
  ASSERT_NE(body->getStmts(), nullptr);
  EXPECT_EQ(body->getStmts()->size(), 1u)
      << "Sec 12.4: the if and its else are a single statement, so the block holds one entry, not two";
}

// --- the conditional ----------------------------------------------------------

// Sec 12.4: a trailing "else" is written, so this is the if-with-else form,
// not the bare if. Sec 12.4.2: no unique/unique0/priority keyword precedes it.
TEST_F(TestPlusargsTest, StatementIsAnUnqualifiedIfElse) {
  const hldb::Begin *const body = getInitialBody();
  ASSERT_NE(body, nullptr);
  ASSERT_NE(body->getStmts(), nullptr);
  ASSERT_EQ(body->getStmts()->size(), 1u);

  EXPECT_EQ(any_cast<hldb::IfStmt>(body->getStmts()->at(0)), nullptr)
      << "Sec 12.4: an 'else' branch is written, so this is not the bare if form";
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr) << "the block's one statement should be an IfElse";
  EXPECT_EQ(ifElse->getQualifier(), vpiNoQualifier)
      << "Sec 12.4.2: no unique/unique0/priority keyword precedes this if";
}

// THE POINT OF THIS FIXTURE. Sec 21.6: $test$plusargs returns nonzero when the
// string matches a plusarg, and returning a value is exactly what lets it
// stand as an if condition -- so it must be a SysFuncCall. Its name carries
// two dollar signs, which is the LRM's own spelling.
TEST_F(TestPlusargsTest, IfConditionIsTestPlusargsOnTheStringTEST) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);

  EXPECT_EQ(ifElse->getCondition<hldb::SysTaskCall>(), nullptr)
      << "IEEE 1800-2023 Sec 21.6: $test$plusargs returns a value -- that is why it can be a condition "
         "at all -- so it is a system function, not a system task";
  const hldb::SysFuncCall *const cond = ifElse->getCondition<hldb::SysFuncCall>();
  ASSERT_NE(cond, nullptr) << "the condition should be a SysFuncCall";
  EXPECT_EQ(cond->getName(), "$test$plusargs")
      << "Sec 21.6 spells the name with two dollar signs -- it is not a '$test' call carrying a "
         "'$plusargs' suffix";

  ASSERT_NE(cond->getArguments(), nullptr);
  ASSERT_EQ(cond->getArguments()->size(), 1u) << "'$test$plusargs(\"TEST\")' takes exactly one argument";
  const hldb::Constant *const match = any_cast<hldb::Constant>(cond->getArguments()->at(0));
  ASSERT_NE(match, nullptr) << "the argument is the string literal \"TEST\"";
  EXPECT_EQ(match->getConstType(), vpiStringConst);
  EXPECT_EQ(match->getValue(), "TEST");
  EXPECT_EQ(match->getSize(), 32) << "Sec 5.9: \"TEST\" = 4 chars x 8 bits";
}

// --- the two arms -------------------------------------------------------------

// Sec 12.4: the then-arm is a single statement_or_null written without
// begin/end, so it must bind directly rather than through a Begin.
TEST_F(TestPlusargsTest, ThenBranchDisplaysArgumentFound) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);
  EXPECT_EQ(ifElse->getStmt<hldb::Begin>(), nullptr)
      << "Sec 12.4: no begin/end was written on the then-branch, so it must not be wrapped in a Begin";
  EXPECT_EQ(ifElse->getStmt<hldb::SysFuncCall>(), nullptr)
      << "IEEE 1800-2023 Sec 21.2.1: $display returns nothing, so it is a system task";
  checkDisplayArm(ifElse->getStmt<hldb::SysTaskCall>(), "TEST argument found", 152, "the then-branch");
}

// Sec 12.4: likewise for the else-arm.
TEST_F(TestPlusargsTest, ElseBranchDisplaysArgumentNotFound) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);
  ASSERT_NE(ifElse->getElseStmt(), nullptr) << "Sec 12.4: an 'else' branch is written, so one must be present";
  EXPECT_EQ(ifElse->getElseStmt<hldb::Begin>(), nullptr)
      << "Sec 12.4: no begin/end was written on the else-branch, so it must not be wrapped in a Begin";
  EXPECT_EQ(ifElse->getElseStmt<hldb::SysFuncCall>(), nullptr)
      << "IEEE 1800-2023 Sec 21.2.1: $display returns nothing, so it is a system task";
  checkDisplayArm(ifElse->getElseStmt<hldb::SysTaskCall>(), "TEST argument not found", 184, "the else-branch");
}

// The two arms are separately written calls carrying different text, so they
// must be two separate nodes with two separate literals -- a model that folded
// the branches together would pass neither half of this.
TEST_F(TestPlusargsTest, TheTwoArmsAreDistinctCallsWithDistinctText) {
  const hldb::IfElse *const ifElse = getIfElse();
  ASSERT_NE(ifElse, nullptr);

  const hldb::SysTaskCall *const thenCall = ifElse->getStmt<hldb::SysTaskCall>();
  const hldb::SysTaskCall *const elseCall = ifElse->getElseStmt<hldb::SysTaskCall>();
  ASSERT_NE(thenCall, nullptr);
  ASSERT_NE(elseCall, nullptr);
  EXPECT_NE(thenCall, elseCall) << "the two branches are two separately written calls and must be two "
                                   "separate nodes";

  ASSERT_NE(thenCall->getArguments(), nullptr);
  ASSERT_EQ(thenCall->getArguments()->size(), 1u);
  ASSERT_NE(elseCall->getArguments(), nullptr);
  ASSERT_EQ(elseCall->getArguments()->size(), 1u);
  const hldb::Constant *const thenText = any_cast<hldb::Constant>(thenCall->getArguments()->at(0));
  const hldb::Constant *const elseText = any_cast<hldb::Constant>(elseCall->getArguments()->at(0));
  ASSERT_NE(thenText, nullptr);
  ASSERT_NE(elseText, nullptr);
  EXPECT_NE(thenText->getValue(), elseText->getValue())
      << "the two arms print different text -- that difference is the only thing separating them "
         "before anything runs";
}

// --- compiler diagnostics -----------------------------------------------------

// The source carries no ":should_fail_because:" tag and every construct in it
// is legal per the clauses cited above, so nothing may be reported as an
// error. (The warning count is deliberately not asserted -- see the header.)
TEST_F(TestPlusargsTest, CompilerReportsZeroErrors) {
  ASSERT_NE(m_session->getErrorContainer(), nullptr);
  const ErrorContainer::Stats stats = m_session->getErrorContainer()->getErrorStats();
  EXPECT_EQ(stats.nbFatal, 0);
  EXPECT_EQ(stats.nbSyntax, 0);
  EXPECT_EQ(stats.nbError, 0);
}

}  // namespace hlc

int main(int argc, char **argv) {
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
