/*
Copyright 2019 Alain Dargelas

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
 * File:   Compiler.h
 * Author: alain
 *
 * Created on March 4, 2017, 5:16 PM
 */

#ifndef SURELOG_COMPILER_H
#define SURELOG_COMPILER_H
#pragma once

#include <Surelog/Common/PathId.h>
#include <Surelog/Common/SymbolId.h>
#include <Surelog/ErrorReporting/ErrorContainer.h>
#include <Surelog/SourceCompile/CompileAction.h>

#include <uhdm/Serializer.h>
#include <uhdm/uhdm_forward_decl.h>
#include <uhdm/vpi_user.h>

#include <map>
#include <mutex>
#include <set>
#include <string>
#include <string_view>
#include <vector>

namespace SURELOG {
class CompileSourceFile;
class CompilationUnit;
class ConfigSet;
class FileContent;
class Library;
class LibrarySet;
class PreprocessFile;
class Session;
struct AntlrParserHandler;

class Compiler {
 public:
  using PPFileMap = std::map<PathId, std::vector<PathId>, PathIdLessThanComparer>;

  explicit Compiler(Session *session);
  Compiler(Session *session, std::string_view text);
  Compiler(const Compiler &rhs) = delete;
  Compiler &operator=(const Compiler &rhs) = delete;
  ~Compiler();

  bool compile();
  void purgeParsers();

  Session *getSession() { return m_session; }
  const Session *getSession() const { return m_session; }

  uhdm::Serializer &getSerializer() { return m_serializer; }

  std::vector<CompileSourceFile *> &getCompileSourceFiles() { return m_compileSourceFiles; }
  const std::map<SymbolId, AntlrParserHandler *, SymbolIdLessThanComparer> &getPpAntlrHandlerMap() const {
    return m_antlrPpMap;
  }
  void registerAntlrPpHandlerForId(SymbolId id, AntlrParserHandler *pp);
  AntlrParserHandler *getAntlrPpHandlerForId(SymbolId);

  void addOrderedPackage(std::string_view packageName) { m_orderedPackageNames.emplace_back(packageName); }

  uhdm::Design *getUhdmDesign();
  vpiHandle getVpiDesign();

  ErrorContainer::Stats getErrorStats() const;
  bool isLibraryFile(PathId id) const;
  Library *getLibrary(std::string_view name) const;
  LibrarySet *getLibrarySet() const { return m_librarySet; }

  CompileSourceFile *addBuiltin();

  // Compare parser outputs i.e. AST trees generated by two separate
  // compilations of the same/similar source. Spaces (white space and new lines)
  // are safely ignored.
  static bool compareParserOutputs(Compiler *lhs, Compiler *rhs);

 private:
  bool parseLibrariesDef_();

  bool ppinit_();
  bool createFileList_();
  bool createMultiProcessPreProcessor_();
  bool createMultiProcessParser_();
  bool parseinit_();
  bool compileFileSet_(CompileAction action, bool allowMultithread, std::vector<CompileSourceFile *> &container);
  bool compileOneFile_(CompileSourceFile *compileSource, CompileAction action);
  bool cleanup_();

 private:
  uhdm::Serializer m_serializer;
  Session *const m_session = nullptr;
  CompilationUnit *m_commonCompilationUnit = nullptr;
  std::map<SymbolId, AntlrParserHandler *, SymbolIdLessThanComparer> m_antlrPpMap;
  std::vector<CompileSourceFile *> m_compileSourceFiles;
  std::vector<CompileSourceFile *> m_compilerParentFiles;
  std::vector<CompilationUnit *> m_compilationUnits;
  std::vector<std::string> m_orderedPackageNames;
  std::vector<Session *> m_sessions;
  LibrarySet *const m_librarySet = nullptr;
  ConfigSet *const m_configSet = nullptr;
  PathIdSet m_libraryFiles;  // -v <file>
  std::string m_text;        // unit tests
};
};  // namespace SURELOG

#endif  // SURELOG_COMPILER_H
