#!/usr/bin/env python3

"""
Script to extract log and/or DBs out from artifacts generated by CI builds.
NOTE: CI artifacts are hierarhical tarballs i.e. tarball within tarball within tarball.
"""

import argparse
import multiprocessing
import os
import sys
import tarfile
import traceback
import zipfile

from datetime import datetime
from pathlib import Path
from typing import Pattern

from log_compare import logs_equivalent
from utils import build_filters, is_windows, log, mkdir

_this_filepath = Path(__file__).resolve()
_default_workspace_dirpath = _this_filepath.parent.parent

_default_dbname = 'design.hldb'
_platform_ids = ['', '.linux', '.osx', '.win']
_default_test_dirpath = _default_workspace_dirpath / 'hlc'


def _scan(dirpath: Path, filters: list[str|Pattern]):
  def _is_filtered(test_id, name):
    if not filters:
      return True
    for filter in filters:
      if isinstance(filter, str):
        if filter.lower() in (test_id.lower(), name.lower()):
          return True
      elif filter.search(test_id) or filter.search(name):  # Note: match() reports success only if the match is at index 0
        return True
    return False

  tests = {}
  for filepath in dirpath.resolve().rglob('*.hlc'):
    name = filepath.stem
    test_id = filepath.parent.relative_to(dirpath).as_posix()
    if _is_filtered(test_id, name):
      tests[test_id] = filepath

  return { test_id : tests[test_id] for test_id in sorted(tests.keys(), key=lambda t: t.lower()) }


def _extract_worker(params):
  zip_filepath, archive_name, modes, output_dirpath, test_items, skip_noise = params

  result = 0
  with zipfile.ZipFile(zip_filepath, 'r') as zipfile_strm:
    with zipfile_strm.open(f'{archive_name}.tar.gz') as tarfile_strm:
      with tarfile.open(fileobj=tarfile_strm) as archive_strm:
        for test_id, filepath, tarinfo in test_items:
          name = Path(test_id).name

          dst_dirpath = output_dirpath / test_id if output_dirpath else filepath.parent
          mkdir(dst_dirpath)

          with tarfile.open(fileobj=archive_strm.extractfile(tarinfo)) as test_strm:
            if 'db' in modes:
              src_db_filepath = f'{name}/{_default_dbname}'

              if src_db_filepath in test_strm.getnames():
                dst_db_dirpath = dst_dirpath
                mkdir(dst_db_dirpath)

                dst_db_filepath = dst_db_dirpath / _default_dbname

                try:
                  src_strm = test_strm.extractfile(src_db_filepath)

                  with open(dst_db_filepath, 'wb') as dst_strm:
                    dst_strm.write(src_strm.read()) # pyright: ignore[reportOptionalMemberAccess]
                    dst_strm.flush()

                except Exception:
                  log(f'Failed to extract \"{src_db_filepath}\"')
                  traceback.print_exc()
                  result += 1

            if 'log' in modes:
              for platform_id in _platform_ids:
                src_log_filepath = f'{name}/{name}{platform_id}.log'
                if src_log_filepath in test_strm.getnames():
                  dst_log_filepath = dst_dirpath / f'{name}{platform_id}.log'

                  try:
                    src_log_strm = test_strm.extractfile(src_log_filepath)
                    new_bytes = src_log_strm.read() # pyright: ignore[reportOptionalMemberAccess]

                    # Conditionally (only when --skip-noise is passed): if a log already sits at
                    # dst_log_filepath, compare it against the freshly extracted one using
                    # log_compare's tolerant comparison (ignores PROFILE timing, AST_DEBUG block
                    # reordering/id-renumbering, and diagnostic-message reordering -- see
                    # log_compare.py's own module docstring). If the only differences are exactly
                    # that kind of run-to-run noise, leave the existing file untouched instead of
                    # overwriting it -- avoids creating revision history for noise alone.
                    if skip_noise and dst_log_filepath.is_file():
                      old_text = dst_log_filepath.read_text(encoding='utf-8', errors='replace')
                      new_text = new_bytes.decode('utf-8', errors='replace')
                      equivalent, _diffs = logs_equivalent(old_text, new_text)
                      if equivalent:
                        log(f'{src_log_filepath} => {dst_log_filepath} (unchanged: only noise, kept existing)')
                        continue

                    log(f'{src_log_filepath} => {dst_log_filepath}')

                    with dst_log_filepath.open('wb') as dst_log_strm:
                      dst_log_strm.write(new_bytes)
                      dst_log_strm.flush()

                    # On Windows, fixup the line endings
                    if is_windows():
                      with dst_log_filepath.open() as istrm:
                        lines = istrm.readlines()
                      with dst_log_filepath.open('wt') as ostrm:
                        ostrm.writelines(lines)
                        ostrm.flush()

                  except KeyError:
                    log(f'Failed to extract \"{src_log_filepath}\"')
                    traceback.print_exc()
                    result += 1

  return result


def _extract(args, tests):
  if not tests:
    return 0  # No selected tests

  if not args.zip_filepath:
    raise ValueError("Missing required archive path")

  if not args.zip_filepath.is_file():
    raise ValueError("Input archive path is invalid")

  archive_name = args.zip_filepath.name
  pos = str(archive_name).find('.')
  if pos >= 0:
    archive_name = str(archive_name)[:pos]

  # Build a lookup from expected tar member name -> (test_id, filepath)
  member_lookup = {f'{archive_name}/{test_id}.tar.gz': (test_id, fp) for test_id, fp in tests.items()}

  # Read the archive's member list once in the parent, keeping only tests present in this shard
  matched = []
  with zipfile.ZipFile(args.zip_filepath, 'r') as zf:
    with zf.open(f'{archive_name}.tar.gz') as tf_stream:
      with tarfile.open(fileobj=tf_stream) as tf:
        for member in tf.getmembers():
          if member.name in member_lookup:
            test_id, filepath = member_lookup[member.name]
            matched.append((test_id, filepath, member))

  if not matched:
    return 0

  # Sort by byte offset so each worker makes only forward seeks through the compressed stream,
  # avoiding the expensive re-decompression that backward seeks require
  matched.sort(key=lambda x: x[2].offset_data)

  jobs = min(args.jobs, len(matched))

  # Round-robin distribution: interleaves tests across workers while preserving ascending
  # offset order within each worker's list, so forward-seek invariant is maintained
  chunks = [matched[i::jobs] for i in range(jobs)]
  worker_params = [
      (args.zip_filepath, archive_name, args.modes, args.output_dirpath, chunk, args.skip_noise) for chunk in chunks
  ]

  if jobs <= 1:
    results = [_extract_worker(worker_params[0])]
  else:
    with multiprocessing.Pool(processes=jobs) as pool:
      results = pool.map(_extract_worker, worker_params)

  return sum(results)


def _main():
  start_dt = datetime.now()
  print(f'Starting CI artifact extraction @ {str(start_dt)}')

  parser = argparse.ArgumentParser()
  parser.add_argument('modes', nargs='+', choices=['db', 'log'], type=str, help='Pick what to extract')
  parser.add_argument(
      '--output-dirpath', dest='output_dirpath', required=False, type=str,
      help='Output directory path to extract to. If provided, all files are extracted with input directory as root.')
  parser.add_argument(
      '--filters', nargs='+', required=False, default=[], type=str, help='Filter tests matching these regex inputs')
  parser.add_argument(
      '--jobs', nargs='?', required=False, default=multiprocessing.cpu_count(), type=int,
      help='Run tests in parallel, optionally providing max number of concurrent processes. Set 0 to run sequentially.')
  parser.add_argument(
      '--zip-filepath', dest='zip_filepath', required=True, type=str, help='Path to zipfile to extract logs from.')
  parser.add_argument(
      '--skip-noise', dest='skip_noise', action='store_true',
      help='For \'log\' mode: if a log already exists at the destination, keep it instead of overwriting when the '
           'only differences from the freshly extracted one are PROFILE timing, AST_DEBUG block reordering/'
           'id-renumbering, or diagnostic message reordering (see log_compare.py). Off by default -- logs are '
           'always overwritten as before.')
  args = parser.parse_args()

  args.modes = sorted(set(args.modes))
  args.zip_filepath = Path(args.zip_filepath).resolve()

  if args.output_dirpath:
    args.output_dirpath = Path(args.output_dirpath).resolve()
    mkdir(args.output_dirpath)

  args.filters = build_filters(args.filters)
  tests = _scan(_default_test_dirpath, args.filters)

  if (args.jobs == None) or (args.jobs > multiprocessing.cpu_count()):
    args.jobs = multiprocessing.cpu_count()
  if args.jobs > len(tests):
    args.jobs = len(tests)

  print( 'Environment:')
  print(f'   command-line: {" ".join(sys.argv)}')
  print(f'current-dirpath: {os.getcwd()}')
  print(f'   zip-filepath: {args.zip_filepath}')
  print(f' output-dirpath: {args.output_dirpath}')
  print(f'        filters: {args.filters}')
  print(f'           jobs: {args.jobs}')
  print(f'     skip-noise: {args.skip_noise}')
  print(f'          tests: {len(tests)}')
  print( '')

  print(f'Extracting {args.zip_filepath} ...')
  result = _extract(args, tests)

  end_dt = datetime.now()
  delta = round((end_dt - start_dt).total_seconds())

  print( '')
  print(f'Extraction completed @ {str(end_dt)} in {str(delta)} seconds, with {result} failures.')
  return result


if __name__ == '__main__':
  sys.exit(_main())
